import { IconVideo } from "@tabler/icons-react";

import {
  ActionIcon,
  Avatar,
  Container,
  Flex,
  Group,
  Paper,
  SimpleGrid,
  Stack,
  Text,
  Title,
  Tooltip,
} from "@mantine/core";
import { getFormatter, getLocale, getTranslations } from "next-intl/server";
import { fetchProfileRecordings, getFollower } from "./actions/actions";

import { CountryFlag } from "@/app/[locale]/(protected)/components/country-flag";
import { FollowerTypeIcon } from "@/app/[locale]/(protected)/components/follower-type-icon";
import { getSocialUrl } from "@/app/components/open-social";
import { generateAvatarUrl } from "@/app/lib/avatar-url";

import { generateProfileUrl } from "@/app/lib/profile-url";
import { generateAlternates } from "@/app/lib/seo";
import { FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { Metadata } from "next";
import Image from "next/image";

import { notFound } from "next/navigation";
import { ImageVideoPreview } from "./components/image-video-preview";
import { SignupCta } from "./components/signup-cta";

interface PageProps {
  params: Promise<{
    username: string;
    type: string;
  }>;
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ username: string; type: string }>;
}): Promise<Metadata> {
  const { type, username } = await params;
  const t = await getTranslations("profile");
  const locale = await getLocale();
  const follower = await getFollower({ username, type, locale });

  if (!follower) {
    return {
      title: t("meta.notFoundTitle"),
      description: t("meta.notFoundDescription"),
    };
  }

  const platformName = type.charAt(0).toUpperCase() + type.slice(1);
  const translation = {
    nickname: follower.nickname || "",
    username: follower.username,
    platform: platformName,
  };
  const title = t("meta.title", translation);
  const description = follower.tagline || t("meta.description", translation);

  return {
    title,
    description,
    keywords: t("meta.keywords", translation).split(", "),
    openGraph: {
      title: t("meta.ogTitle", translation),
      description,
      type: "profile",
      siteName: "Live Stream Recorder",
      images: [
        `${process.env.NEXT_PUBLIC_BASE_URL}/api/og/${generateProfileUrl(
          follower,
          false,
        )}`,
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: t("meta.twitterTitle", translation),
      description,
      images: [
        `${process.env.NEXT_PUBLIC_BASE_URL}/api/og/${generateProfileUrl(
          follower,
          false,
        )}`,
      ],
    },
    alternates: generateAlternates(`/${type}/${follower.username}`, locale),
  };
}

export default async function Page({ params }: PageProps) {
  const { type, username } = await params;
  const t = await getTranslations("profile");
  const format = await getFormatter();
  const locale = await getLocale();
  const follower = await getFollower({ username, type, locale });

  if (!follower) {
    notFound();
  }

  const data = await fetchProfileRecordings(type, username);
  const recordings = data?.data ?? [];
  const hasRecordings = recordings.length > 0;

  const regionNames = new Intl.DisplayNames(["en"], { type: "region" });
  const getCountryName = (countryCode?: string) => {
    if (!countryCode || countryCode === "-") return undefined;
    return regionNames.of(countryCode.toUpperCase());
  };

  const countryName = getCountryName(follower.countryCode);

  const profileUrl = generateProfileUrl(follower, true);

  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL;
  const platformName = type.charAt(0).toUpperCase() + type.slice(1);

  const breadcrumbSchema = {
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        item: {
          "@id": baseUrl,
          name: "Home",
        },
      },
      {
        "@type": "ListItem",
        position: 2,
        item: {
          "@id": `${baseUrl}/creators/${type}`,
          name: `${platformName} Creators`,
        },
      },
      {
        "@type": "ListItem",
        position: 3,
        item: {
          "@id": profileUrl,
          name: follower.nickname || `@${follower.username}`,
        },
      },
    ],
  };

  const profilePageSchema = {
    "@type": "ProfilePage",
    "@id": profileUrl,
    url: profileUrl,
    mainEntity: {
      "@type": "Person",
      "@id": `${profileUrl}#person`,
      name: follower.username,
      identifier: follower.username,
      alternateName: [follower.nickname, `@${follower.username}`].filter(
        Boolean,
      ),
      description: follower.tagline || follower.description,
      image: generateAvatarUrl(follower.avatar?.url, true),
      url: profileUrl,
      ...(countryName && {
        nationality: {
          "@type": "Country",
          name: countryName,
        },
      }),
      sameAs: [getSocialUrl(follower)],
    },
    hasPart:
      recordings.length > 0
        ? {
            "@type": "ItemList",
            itemListElement: recordings.slice(0, 5).map((video, index) => ({
              "@type": "ListItem",
              position: index + 1,
              url: `${profileUrl}/video/${video.documentId}`,
            })),
          }
        : undefined,
  };

  const faqSchema = follower.faq?.length
    ? {
        "@type": "FAQPage",
        name: `FAQ - ${follower.nickname || follower.username}`,
        mainEntity: follower.faq.map((item: { q: string; a: string }) => ({
          "@type": "Question",
          name: item.q,
          acceptedAnswer: {
            "@type": "Answer",
            text: item.a,
          },
        })),
      }
    : null;

  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      breadcrumbSchema,
      profilePageSchema,
      ...(faqSchema ? [faqSchema] : []),
    ],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <Container size="xl">
        <Stack gap="xl">
          <Flex
            gap="md"
            justify={{ base: "center", sm: "flex-start" }}
            direction={{ base: "column", sm: "row" }}
            align="center"
          >
            <Avatar
              size={100}
              radius={100}
              styles={{
                root: {
                  overflow: "hidden",
                },
              }}
            >
              {follower.avatar?.url && (
                <Image
                  src={generateAvatarUrl(follower.avatar?.url)}
                  alt={follower.nickname || follower.username}
                  width={100}
                  height={100}
                />
              )}
            </Avatar>

            <Stack gap="xs">
              <Group>
                <Title order={1}>{follower.username}</Title>
                {follower.nickname && (
                  <Title order={2} size="lg" fw={400} c="dimmed">
                    {follower.nickname}
                  </Title>
                )}
                {follower.countryCode && (
                  <CountryFlag countryCode={follower.countryCode} size={30} />
                )}
                <Tooltip label={follower.type}>
                  <FollowerTypeIcon
                    color="transparent"
                    type={follower.type}
                    size={30}
                  />
                </Tooltip>
              </Group>

              <Text>
                {follower.tagline ||
                  t("defaultTagline", { nickname: follower.nickname || "" })}
              </Text>
            </Stack>
          </Flex>

          <Stack gap="xl">
            <Stack gap="md">
              {!hasRecordings ? (
                <EmptyState />
              ) : (
                <SimpleGrid cols={{ base: 1, sm: 2 }} spacing="lg">
                  {recordings?.map((rec) => (
                    <Stack key={rec.documentId} gap={4}>
                      <ImageVideoPreview
                        recording={rec}
                        type={type as unknown as FollowerTypeEnum}
                      />
                      <Text size="xs" suppressHydrationWarning>
                        {t("recorded", {
                          date: format.dateTime(new Date(rec.createdAt || ""), {
                            year: "numeric",
                            month: "short",
                            day: "numeric",
                            hour: "numeric",
                            minute: "2-digit",
                          }),
                        })}
                      </Text>
                    </Stack>
                  ))}
                  <SignupCta
                    username={follower.username}
                    recordings={recordings}
                  />
                </SimpleGrid>
              )}
            </Stack>
          </Stack>

          {follower.description ? (
            <Stack gap="xl">
              <div>
                <Title order={2}>
                  {t("about", { nickname: follower.nickname || "" })}
                </Title>
                <Title order={2} size="lg" fw={400} c="dimmed" mt="sm">
                  {follower.description}
                </Title>
              </div>
            </Stack>
          ) : null}

          {follower.faq ? (
            <>
              <Title order={3}>{t("faq")}</Title>
              {follower.faq.map((item: { q: string; a: string }) => (
                <Paper
                  key={item.q}
                  p="md"
                  radius="lg"
                  style={{
                    background: "rgba(255, 255, 255, 0.02)",
                    border: "1px solid rgba(255, 255, 255, 0.06)",
                    cursor: "pointer",
                  }}
                >
                  <Flex justify="space-between" align="center" gap="md">
                    <Text fw={500} style={{ color: "#f1f5f9" }}>
                      {item.q}
                    </Text>
                  </Flex>

                  <Text
                    mt="md"
                    style={{
                      color: "#94a3b8",
                      lineHeight: 1.7,
                      borderTop: "1px solid rgba(255, 255, 255, 0.06)",
                      paddingTop: 12,
                    }}
                  >
                    {item.a}
                  </Text>
                </Paper>
              ))}
            </>
          ) : null}
        </Stack>
      </Container>
    </>
  );
}

async function EmptyState() {
  const t = await getTranslations("profile");

  return (
    <Stack align="center" justify="center" py={80} gap="lg">
      <ActionIcon variant="transparent" size={120} radius="xl" color="white">
        <IconVideo size={90} stroke={2} />
      </ActionIcon>
      <Stack align="center" gap={12}>
        <Title order={2} fw={600}>
          {t("emptyState.title")}
        </Title>
        <Text size="xl" c="dimmed" maw={450} ta="center">
          {t("emptyState.description")}
        </Text>
      </Stack>
    </Stack>
  );
}
