import api from "@/lib/api";
import { ProviderEnum } from "@/lib/types/strapi-autogenerated";
import { cookies } from "next/headers";
import { NextRequest, NextResponse } from "next/server";

interface GoogleTokenResponse {
  access_token: string;
  refresh_token?: string;
  expires_in: number;
  token_type: string;
  error?: string;
  error_description?: string;
}

const STATE_COOKIE = "youtube_oauth_state";

function redirect(path: string): NextResponse {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL!;
  const response = NextResponse.redirect(`${baseUrl}${path}`);
  response.cookies.delete(STATE_COOKIE);
  return response;
}

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams;
  const code = searchParams.get("code");
  const error = searchParams.get("error");
  const state = searchParams.get("state");

  if (error || !code) {
    return redirect("/settings?youtube=error");
  }

  try {
    const clientId = process.env.YOUTUBE_CLIENT_ID!;
    const clientSecret = process.env.YOUTUBE_CLIENT_SECRET!;
    const baseUrl = process.env.NEXT_PUBLIC_BASE_URL!;
    const redirectUri = `${baseUrl}/callback/youtube`;

    // Verify state cookie for CSRF protection
    const cookieStore = await cookies();
    const savedState = cookieStore.get(STATE_COOKIE)?.value;

    if (!savedState || savedState !== state) {
      console.error("YouTube callback: state mismatch");
      return redirect("/settings?youtube=error");
    }

    // Exchange code for tokens
    const tokenResponse = await fetch(
      "https://oauth2.googleapis.com/token",
      {
        method: "POST",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: new URLSearchParams({
          client_id: clientId,
          client_secret: clientSecret,
          code,
          grant_type: "authorization_code",
          redirect_uri: redirectUri,
        }),
      },
    );

    const data: GoogleTokenResponse = await tokenResponse.json();

    if (data.error) {
      console.error("YouTube token exchange failed:", data.error_description);
      return redirect("/settings?youtube=error");
    }

    const expiresAt = new Date(
      Date.now() + data.expires_in * 1000,
    ).toISOString();

    // Check if YouTube is already connected
    const existingYt = await api.socialAccount.meGetSocialAccounts({
      provider: "youtube" as ProviderEnum,
    });

    if (existingYt.data?.data?.length) {
      // Update existing connection
      await api.socialAccount.mePutSocialAccountsId(
        { id: existingYt.data.data[0].documentId! },
        {
          data: {
            accessToken: data.access_token,
            ...(data.refresh_token && { refreshToken: data.refresh_token }),
            expiresAt,
          },
        } as never,
      );
      return redirect("/settings?youtube=connected");
    }

    // Create new YouTube social account
    await api.socialAccount.mePostSocialAccounts({
      data: {
        provider: "youtube" as never,
        providerId: "youtube",
        accessToken: data.access_token,
        refreshToken: data.refresh_token || "",
        expiresAt,
      },
    });

    return redirect("/settings?youtube=connected");
  } catch (error) {
    console.error("YouTube callback error:", error);
    return redirect("/settings?youtube=error");
  }
}
