import { FollowerTypeIcon } from "@/app/[locale]/(protected)/components/follower-type-icon";
import { getUser } from "@/app/actions/user";
import { getProfileUrl } from "@/app/components/open-social";
import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { streamingPlatforms } from "@/app/lib/streaming-platforms";
import { FollowerTypeEnum, ScopeEnum } from "@/lib/types/strapi-autogenerated";
import {
  Anchor,
  Avatar,
  Box,
  Button,
  Card,
  Divider,
  Flex,
  Group,
  Image,
  SimpleGrid,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import {
  IconBrandSafari,
  IconChevronRight,
  IconVideo,
  IconWorldSearch,
} from "@tabler/icons-react";
import { getFormatter, getTranslations } from "next-intl/server";
import NextImage from "next/image";
import Link from "next/link";
import { ImageSpritePreview } from "../components/image-sprite-preview";
import { RecordingMenu } from "../components/recording-menu";
import {
  fetchLatestFollowers,
  fetchRecordingsByPlatform,
} from "./actions/fetch-recordings";

const platformMap: Record<string, FollowerTypeEnum> = {
  TikTok: FollowerTypeEnum.Tiktok,
  Twitch: FollowerTypeEnum.Twitch,
  Kick: FollowerTypeEnum.Kick,
  YouTube: FollowerTypeEnum.Youtube,
  AfreecaTV: FollowerTypeEnum.Afreecatv,
  Pandalive: FollowerTypeEnum.Pandalive,
  Bigo: FollowerTypeEnum.Bigo,
};

export default async function Page() {
  const tc = await getTranslations("protected.common");
  const t = await getTranslations("protected.dashboard");
  const userData = await getUser();
  const username = userData?.data?.username || "";

  const format = await getFormatter();
  const hour = new Date().getHours();
  const greetingKey =
    hour < 12
      ? "greetingMorning"
      : hour < 17
        ? "greetingAfternoon"
        : "greetingEvening";

  const [latestFollowers, myFeed, platformDataRaw] = await Promise.all([
    fetchLatestFollowers(),
    Promise.all(
      streamingPlatforms.map(async (platform) => {
        const type = platformMap[platform.name];
        const recordings = await fetchRecordingsByPlatform(
          ScopeEnum.Following,
          type,
        );
        return {
          ...platform,
          type,
          recordings,
        };
      }),
    ),
    Promise.all(
      streamingPlatforms.map(async (platform) => {
        const type = platformMap[platform.name];
        const recordings = await fetchRecordingsByPlatform(
          ScopeEnum.Discover,
          type,
        );
        return {
          ...platform,
          type,
          recordings,
        };
      }),
    ),
  ]);

  // Filter out platforms with no recordings
  const platformData = platformDataRaw.filter(
    (platform) => platform.recordings.length > 0,
  );

  return (
    <Stack w="100%">
      <Card radius="lg" withBorder p="0">
        <Flex justify="space-between" align="center" w="100%" p="xl">
          <Stack gap={2}>
            <Flex gap="xs" align="center">
              <Title order={1} size="h1" c="white">
                {t(greetingKey, { username })}
              </Title>
            </Flex>
            <Text size="lg" c="white">
              {t("greetingSubtitle")}
            </Text>
          </Stack>
        </Flex>

        <Divider />

        <Box
          py="sm"
          px={{ base: "xs", sm: "md" }}
          style={{ background: "linear-gradient(150deg, #B4F4FF, #52DDE8)" }}
        >
          <Flex justify="space-between" align="center" w="100%">
            <Stack gap={2}>
              <Flex gap="xs" align="center">
                <IconWorldSearch size={24} color="black" />
                <Title order={1} size="lg" c="black">
                  {t("newCreators")}
                </Title>
              </Flex>
            </Stack>
          </Flex>
        </Box>
        <Divider mx={{ base: "-xs", sm: "-md" }} />

        <Flex gap={20} wrap="wrap" p="md">
          {latestFollowers.map((follower) => (
            <div
              key={follower.documentId}
              style={{
                flex: "1 1 calc(16.666% - 17px)",
                minWidth: "140px",
                maxWidth: "180px",
              }}
            >
              <Anchor href={getProfileUrl(follower)} underline="never">
                <Card
                  padding={16}
                  style={{
                    background: "rgba(255, 255, 255, 0.02)",
                    border: "1px solid rgba(255, 255, 255, 0.06)",
                    borderRadius: "16px",
                    cursor: "pointer",
                    textAlign: "center",
                  }}
                >
                  <Stack align="center" gap={8}>
                    <div style={{ position: "relative" }}>
                      <Avatar size={64} radius="xl">
                        <NextImage
                          src={generateAvatarUrl(follower.avatar?.url)}
                          alt={follower.username}
                          width={64}
                          height={64}
                          quality={75}
                        />
                      </Avatar>
                      <FollowerTypeIcon
                        pos="absolute"
                        color="transparent"
                        type={follower.type}
                        top="50%"
                        left="50%"
                        size={32}
                        opacity={0.8}
                        style={{ transform: "translate(-50%, -50%)" }}
                      />
                    </div>
                    <div>
                      <Text fw={600} size="sm" style={{ color: "#f1f5f9" }}>
                        {follower.nickname || follower.username}
                      </Text>
                      <Text size="xs" style={{ color: "#64748b" }}>
                        @{follower.username}
                      </Text>
                    </div>
                  </Stack>
                </Card>
              </Anchor>
            </div>
          ))}
        </Flex>

        {myFeed.some((p) => p.recordings.length > 0) && (
          <>
            <Divider />
            <Box
              style={{
                background: "linear-gradient(150deg, #BDFF88, #5ABB91)",
              }}
              py="sm"
              px={{ base: "xs", sm: "md" }}
            >
              <Flex justify="space-between" align="center" w="100%">
                <Stack gap={2}>
                  <Flex gap="xs" align="center">
                    <IconVideo size={24} color="black" />
                    <Title order={1} size="lg" c="black">
                      {t("myFeed")}
                    </Title>
                  </Flex>
                </Stack>
              </Flex>
            </Box>
            <Divider />

            {myFeed.map((platform) =>
              platform.recordings.length > 0 ? (
                <Stack key={platform.name} gap="md" p="md">
                  <Flex justify="space-between" align="center">
                    <Flex gap="xs" align="center">
                      <Image
                        src={platform.file}
                        alt={platform.name}
                        w={24}
                        h={24}
                        style={{ filter: "brightness(0) invert(1)" }}
                      />
                      <Title order={2} size="h4">
                        {platform.name}
                      </Title>
                    </Flex>
                    <Link href={`/following?type=${platform.type}`}>
                      <Button
                        variant="outline"
                        color="gray"
                        size="sm"
                        rightSection={<IconChevronRight size={16} />}
                      >
                        {t("browseAll")}
                      </Button>
                    </Link>
                  </Flex>

                  <SimpleGrid cols={{ base: 2, sm: 2, md: 4 }} spacing="md">
                    {platform.recordings.map((rec) => (
                      <Stack key={rec.documentId} gap="4">
                        <Box
                          pos="relative"
                          style={{ opacity: rec.hidden ? 0.5 : 1 }}
                        >
                          <ImageSpritePreview
                            recording={rec}
                            username={rec.follower?.username || ""}
                            type={platform.type}
                          />
                        </Box>

                        <Group justify="space-between" align="center">
                          <Text size="xs" suppressHydrationWarning>
                            {format.dateTime(new Date(rec.createdAt || ""), { dateStyle: "medium", timeStyle: "short" })}
                          </Text>
                          {rec.follower && (
                            <RecordingMenu
                              recording={rec}
                              username={rec.follower.username}
                              type={rec.follower.type}
                            />
                          )}
                        </Group>
                      </Stack>
                    ))}
                  </SimpleGrid>
                </Stack>
              ) : null,
            )}
          </>
        )}

        <Divider />
        <Box
          style={{
            background: "linear-gradient(150deg, #FFCCCD , #F8888A)",
          }}
          py="sm"
          px={{ base: "xs", sm: "md" }}
        >
          <Flex justify="space-between" align="center" w="100%">
            <Stack gap={2}>
              <Flex gap="xs" align="center">
                <IconBrandSafari size={24} color="black" />
                <Title order={1} size="lg" c="black">
                  {t("discoverSection")}
                </Title>
              </Flex>
            </Stack>
          </Flex>
        </Box>
        <Divider />

        {platformData.map((platform) => (
          <Stack key={platform.name} gap="md" p="md">
            <Flex justify="space-between" align="center">
              <Flex gap="xs" align="center">
                <Image
                  src={platform.file}
                  alt={platform.name}
                  w={24}
                  h={24}
                  style={{ filter: "brightness(0) invert(1)" }}
                />
                <Title order={2} size="h4">
                  {platform.name}
                </Title>
              </Flex>
              <Link href={`/explore?type=${platform.type}`}>
                <Button
                  variant="outline"
                  color="gray"
                  size="sm"
                  rightSection={<IconChevronRight size={16} />}
                >
                  {t("browseAll")}
                </Button>
              </Link>
            </Flex>

            <SimpleGrid cols={{ base: 2, sm: 2, md: 4 }} spacing="md">
              {platform.recordings.map((rec) => (
                <Stack key={rec.documentId} gap="4">
                  <Box pos="relative" style={{ opacity: rec.hidden ? 0.5 : 1 }}>
                    <ImageSpritePreview
                      recording={rec}
                      username={rec.follower?.username || ""}
                      type={platform.type}
                    />
                  </Box>

                  <Group justify="space-between" align="center">
                    <Text size="xs" suppressHydrationWarning>
                      {format.dateTime(new Date(rec.createdAt || ""), { dateStyle: "medium", timeStyle: "short" })}
                    </Text>
                    {rec.follower && (
                      <RecordingMenu
                        recording={rec}
                        username={rec.follower.username}
                        type={rec.follower.type}
                      />
                    )}
                  </Group>
                </Stack>
              ))}
            </SimpleGrid>
          </Stack>
        ))}
      </Card>
    </Stack>
  );
}
