import { getUser } from "@/app/actions/user";
import { streamingPlatforms } from "@/app/lib/streaming-platforms";
import { FollowerTypeEnum, ScopeEnum } from "@/lib/types/strapi-autogenerated";
import {
  Box,
  Card,
  Divider,
  Flex,
  Skeleton,
  Stack,
  Title,
} from "@mantine/core";
import { IconWorldSearch } from "@tabler/icons-react";
import { getTranslations } from "next-intl/server";
import { Suspense } from "react";
import {
  fetchLatestFollowers,
  fetchRecordingsByPlatform,
} from "./actions/fetch-recordings";
import { DiscoverSection } from "./components/discover-section";
import { GreetingSection } from "./components/greeting-section";
import { LatestFollowersSection } from "./components/latest-followers-section";
import { MyFeedSection } from "./components/my-feed-section";

const platformMap: Record<string, FollowerTypeEnum> = {
  TikTok: FollowerTypeEnum.Tiktok,
  Twitch: FollowerTypeEnum.Twitch,
  Kick: FollowerTypeEnum.Kick,
  YouTube: FollowerTypeEnum.Youtube,
  AfreecaTV: FollowerTypeEnum.Afreecatv,
  Pandalive: FollowerTypeEnum.Pandalive,
  Bigo: FollowerTypeEnum.Bigo,
  Buzzcast: FollowerTypeEnum.Buzzcast,
  LiveMe: FollowerTypeEnum.Liveme,
};

export default async function Page() {
  const t = await getTranslations("protected.dashboard");

  // Start all promises without awaiting - they run in parallel
  const userPromise = getUser();
  const followersPromise = fetchLatestFollowers();

  const myFeedPromise = Promise.all(
    streamingPlatforms.map(async (platform) => {
      const type = platformMap[platform.name];
      const recordings = await fetchRecordingsByPlatform(
        ScopeEnum.Following,
        type,
      );
      return { ...platform, type, recordings };
    }),
  );

  const discoverPromise = Promise.all(
    streamingPlatforms.map(async (platform) => {
      const type = platformMap[platform.name];
      const recordings = await fetchRecordingsByPlatform(
        ScopeEnum.Discover,
        type,
      );
      return { ...platform, type, recordings };
    }),
  );

  return (
    <Stack w="100%">
      <Card radius="lg" withBorder p="0">
        <Suspense fallback={<Skeleton h={80} m="xl" radius="md" />}>
          <GreetingSection userPromise={userPromise} />
        </Suspense>

        <Divider />

        <Box
          py="sm"
          px={{ base: "xs", sm: "md" }}
          style={{ background: "linear-gradient(150deg, #B4F4FF, #52DDE8)" }}
        >
          <Flex justify="space-between" align="center" w="100%">
            <Stack gap={2}>
              <Flex gap="xs" align="center">
                <IconWorldSearch size={24} color="black" />
                <Title order={1} size="lg" c="black">
                  {t("newCreators")}
                </Title>
              </Flex>
            </Stack>
          </Flex>
        </Box>
        <Divider mx={{ base: "-xs", sm: "-md" }} />

        <Suspense fallback={<Skeleton h={120} radius="md" m="md" />}>
          <LatestFollowersSection followersPromise={followersPromise} />
        </Suspense>

        <Suspense fallback={<Skeleton h={360} radius="md" m="md" />}>
          <MyFeedSection myFeedPromise={myFeedPromise} />
        </Suspense>

        <Suspense fallback={<Skeleton h={360} radius="md" m="md" />}>
          <DiscoverSection discoverPromise={discoverPromise} />
        </Suspense>
      </Card>
    </Stack>
  );
}
