"use client";

import { DailyEarnings } from "@/lib/types/analytics-autogenerated";
import { Box, Paper, Text, Title } from "@mantine/core";
import { AreaChart } from "@mantine/charts";
import { useTranslations } from "next-intl";
import { use } from "react";

interface EarningsChartProps {
  earningsPromise: Promise<DailyEarnings[]>;
}

export function EarningsChart({ earningsPromise }: EarningsChartProps) {
  const t = useTranslations("protected.profileInsights");
  const earnings = use(earningsPromise);

  const header = (
    <Box
      style={{
        background: "linear-gradient(150deg, #FFFDB4, #E8C252)",
        borderTopLeftRadius: 8,
        borderTopRightRadius: 8,
      }}
      p="md"
    >
      <Title order={5} c="black">{t("earnings.title")}</Title>
    </Box>
  );

  if (!earnings.length) {
    return (
      <Paper withBorder radius="md">
        {header}
        <Box p="md">
          <Text c="dimmed" size="sm">{t("earnings.empty")}</Text>
        </Box>
      </Paper>
    );
  }

  const data = [...earnings].reverse().map((e) => ({
    date: e.date ?? "",
    diamonds: e.diamonds ?? 0,
  }));

  return (
    <Paper withBorder radius="md" style={{ minWidth: 0 }}>
      {header}
      <Box p="md">
        <AreaChart
          h={220}
          w="100%"
          data={data}
          dataKey="date"
          series={[{ name: "diamonds", label: t("earnings.seriesLabel"), color: "yellow.5" }]}
          curveType="monotone"
          tickLine="xy"
          gridAxis="xy"
          withLegend
          withTooltip
          areaChartProps={{ syncId: "earnings" }}
        />
      </Box>
    </Paper>
  );
}
