"use client";

import { ScheduleDay } from "@/lib/types/analytics-autogenerated";
import { Box, Group, Paper, SimpleGrid, Text, Title } from "@mantine/core";
import { IconClock } from "@tabler/icons-react";
import { useFormatter, useTranslations } from "next-intl";
import { use } from "react";

const DAY_KEYS = [
  { key: 1, t: "mon" },
  { key: 2, t: "tue" },
  { key: 3, t: "wed" },
  { key: 4, t: "thu" },
  { key: 5, t: "fri" },
  { key: 6, t: "sat" },
  { key: 7, t: "sun" },
] as const;

interface ScheduleChartProps {
  schedulePromise: Promise<ScheduleDay[]>;
}

export function ScheduleChart({ schedulePromise }: ScheduleChartProps) {
  const t = useTranslations("protected.profileInsights");
  const format = useFormatter();
  const schedule = use(schedulePromise);

  function formatHour(h: number): string {
    const d = new Date(2000, 0, 1, h, 0, 0);
    return format.dateTime(d, { hour: "numeric" });
  }

  const data = DAY_KEYS.map((d) => {
    const found = schedule.find((s) => s.day_of_week === d.key);
    return {
      key: d.key,
      label: t(`schedule.${d.t}`),
      hours: found ? Math.round((found.total_hours ?? 0) * 10) / 10 : 0,
      streams: found?.stream_count ?? 0,
      startHour: found?.typical_start_hour ?? null,
      endHour: found?.typical_end_hour ?? null,
    };
  });

  return (
    <Paper withBorder radius="md">
      <Box
        style={{
          background: "linear-gradient(150deg, #D4B4FF, #9452E8)",
          borderTopLeftRadius: 8,
          borderTopRightRadius: 8,
        }}
        p="md"
      >
        <Title order={5} c="black">
          {t("schedule.title")}
        </Title>
      </Box>
      <Box p="md">
        <SimpleGrid cols={{ base: 3, sm: 7 }} spacing="xs">
          {data.map((d) => (
            <Paper
              key={d.key}
              withBorder
              p="xs"
              radius="md"
              style={{
                textAlign: "center",
                opacity: d.streams === 0 ? 0.35 : 1,
              }}
            >
              <Text size="lg" fw={700}>
                {d.label}
              </Text>
              {d.startHour !== null && d.endHour !== null ? (
                <Group gap={2} justify="center" mt={4} wrap="nowrap">
                  <IconClock size={14} />
                  <Text fw={600} size="md">
                    {formatHour(d.startHour)} - {formatHour(d.endHour)}
                  </Text>
                </Group>
              ) : (
                <Text size="md" c="dimmed" mt={4}>
                  —
                </Text>
              )}
              <Text size="xs" c="dimmed" mt={2}>
                {d.streams}×
              </Text>
            </Paper>
          ))}
        </SimpleGrid>
      </Box>
    </Paper>
  );
}
