"use client";

import { StreamerStats } from "@/lib/types/analytics-autogenerated";
import {
  Group,
  Paper,
  SimpleGrid,
  Stack,
  Text,
  ThemeIcon,
} from "@mantine/core";
import {
  IconStar,
  IconSword,
  IconSwordOff,
  IconTrophy,
  IconUser,
  IconUsers,
} from "@tabler/icons-react";
import { useTranslations } from "next-intl";
import { use } from "react";
import { formatCompact } from "../lib";

interface StatCardProps {
  label: string;
  value: number | string;
  icon: React.FC<{ size?: number; color?: string }>;
  color: string;
  breakdown?: { battle: number; nonBattle: number; total: number; battleLabel: string; nonBattleLabel: string };
}

function StatCard({ label, value, icon: Icon, color, breakdown }: StatCardProps) {
  return (
    <Paper withBorder p="md" radius="md">
      <Group justify="space-between" wrap="nowrap">
        <div>
          <Text size="xs" c="dimmed" tt="uppercase" fw={600} lh={1.2}>
            {label}
          </Text>
          <Text fw={700} size="xl" mt={4}>
            {typeof value === "number" ? formatCompact(value) : value}
          </Text>
        </div>
        <ThemeIcon size={44} radius="md" color={color} variant="light">
          <Icon size={22} />
        </ThemeIcon>
      </Group>
      {breakdown && breakdown.total > 0 && (
        <Stack gap={2} mt="xs">
          <Group justify="space-between">
            <Text size="xs" c="dimmed">{breakdown.battleLabel}</Text>
            <Text size="xs" fw={600}>{formatCompact(breakdown.battle)}</Text>
          </Group>
          <Group justify="space-between">
            <Text size="xs" c="dimmed">{breakdown.nonBattleLabel}</Text>
            <Text size="xs" fw={600}>{formatCompact(breakdown.nonBattle)}</Text>
          </Group>
        </Stack>
      )}
    </Paper>
  );
}

interface BattleCardProps {
  won: number;
  lost: number;
  winRate: number;
  labelTitle: string;
  labelWon: string;
  labelLost: string;
  labelWinRate: string;
}

function BattleCard({ won, lost, winRate, labelTitle, labelWon, labelLost, labelWinRate }: BattleCardProps) {
  return (
    <Paper withBorder p="md" radius="md">
      <Text size="xs" c="dimmed" tt="uppercase" fw={600} lh={1.2} mb="xs">
        {labelTitle}
      </Text>
      <Group justify="space-between" wrap="nowrap">
        <Stack gap={2} align="center">
          <ThemeIcon size={32} radius="md" color="green" variant="light">
            <IconTrophy size={16} />
          </ThemeIcon>
          <Text fw={700} size="lg" c="green">{formatCompact(won)}</Text>
          <Text size="xs" c="dimmed">{labelWon}</Text>
        </Stack>
        <Stack gap={2} align="center">
          <ThemeIcon size={32} radius="md" color="red" variant="light">
            <IconSwordOff size={16} />
          </ThemeIcon>
          <Text fw={700} size="lg" c="red">{formatCompact(lost)}</Text>
          <Text size="xs" c="dimmed">{labelLost}</Text>
        </Stack>
        <Stack gap={2} align="center">
          <ThemeIcon size={32} radius="md" color="teal" variant="light">
            <IconSword size={16} />
          </ThemeIcon>
          <Text fw={700} size="lg" c="teal">{winRate}%</Text>
          <Text size="xs" c="dimmed">{labelWinRate}</Text>
        </Stack>
      </Group>
    </Paper>
  );
}

interface StatsOverviewProps {
  statsPromise: Promise<StreamerStats | null>;
}

export function StatsOverview({ statsPromise }: StatsOverviewProps) {
  const t = useTranslations("protected.profileInsights");
  const stats = use(statsPromise);
  if (!stats) return null;

  const winRate =
    stats.total_battles && stats.total_battles > 0
      ? Math.round(((stats.battles_won ?? 0) / stats.total_battles) * 100)
      : 0;

  return (
    <SimpleGrid cols={{ base: 2, sm: 3, lg: 4 }} spacing="md">
      <StatCard
        label={t("stats.totalDiamonds")}
        value={stats.total_diamonds ?? 0}
        icon={IconStar}
        color="yellow"
        breakdown={{
          battle: stats.battle_diamonds ?? 0,
          nonBattle: stats.non_battle_diamonds ?? 0,
          total: stats.total_diamonds ?? 0,
          battleLabel: t("stats.battleDiamonds"),
          nonBattleLabel: t("stats.nonBattleDiamonds"),
        }}
      />
      <BattleCard
        won={stats.battles_won ?? 0}
        lost={stats.battles_lost ?? 0}
        winRate={winRate}
        labelTitle={t("stats.battles")}
        labelWon={t("stats.won")}
        labelLost={t("stats.lost")}
        labelWinRate={t("stats.winRate")}
      />
      <StatCard
        label={t("stats.gifters")}
        value={stats.unique_gifters ?? 0}
        icon={IconUsers}
        color="violet"
      />
      <StatCard
        label={t("stats.chatParticipants")}
        value={stats.unique_chatters ?? 0}
        icon={IconUser}
        color="cyan"
      />
    </SimpleGrid>
  );
}
