"use client";

import { ActivityPage, getStreamerActivity } from "@/app/actions/analytics";
import { StreamSession } from "@/lib/types/analytics-autogenerated";
import {
  Badge,
  Box,
  LoadingOverlay,
  Pagination,
  Paper,
  Table,
  TableScrollContainer,
  TableTh,
  TableThead,
  TableTr,
  Text,
  Title,
} from "@mantine/core";
import { useFormatter, useTranslations } from "next-intl";
import { use, useState } from "react";
import { formatCompact } from "../lib";

const DATE_FORMAT = {
  year: "numeric",
  month: "short",
  day: "numeric",
  hour: "numeric",
  minute: "2-digit",
} as const;

const LIMIT = 20;

interface StreamActivityProps {
  username: string;
  activityPromise: Promise<ActivityPage>;
}

export function StreamActivity({
  username,
  activityPromise,
}: StreamActivityProps) {
  const t = useTranslations("protected.profileInsights");
  const format = useFormatter();
  const initialData = use(activityPromise);
  const [sessions, setSessions] = useState<StreamSession[]>(initialData.data);
  const [total, setTotal] = useState(initialData.total);
  const [activePage, setActivePage] = useState(1);
  const [loading, setLoading] = useState(false);

  const totalPages = Math.ceil(total / LIMIT);

  const handlePageChange = async (page: number) => {
    setActivePage(page);
    setLoading(true);
    const result = await getStreamerActivity(
      username,
      LIMIT,
      (page - 1) * LIMIT,
    );
    setSessions(result.data);
    setTotal(result.total);
    setLoading(false);
  };

  function formatDuration(minutes: number) {
    const h = Math.floor(minutes / 60);
    const m = minutes % 60;
    if (h === 0) return t("streamActivity.durationMinutes", { m });
    return t("streamActivity.durationHoursMinutes", { h, m });
  }

  const header = (
    <Box
      style={{
        background: "linear-gradient(150deg, #B4FFE4, #52E8A8)",
        borderTopLeftRadius: 8,
        borderTopRightRadius: 8,
      }}
      p="md"
    >
      <Title order={5} c="black">
        {t("streamActivity.title")}
        {total > 0 && (
          <Text span size="sm" fw={400} c="dark.3" ml={8}>
            ({total})
          </Text>
        )}
      </Title>
    </Box>
  );

  if (!sessions.length && !loading) {
    return (
      <Paper withBorder radius="md">
        {header}
        <Box p="md">
          <Text c="dimmed" size="sm">
            {t("streamActivity.empty")}
          </Text>
        </Box>
      </Paper>
    );
  }

  return (
    <Paper withBorder radius="md">
      {header}

      <Box style={{ position: "relative" }}>
        <LoadingOverlay
          visible={loading}
          zIndex={1}
          overlayProps={{ radius: "sm", blur: 2 }}
        />
        <TableScrollContainer minWidth={700}>
          <Table striped highlightOnHover withTableBorder={false} fz="sm">
            <TableThead>
              <TableTr>
                <TableTh>{t("streamActivity.colDate")}</TableTh>
                <TableTh>{t("streamActivity.colDuration")}</TableTh>
                <TableTh>{t("streamActivity.colPeakViewers")}</TableTh>
                <TableTh>{t("streamActivity.colAvgViewers")}</TableTh>
                <TableTh>{t("streamActivity.colDiamonds")}</TableTh>
                <TableTh>{t("streamActivity.colBattles")}</TableTh>
              </TableTr>
            </TableThead>
            <Table.Tbody>
              {sessions.map((s, i) => (
                <TableTr key={s.room_id ?? i}>
                  <Table.Td>
                    <Text size="sm">
                      {s.started_at
                        ? format.dateTime(new Date(s.started_at), DATE_FORMAT)
                        : "—"}
                    </Text>
                  </Table.Td>
                  <Table.Td>
                    {s.duration_minutes != null
                      ? formatDuration(s.duration_minutes)
                      : "—"}
                  </Table.Td>
                  <Table.Td>{formatCompact(s.peak_viewers ?? 0)}</Table.Td>
                  <Table.Td>{formatCompact(s.avg_viewers ?? 0)}</Table.Td>
                  <Table.Td>
                    <Badge color="yellow" variant="light" size="sm">
                      {formatCompact(s.diamonds ?? 0)}
                    </Badge>
                  </Table.Td>
                  <Table.Td>{s.battles ?? 0}</Table.Td>
                </TableTr>
              ))}
            </Table.Tbody>
          </Table>
        </TableScrollContainer>
      </Box>

      {totalPages > 1 && (
        <Box p="md" style={{ display: "flex", justifyContent: "center" }}>
          <Pagination
            total={totalPages}
            value={activePage}
            onChange={handlePageChange}
            size="sm"
          />
        </Box>
      )}
    </Paper>
  );
}
