"use client";

import { Opponent } from "@/lib/types/analytics-autogenerated";
import { useTranslations } from "next-intl";
import { use } from "react";
import {
  Badge,
  Box,
  Group,
  Paper,
  Progress,
  Stack,
  Text,
  Title,
} from "@mantine/core";

interface TopOpponentsProps {
  opponentsPromise: Promise<Opponent[]>;
}

export function TopOpponents({ opponentsPromise }: TopOpponentsProps) {
  const t = useTranslations("protected.profileInsights");
  const opponents = use(opponentsPromise);

  const header = (
    <Box
      style={{
        background: "linear-gradient(150deg, #B4F4FF, #52DDE8)",
        borderTopLeftRadius: 8,
        borderTopRightRadius: 8,
      }}
      p="md"
    >
      <Title order={5} c="black">
        {t("topOpponents.title")}
      </Title>
    </Box>
  );

  if (!opponents.length) {
    return (
      <Paper withBorder radius="md">
        {header}
        <Text c="dimmed" size="sm" p="md">
          {t("topOpponents.empty")}
        </Text>
      </Paper>
    );
  }

  return (
    <Paper withBorder radius="md">
      {header}
      <Stack gap="sm" p="md">
        {opponents.map((o, i) => {
          const total = o.battles ?? 1;
          const winRate = Math.round(((o.wins ?? 0) / total) * 100);
          return (
            <div key={o.opponent_username ?? i}>
              <Group justify="space-between" mb={4} wrap="nowrap">
                <Text size="md" fw={500} truncate>
                  @{o.opponent_username}
                </Text>
                <Group gap="xs" style={{ flexShrink: 0 }}>
                  <Badge color="green" variant="light" size="md">
                    {t("topOpponents.wins", { count: o.wins ?? 0 })}
                  </Badge>
                  <Badge color="red" variant="light" size="md">
                    {t("topOpponents.losses", { count: o.losses ?? 0 })}
                  </Badge>
                  <Text size="md" c="dimmed">
                    {t("topOpponents.battleCount", { count: total })}
                  </Text>
                </Group>
              </Group>
              <Progress
                value={winRate}
                color={winRate >= 50 ? "green" : "red"}
                size="md"
                radius="xl"
              />
            </div>
          );
        })}
      </Stack>
    </Paper>
  );
}
