"use client";

import { TopGifter } from "@/lib/types/analytics-autogenerated";
import { formatCompact } from "../lib";
import { useTranslations } from "next-intl";
import { use } from "react";
import {
  Avatar,
  Badge,
  Box,
  Group,
  Paper,
  Progress,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import { IconStar } from "@tabler/icons-react";

interface TopGiftersProps {
  giftersPromise: Promise<TopGifter[]>;
}

export function TopGifters({ giftersPromise }: TopGiftersProps) {
  const t = useTranslations("protected.profileInsights");
  const gifters = use(giftersPromise);
  const header = (
    <Box
      style={{
        background: "linear-gradient(150deg, #FFB4F0, #E852D0)",
        borderTopLeftRadius: 8,
        borderTopRightRadius: 8,
      }}
      p="md"
    >
      <Title order={5} c="black">{t("topGifters.title")}</Title>
    </Box>
  );

  if (!gifters.length) {
    return (
      <Paper withBorder radius="md">
        {header}
        <Box p="md">
          <Text c="dimmed" size="sm">{t("topGifters.empty")}</Text>
        </Box>
      </Paper>
    );
  }

  const max = gifters[0]?.diamonds ?? 1;

  return (
    <Paper withBorder radius="md">
      {header}
      <Stack gap="sm" p="md">
        {gifters.map((g, i) => (
          <div key={g.sender_username ?? i}>
            <Group justify="space-between" mb={4} wrap="nowrap">
              <Group gap="xs" wrap="nowrap">
                <Avatar size="sm" color="violet" radius="xl">
                  {(g.sender_username ?? "?")[0].toUpperCase()}
                </Avatar>
                <div style={{ minWidth: 0 }}>
                  <Group gap={4} wrap="nowrap">
                    <Text size="sm" fw={500} truncate>
                      @{g.sender_username}
                    </Text>
                    {g.sender_nickname && (
                      <Text size="sm" c="dimmed" truncate>
                        ({g.sender_nickname})
                      </Text>
                    )}
                  </Group>
                  <Text size="xs" c="dimmed">
                    {t("topGifters.giftCount", { count: g.gift_count ?? 0 })}
                  </Text>
                </div>
              </Group>
              <Badge
                leftSection={<IconStar size={10} />}
                color="yellow"
                variant="light"
                size="sm"
                style={{ flexShrink: 0 }}
              >
                {formatCompact(g.diamonds ?? 0)}
              </Badge>
            </Group>
            <Progress
              value={((g.diamonds ?? 0) / max) * 100}
              color="yellow"
              size="xs"
              radius="xl"
            />
          </div>
        ))}
      </Stack>
    </Paper>
  );
}
