"use client";

import { follow, updateFollower } from "@/app/actions/followers";
import { Can, Role } from "@/app/providers/ability-provider";
import { Follower, FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { ActionIcon, Button, Menu } from "@mantine/core";
import {
  IconCheck,
  IconLock,
  IconLockOpen2,
  IconMovie,
  IconMovieOff,
  IconPlayerPause,
  IconPlayerPlay,
  IconTransformPoint,
  IconTrash,
} from "@tabler/icons-react";
import { useState, useTransition } from "react";

export function AdminMenu({ follower, showLabel }: { follower: Follower; showLabel?: boolean }) {
  const [isPending, startTransition] = useTransition();
  const [paused, setPaused] = useState(follower.pause || false);

  const [protect, setProtect] = useState(follower.protected || false);
  const [encode, setEncode] = useState(follower.encode || false);

  const handlePaused = () => {
    const nextPaused = !paused;
    setPaused(nextPaused);

    startTransition(async () => {
      await updateFollower(follower.documentId!, {
        pause: nextPaused,
      });
    });
  };

  const handleDelete = () => {};

  const handleCheck = () => {
    startTransition(async () => {
      await follow(follower.username!, follower.type as FollowerTypeEnum);
    });
  };

  const handleProtected = () => {
    const nextProtected = !protect;
    setProtect(nextProtected);

    startTransition(async () => {
      await updateFollower(follower.documentId!, {
        protected: nextProtected,
      });
    });
  };

  const handleEncode = () => {
    const nextEncode = !encode;
    setEncode(nextEncode);

    startTransition(async () => {
      await updateFollower(follower.documentId!, {
        encode: nextEncode,
      });
    });
  };

  return (
    <Role is={["admin", "moderator"]}>
      <Menu width={200} shadow="md" position="bottom-start">
        <Menu.Target>
          {showLabel ? (
            <Button size="sm" radius="xl" color="yellow" leftSection={<IconTransformPoint size={18} />}>
              Admin
            </Button>
          ) : (
            <ActionIcon size="lg" color="yellow">
              <IconTransformPoint />
            </ActionIcon>
          )}
        </Menu.Target>

        <Menu.Dropdown>
          <Can I="update" a="Follower">
            <Menu.Item
              leftSection={paused ? <IconPlayerPlay /> : <IconPlayerPause />}
              onClick={handlePaused}
            >
              {paused ? "Resume download" : "Pause download"}
            </Menu.Item>
          </Can>
          <Can I="update" a="Follower">
            <Menu.Item
              leftSection={protect ? <IconLock /> : <IconLockOpen2 />}
              onClick={handleProtected}
            >
              {protect ? "Unlock" : "Lock"}
            </Menu.Item>
          </Can>
          <Can I="update" a="Follower">
            <Menu.Item
              leftSection={encode ? <IconMovieOff /> : <IconMovie />}
              onClick={handleEncode}
            >
              {encode ? "Disable Encoding" : "Enable Encoding"}
            </Menu.Item>
          </Can>
          <Can I="update" a="Follower">
            <Menu.Item leftSection={<IconCheck />} onClick={handleCheck}>
              Check
            </Menu.Item>
          </Can>
          <Can I="delete" a="Follower">
            <Menu.Item leftSection={<IconTrash />} onClick={handleDelete}>
              Delete
            </Menu.Item>
          </Can>
        </Menu.Dropdown>
      </Menu>
    </Role>
  );
}
