"use client";

import { ImageSpritePreview } from "@/app/[locale]/(protected)/components/image-sprite-preview";
import { RecordingMenu } from "@/app/[locale]/(protected)/components/recording-menu";
import {
  FollowerTypeEnum,
  SourceStateEnum,
} from "@/lib/types/strapi-autogenerated";
import {
  Group,
  Loader,
  SimpleGrid,
  Stack,
  Text,
} from "@mantine/core";
import { useIntersection } from "@mantine/hooks";
import { useInfiniteQuery } from "@tanstack/react-query";
import { useParams } from "next/navigation";
import { useQueryStates } from "nuqs";
import { useEffect } from "react";

import { safeRelativeTime } from "@/app/lib/safe-relative-time";
import { useFormatter, useNow, useTranslations } from "next-intl";
import { fetchProfileRecordings } from "../actions/actions";
import { profileParsers } from "../lib/search-params";

export default function ProfileRecordings() {
  const t = useTranslations("protected.common");
  const format = useFormatter();
  const now = useNow();
  const params = useParams<{ type: FollowerTypeEnum; username: string }>();
  const [filters] = useQueryStates(profileParsers);

  const { data, fetchNextPage, hasNextPage, isFetchingNextPage, isLoading } =
    useInfiniteQuery({
      queryKey: ["profile-recordings", params.type, params.username, filters],
      queryFn: ({ pageParam }) =>
        fetchProfileRecordings(
          params.type,
          params.username,
          filters,
          pageParam,
        ),
      initialPageParam: 1,
      getNextPageParam: (lastPage) => {
        const { page = 1, pageCount = 0 } = lastPage.meta?.pagination ?? {};
        return page < pageCount ? page + 1 : undefined;
      },
    });

  const { ref, entry } = useIntersection({ threshold: 0.5 });

  useEffect(() => {
    if (entry?.isIntersecting && hasNextPage && !isFetchingNextPage) {
      fetchNextPage();
    }
  }, [entry?.isIntersecting, hasNextPage, isFetchingNextPage, fetchNextPage]);

  const recordings = data?.pages.flatMap((p) => p.data) ?? [];

  if (isLoading) {
    return (
      <Stack align="center" py="xl">
        <Loader size="lg" />
      </Stack>
    );
  }

  return (
    <Stack gap="md">
      <SimpleGrid cols={{ base: 1, sm: 2, md: 3, xl: 4 }} spacing="lg">
        {recordings.map((rec) => {
          const isRecording = rec.sources?.some(
            (s) => s.state === SourceStateEnum.Recording,
          );

          return (
            <Stack key={rec.documentId} gap={4}>
              <ImageSpritePreview
                recording={rec}
                username={params.username}
                type={params.type}
              />

              <Group justify="space-between">
                <Text size="xs" suppressHydrationWarning>
                  {isRecording
                    ? t("recordings.liveAgo", {
                        time: safeRelativeTime(format, rec.createdAt, {
                          style: "narrow",
                          now,
                        }),
                      })
                    : t("recordings.recordedAgo", {
                        time: safeRelativeTime(format, rec.createdAt, {
                          now,
                        }),
                      })}
                </Text>
                <RecordingMenu
                  recording={rec}
                  username={params.username}
                  type={params.type}
                />
              </Group>
            </Stack>
          );
        })}
      </SimpleGrid>

      {hasNextPage && !isFetchingNextPage && (
        <div ref={ref} style={{ height: 20 }} />
      )}
      {isFetchingNextPage && (
        <Loader size="sm" style={{ alignSelf: "center" }} />
      )}
      {!hasNextPage && recordings.length > 0 && (
        <Text ta="center" c="dimmed" size="sm" suppressHydrationWarning>
          {t("recordings.noRecordings")}
        </Text>
      )}
    </Stack>
  );
}
