"use client";

import { getProfileUrl } from "@/app/components/open-social";
import { FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { Badge, Flex, SegmentedControl, Tabs } from "@mantine/core";
import { IconChartBar, IconScissors, IconVideo } from "@tabler/icons-react";
import { useTranslations } from "next-intl";
import { usePathname, useRouter } from "next/navigation";
import { useQueryStates } from "nuqs";
import { profileParsers, SortOptions } from "../lib/search-params";

interface ProfileTabsProps {
  type: string;
  username: string;
  clipsCount?: number;
}

export function ProfileTabs({ type, username, clipsCount }: ProfileTabsProps) {
  const t = useTranslations("protected.common");
  const tInsights = useTranslations("protected.profileInsights");
  const router = useRouter();
  const pathname = usePathname();
  const [filters, setFilters] = useQueryStates(profileParsers);

  const isInsights = pathname.endsWith("/insights");
  const isClips = pathname.endsWith("/clips");
  const isTiktok = type === FollowerTypeEnum.Tiktok;
  const activeTab = isInsights ? "insights" : isClips ? "clips" : "videos";

  if (isTiktok) {
    const profileUrl = getProfileUrl({ type, username });
    return (
      <Tabs
        value={activeTab}
        onChange={(value) => {
          if (value === "insights") {
            router.push(profileUrl + "/insights");
          } else if (value === "clips") {
            router.push(profileUrl + "/clips");
          } else {
            router.push(profileUrl);
          }
        }}
        color="white"
        styles={{
          list: { borderBottomWidth: 3 },
          tabLabel: { fontWeight: 600, fontSize: 15 },
        }}
      >
        <Tabs.List>
          <Tabs.Tab
            value="videos"
            leftSection={<IconVideo stroke={1.5} />}
            style={{ color: activeTab === "videos" ? "white" : undefined }}
          >
            {tInsights("tabs.videos")}
          </Tabs.Tab>
          <Tabs.Tab
            value="clips"
            leftSection={<IconScissors stroke={1.5} />}
            style={{ color: activeTab === "clips" ? "white" : undefined }}
            rightSection={
              clipsCount != null ? (
                <Badge size="sm" variant="filled" circle>
                  {clipsCount}
                </Badge>
              ) : undefined
            }
          >
            {tInsights("tabs.clips")}
          </Tabs.Tab>
          <Tabs.Tab
            value="insights"
            leftSection={<IconChartBar stroke={1.5} />}
            style={{ color: activeTab === "insights" ? "white" : undefined }}
          >
            {tInsights("tabs.insights")}
          </Tabs.Tab>
          {activeTab === "videos" && (
            <div
              style={{
                marginInlineStart: "auto",
                display: "flex",
                alignItems: "center",
                marginBottom: 4,
              }}
            >
              <SegmentedControl
                value={filters.sort}
                onChange={(value) => setFilters({ sort: value as SortOptions })}
                data={[
                  { label: t("newest"), value: SortOptions.createdAtDesc },
                  { label: t("oldest"), value: SortOptions.createdAtAsc },
                ]}
              />
            </div>
          )}
        </Tabs.List>
      </Tabs>
    );
  }

  return !isInsights ? (
    <Flex justify="flex-end">
      <SegmentedControl
        value={filters.sort}
        onChange={(value) => setFilters({ sort: value as SortOptions })}
        data={[
          { label: t("newest"), value: SortOptions.createdAtDesc },
          { label: t("oldest"), value: SortOptions.createdAtAsc },
        ]}
      />
    </Flex>
  ) : null;
}
