"use client";

import { CountryFlag } from "@/app/[locale]/(protected)/components/country-flag";
import FollowButton from "@/app/[locale]/(protected)/components/follow-button";
import { FollowerTypeIcon } from "@/app/[locale]/(protected)/components/follower-type-icon";
import UnfollowButton from "@/app/[locale]/(protected)/components/unfollow-button";
import { FavoriteButton } from "@/app/[locale]/(protected)/my-list/components/favorite-button";
import OpenSocial from "@/app/components/open-social";
import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { Role } from "@/app/providers/ability-provider";
import { useUser } from "@/app/providers/user-provider";
import { Follower } from "@/lib/types/strapi-autogenerated";
import { Alert, Avatar, Box, Group, Stack, Text, Title } from "@mantine/core";
import { IconPlayerPause, IconShieldX } from "@tabler/icons-react";
import { FastAverageColor } from "fast-average-color";
import { useFormatter, useTranslations } from "next-intl";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import { AdminMenu } from "./admin-menu";
import classes from "./profile-header.module.css";
import { ProfileTabs } from "./profile-tabs";

interface ProfileHeaderProps {
  follower: Follower & { isFollowing: boolean };
  isRecording?: boolean;
  clipsCount?: number;
}

export function ProfileHeader({
  follower,
  isRecording = false,
  clipsCount,
}: ProfileHeaderProps) {
  const t = useTranslations("protected.profile");
  const format = useFormatter();
  const user = useUser();
  const isFavorite =
    user?.favorites?.some((f) => f.documentId === follower.documentId) ?? false;
  const avatarRef = useRef<HTMLImageElement>(null);
  const [bgColor, setBgColor] = useState<string | null>(null);

  useEffect(() => {
    if (!follower.avatar?.url) return;
    const img = new window.Image();
    img.crossOrigin = "anonymous";
    img.src = generateAvatarUrl(follower.avatar.url);
    img.onload = () => {
      const fac = new FastAverageColor();
      const result = fac.getColor(img, { algorithm: "dominant" });
      setBgColor(result.hex);
      fac.destroy();
    };
  }, [follower.avatar?.url]);

  return (
    <Stack mb="md" gap="md">
      <Box
        m="-md"
        style={{
          background: bgColor
            ? `linear-gradient(180deg, ${bgColor} 0%, ${bgColor}99 40%, transparent 100%)`
            : undefined,
          padding: "var(--mantine-spacing-md)",
          transition: "background 0.3s ease",
        }}
      >
        <Group
          justify="space-between"
          wrap="nowrap"
          align="flex-start"
          visibleFrom="sm"
        >
          <Group>
            <Box
              pos="relative"
              className={classes.avatarWrapper}
              data-favorite={isFavorite || undefined}
            >
              <Avatar
                size={120}
                style={{
                  ...(isRecording ? { border: "3px solid red" } : {}),
                }}
              >
                {follower.avatar?.url && (
                  <Image
                    src={generateAvatarUrl(follower.avatar?.url)}
                    alt={"Avatar"}
                    width={120}
                    height={120}
                    loading="lazy"
                  />
                )}
              </Avatar>
              {follower.type && (
                <FollowerTypeIcon
                  pos="absolute"
                  color="transparent"
                  type={follower.type}
                  top="50%"
                  left="50%"
                  size={90}
                  style={{ transform: "translate(-50%, -50%)" }}
                />
              )}
            </Box>
            <Stack gap={0}>
              <Title order={1} c="white" fz="2.5em">
                {follower.nickname || decodeURIComponent(follower.username)}
              </Title>
              <Group gap="xs">
                {follower.nickname && (
                  <Text size="sm" c="gray.6">
                    @{decodeURIComponent(follower.username)}
                  </Text>
                )}
                {follower.nickname && (
                  <Text size="sm" c="gray.6">
                    ·
                  </Text>
                )}
                <Text size="sm" c="gray.6" suppressHydrationWarning>
                  {t("addedAgo", {
                    time: format.relativeTime(
                      new Date(follower.createdAt!),
                      new Date(),
                    ),
                  })}
                </Text>
                {follower.lastCheckedAt && (
                  <>
                    <Text size="sm" c="gray.6">
                      ·
                    </Text>
                    <Text size="sm" c="gray.6" suppressHydrationWarning>
                      {t("lastCheckedAgo", {
                        time: format.relativeTime(
                          new Date(follower.lastCheckedAt),
                          new Date(),
                        ),
                      })}
                    </Text>
                  </>
                )}
                {follower.countryCode && (
                  <CountryFlag countryCode={follower.countryCode} size={30} />
                )}
              </Group>
            </Stack>
          </Group>
          <Group gap="xs">
            <OpenSocial follower={follower} showLabel />
            {follower.isFollowing && (
              <FavoriteButton
                documentId={follower.documentId!}
                isFavorite={isFavorite}
                showLabel
              />
            )}
            {follower.isFollowing ? (
              <UnfollowButton
                username={follower.username!}
                type={follower.type}
                showLabel
              />
            ) : (
              <FollowButton
                username={follower.username!}
                type={follower.type}
                showLabel
              />
            )}
            <AdminMenu follower={follower} showLabel />
          </Group>
        </Group>

        <Stack hiddenFrom="sm" gap="md">
          <Group>
            <Box
              pos="relative"
              className={classes.avatarWrapper}
              data-favorite={isFavorite || undefined}
            >
              <Avatar
                size={80}
                style={{
                  ...(isRecording ? { border: "3px solid red" } : {}),
                }}
              >
                {follower.avatar?.url && (
                  <Image
                    src={generateAvatarUrl(follower.avatar?.url)}
                    alt={"Avatar"}
                    width={80}
                    height={80}
                    loading="lazy"
                  />
                )}
              </Avatar>
              {follower.type && (
                <FollowerTypeIcon
                  pos="absolute"
                  color="transparent"
                  type={follower.type}
                  top="50%"
                  left="50%"
                  size={50}
                  style={{ transform: "translate(-50%, -50%)" }}
                />
              )}
            </Box>
            <Stack gap={0} style={{ flex: 1 }}>
              <Title order={1} c="white">
                {follower.nickname || decodeURIComponent(follower.username)}
              </Title>
              <Group gap="xs" wrap="wrap">
                {follower.nickname && (
                  <Text size="xs" c="gray.6">
                    @{decodeURIComponent(follower.username)}
                  </Text>
                )}
                {follower.nickname && (
                  <Text size="xs" c="gray.6">
                    ·
                  </Text>
                )}
                <Text size="xs" c="gray.6" suppressHydrationWarning>
                  {t("addedAgo", {
                    time: format.relativeTime(
                      new Date(follower.createdAt!),
                      new Date(),
                    ),
                  })}
                </Text>
                {follower.countryCode && (
                  <CountryFlag countryCode={follower.countryCode} size={20} />
                )}
              </Group>
            </Stack>
          </Group>
          <Group gap="xs">
            <OpenSocial follower={follower} showLabel />
            {follower.isFollowing && (
              <FavoriteButton
                documentId={follower.documentId!}
                isFavorite={isFavorite}
                showLabel
              />
            )}
            {follower.isFollowing ? (
              <UnfollowButton
                username={follower.username!}
                type={follower.type}
                showLabel
              />
            ) : (
              <FollowButton
                username={follower.username!}
                type={follower.type}
                showLabel
              />
            )}
            <AdminMenu follower={follower} showLabel />
          </Group>
        </Stack>
      </Box>
      {follower.blocked && (
        <Alert icon={<IconShieldX size={20} />} color="red" variant="light">
          {t("blocked")}
        </Alert>
      )}
      {follower.pause && !follower.isFollowing && !follower.blocked && (
        <Role is="authenticated" not>
          <Alert
            icon={<IconPlayerPause size={20} />}
            color="yellow"
            variant="light"
          >
            {t("paused")}
          </Alert>
        </Role>
      )}
      <ProfileTabs
        type={follower.type!}
        username={follower.username!}
        clipsCount={clipsCount}
      />
    </Stack>
  );
}
