import { CountryFlag } from "@/app/[locale]/(protected)/components/country-flag";
import FollowButton from "@/app/[locale]/(protected)/components/follow-button";
import { FollowerTypeIcon } from "@/app/[locale]/(protected)/components/follower-type-icon";
import UnfollowButton from "@/app/[locale]/(protected)/components/unfollow-button";
import OpenSocial from "@/app/components/open-social";
import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { safeRelativeTime } from "@/app/lib/safe-relative-time";
import { Follower } from "@/lib/types/strapi-autogenerated";
import { Avatar, Box, Group, Stack, Text, Title } from "@mantine/core";
import { getFormatter, getTranslations } from "next-intl/server";
import Image from "next/image";
import { AdminMenu } from "./admin-menu";
import { ProfileTabs } from "./profile-tabs";

interface ProfileHeaderProps {
  follower: Follower & { isFollowing: boolean };
  isRecording?: boolean;
}

export async function ProfileHeader({
  follower,
  isRecording = false,
}: ProfileHeaderProps) {
  const t = await getTranslations("protected.profile");
  const format = await getFormatter();

  return (
    <Stack mb="xl" gap="md">
    <Group>
      <Box pos="relative">
        <Avatar
          size={150}
          style={{
            ...(isRecording ? { border: "3px solid red" } : {}),
          }}
        >
          {follower.avatar?.url && (
            <Image
              src={generateAvatarUrl(follower.avatar?.url)}
              alt={"Avatar"}
              width={150}
              height={150}
            />
          )}
        </Avatar>

        {follower.type && (
          <FollowerTypeIcon
            pos="absolute"
            color="transparent"
            type={follower.type}
            top="50%"
            left="50%"
            size={90}
            style={{ transform: "translate(-50%, -50%)" }}
          />
        )}
      </Box>

      <Stack gap="xs">
        <Group>
          <Title order={2}>{decodeURIComponent(follower.username)}</Title>
          {follower.countryCode && (
            <CountryFlag countryCode={follower.countryCode} size={40} />
          )}
        </Group>

        <Group gap="xs">
          <OpenSocial follower={follower} />
          {follower.isFollowing ? (
            <UnfollowButton
              username={follower.username!}
              type={follower.type}
            />
          ) : (
            <FollowButton
              username={follower.username!}
              type={follower.type}
            />
          )}
          <AdminMenu follower={follower} />
        </Group>

        <div>
          <Text size="sm" c="dimmed" suppressHydrationWarning>
            {t("addedAgo", {
              time: safeRelativeTime(format, follower.createdAt),
            })}
          </Text>
          <Text size="sm" c="dimmed" suppressHydrationWarning>
            {t("lastCheckedAgo", {
              time: safeRelativeTime(format, follower.lastCheckedAt),
            })}
          </Text>
        </div>
      </Stack>
    </Group>
    <ProfileTabs type={follower.type!} username={follower.username!} />
    </Stack>
  );
}
