"use client";

import { CountryFlag } from "@/app/[locale]/(protected)/components/country-flag";
import FollowButton from "@/app/[locale]/(protected)/components/follow-button";
import { FollowerTypeIcon } from "@/app/[locale]/(protected)/components/follower-type-icon";
import UnfollowButton from "@/app/[locale]/(protected)/components/unfollow-button";
import OpenSocial from "@/app/components/open-social";
import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { Role } from "@/app/providers/ability-provider";
import { Follower } from "@/lib/types/strapi-autogenerated";
import { Alert, Avatar, Box, Group, Stack, Text, Title } from "@mantine/core";
import { IconPlayerPause, IconShieldX } from "@tabler/icons-react";
import { useFormatter, useTranslations } from "next-intl";
import Image from "next/image";
import { AdminMenu } from "./admin-menu";
import { ProfileTabs } from "./profile-tabs";

interface ProfileHeaderProps {
  follower: Follower & { isFollowing: boolean };
  isRecording?: boolean;
  clipsCount?: number;
}

export function ProfileHeader({
  follower,
  isRecording = false,
  clipsCount,
}: ProfileHeaderProps) {
  const t = useTranslations("protected.profile");
  const format = useFormatter();
  return (
    <Stack mb="xl" gap="md">
      <Group>
        <Box pos="relative">
          <Avatar
            size={150}
            style={{
              ...(isRecording ? { border: "3px solid red" } : {}),
            }}
          >
            {follower.avatar?.url && (
              <Image
                src={generateAvatarUrl(follower.avatar?.url)}
                alt={"Avatar"}
                width={150}
                height={150}
                loading="lazy"
              />
            )}
          </Avatar>

          {follower.type && (
            <FollowerTypeIcon
              pos="absolute"
              color="transparent"
              type={follower.type}
              top="50%"
              left="50%"
              size={90}
              style={{ transform: "translate(-50%, -50%)" }}
            />
          )}
        </Box>

        <Stack gap="xs">
          <Group>
            <Title order={2}>{decodeURIComponent(follower.username)}</Title>
            {follower.countryCode && (
              <CountryFlag countryCode={follower.countryCode} size={40} />
            )}
          </Group>

          <Group gap="xs">
            <OpenSocial follower={follower} />
            {follower.isFollowing ? (
              <UnfollowButton
                username={follower.username!}
                type={follower.type}
              />
            ) : (
              <FollowButton
                username={follower.username!}
                type={follower.type}
              />
            )}
            <AdminMenu follower={follower} />
          </Group>

          <div>
            <Text size="sm" c="dimmed" suppressHydrationWarning>
              {t("addedAgo", {
                time: format.relativeTime(
                  new Date(follower.createdAt!),
                  new Date(),
                ),
              })}
            </Text>
            {follower.lastCheckedAt && (
              <Text size="sm" c="dimmed" suppressHydrationWarning>
                {t("lastCheckedAgo", {
                  time: format.relativeTime(
                    new Date(follower.lastCheckedAt),
                    new Date(),
                  ),
                })}
              </Text>
            )}
          </div>
        </Stack>
      </Group>
      {follower.blocked && (
        <Alert icon={<IconShieldX size={20} />} color="red" variant="light">
          {t("blocked")}
        </Alert>
      )}
      {follower.pause && !follower.isFollowing && !follower.blocked && (
        <Role is="authenticated" not>
          <Alert
            icon={<IconPlayerPause size={20} />}
            color="yellow"
            variant="light"
          >
            {t("paused")}
          </Alert>
        </Role>
      )}
      <ProfileTabs type={follower.type!} username={follower.username!} clipsCount={clipsCount} />
    </Stack>
  );
}
