"use client";

import { getProfileUrl } from "@/app/components/open-social";
import { FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { SegmentedControl, Tabs } from "@mantine/core";
import { IconChartBar, IconVideo } from "@tabler/icons-react";
import { useTranslations } from "next-intl";
import { usePathname, useRouter } from "next/navigation";
import { useQueryStates } from "nuqs";
import { profileParsers, SortOptions } from "../lib/search-params";

interface ProfileTabsProps {
  type: string;
  username: string;
}

export function ProfileTabs({ type, username }: ProfileTabsProps) {
  const t = useTranslations("protected.common");
  const tInsights = useTranslations("protected.profileInsights");
  const router = useRouter();
  const pathname = usePathname();
  const [filters, setFilters] = useQueryStates(profileParsers);

  const isInsights = pathname.endsWith("/insights");
  const isTiktok = type === FollowerTypeEnum.Tiktok;

  if (isTiktok) {
    return (
      <Tabs
        value={isInsights ? "insights" : "videos"}
        onChange={(value) => {
          if (value === "insights") {
            router.push(getProfileUrl({ type, username }) + "/insights");
          } else {
            router.push(getProfileUrl({ type, username }));
          }
        }}
        color="white"
        styles={{
          list: { borderBottomWidth: 3 },
          tabLabel: { fontWeight: 600, fontSize: 15 },
        }}
      >
        <Tabs.List>
          <Tabs.Tab
            value="videos"
            leftSection={<IconVideo stroke={1.5} />}
            style={{ color: !isInsights ? "white" : undefined }}
          >
            {tInsights("tabs.videos")}
          </Tabs.Tab>
          <Tabs.Tab
            value="insights"
            leftSection={<IconChartBar stroke={1.5} />}
            style={{ color: isInsights ? "white" : undefined }}
          >
            {tInsights("tabs.insights")}
          </Tabs.Tab>
          {!isInsights && (
            <div
              style={{
                marginLeft: "auto",
                display: "flex",
                alignItems: "center",
                marginBottom: 4,
              }}
            >
              <SegmentedControl
                value={filters.sort}
                onChange={(value) => setFilters({ sort: value as SortOptions })}
                data={[
                  { label: t("newest"), value: SortOptions.createdAtDesc },
                  { label: t("oldest"), value: SortOptions.createdAtAsc },
                ]}
              />
            </div>
          )}
        </Tabs.List>
      </Tabs>
    );
  }

  return !isInsights ? (
    <SegmentedControl
      value={filters.sort}
      onChange={(value) => setFilters({ sort: value as SortOptions })}
      data={[
        { label: t("newest"), value: SortOptions.createdAtDesc },
        { label: t("oldest"), value: SortOptions.createdAtAsc },
      ]}
    />
  ) : null;
}
