import { FollowerTypeIcon } from "@/app/[locale]/(protected)/components/follower-type-icon";
import { getClipUrl } from "@/app/lib/clip-url";

import { Clip, FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { getLocale } from "next-intl/server";
import { headers } from "next/headers";
import { ClipPlayer } from "./clip-player";

interface Props {
  clip: Clip;
  type: FollowerTypeEnum;
}

export async function ImageClipPreview({ clip, type }: Props) {
  const headersList = await headers();
  const userAgent = headersList.get("user-agent") || "";
  const locale = await getLocale();

  return (
    <div
      style={{
        position: "relative",
        overflow: "hidden",
      }}
    >
      <ClipPlayer
        previewUrl={getClipUrl(clip.documentId!, "thumbnail.jpg", clip.path)}
        src={getClipUrl(clip.documentId!, "clip.mp4", clip.path)}
        subtitlesUrl={`/clip/${clip.documentId}/subtitles.vtt?locale=${locale}`}
        locale={locale}
        userAgent={userAgent}
      />

      <FollowerTypeIcon
        type={type}
        color="black"
        opacity={0.8}
        pos="absolute"
        top={20}
        right={18}
        style={{
          pointerEvents: "none",
        }}
      />
    </div>
  );
}
