import { FollowerTypeIcon } from "@/app/[locale]/(protected)/components/follower-type-icon";

import { formatDuration } from "@/app/[locale]/(protected)/components/video/player-utils";
import { getImageUrl } from "@/app/lib/media-url";
import { getProfileUrl } from "@/app/components/open-social";
import { FollowerTypeEnum, Recording } from "@/lib/types/strapi-autogenerated";
import { Anchor } from "@mantine/core";
import { getFormatter, getTranslations } from "next-intl/server";
import Image from "next/image";

interface Props {
  recording: Recording;
  type: FollowerTypeEnum;
}

export async function ImageVideoPreview({ recording, type }: Props) {
  const t = await getTranslations("profile");
  const format = await getFormatter();
  const sources = recording.sources;
  const totalDuration =
    sources?.reduce((sum, s) => sum + (s.duration || 0), 0) || 0;

  const firstDoneSource = sources?.find((s) => s.state === "done");
  const previewUrl = getImageUrl(recording.documentId!, "preview.jpg", firstDoneSource);

  return (
    <div
      style={{
        aspectRatio: "16/9",
        position: "relative",
        overflow: "hidden",
        borderRadius: "var(--mantine-radius-md)",
      }}
    >
      <Anchor
        href={
          getProfileUrl(recording.follower) + `/video/${recording.documentId}`
        }
        style={{
          position: "relative",
          display: "block",
          width: "100%",
          height: "100%",
        }}
      >
        <Image
          alt={t("jsonLd.streamTitle", {
            nickname:
              recording.follower?.nickname ||
              recording.follower?.username ||
              "",
            date: format.dateTime(new Date(recording.createdAt || ""), {
              year: "numeric",
              month: "short",
              day: "numeric",
              hour: "numeric",
              minute: "2-digit",
            }),
          })}
          sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw"
          src={previewUrl}
          fill
          loading="lazy"
        />
      </Anchor>
      <FollowerTypeIcon
        type={type}
        color="black"
        opacity={0.8}
        pos="absolute"
        top={10}
        right={8}
        style={{
          pointerEvents: "none",
        }}
      />
      {totalDuration > 0 && (
        <div
          style={{
            position: "absolute",
            bottom: 8,
            right: 8,
            backgroundColor: "rgba(0, 0, 0, 0.8)",
            color: "white",
            padding: "2px 6px",
            borderRadius: 4,
            fontSize: 12,
            fontWeight: 500,
            pointerEvents: "none",
          }}
        >
          {formatDuration(totalDuration)}
        </div>
      )}
    </div>
  );
}
