"use client";

import { Recording } from "@/lib/types/strapi-autogenerated";
import "hls-video-element";
import "media-chrome";
import { useSearchParams } from "next/navigation";
import { useEffect, useRef } from "react";
import {
  HlsVideo,
  MediaControlBar,
  MediaController,
  MediaLoadingIndicator,
  MediaMuteButton,
  MediaPlayButton,
  MediaPosterImage,
  MediaSeekForwardButton,
  MediaTimeDisplay,
  MediaTimeRange,
  MediaVolumeRange,
} from "./media-chrome";

export function VideoPlayer({ recording }: { recording: Recording }) {
  const searchParams = useSearchParams();
  const startTime = Number(searchParams.get("t")) || 0;

  const controllerRef = useRef<HTMLElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);

  // Handle seek and autoplay
  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;

    const safePlay = () => {
      const playPromise = video.play();
      if (playPromise !== undefined) {
        playPromise.catch(() => {
          // Autoplay was prevented - this is expected behavior in some browsers
          // User can manually click to play
        });
      }
    };

    const handleLoaded = () => {
      if (startTime > 0) {
        video.currentTime = startTime;
      } else {
        safePlay();
      }
    };

    const handleSeeked = () => {
      safePlay();
    };

    video.addEventListener("loadedmetadata", handleLoaded, { once: true });
    video.addEventListener("seeked", handleSeeked, { once: true });

    return () => {
      video.removeEventListener("loadedmetadata", handleLoaded);
      video.removeEventListener("seeked", handleSeeked);
    };
  }, [startTime]);

  const handleDoubleClick = () => {
    const controller = controllerRef.current;
    if (!controller) return;

    if (document.fullscreenElement) {
      document.exitFullscreen();
    } else {
      const el = controller as HTMLElement & {
        webkitRequestFullscreen?: () => Promise<void>;
      };
      if (el.requestFullscreen) {
        el.requestFullscreen();
      } else if (el.webkitRequestFullscreen) {
        el.webkitRequestFullscreen();
      }
    }
  };

  return (
    <>
      <MediaController
        ref={controllerRef}
        onDoubleClick={handleDoubleClick}
        style={{
          width: "100%",
          height: "100%",
          background: "#000",
        }}
      >
        <HlsVideo
          ref={videoRef}
          src={`/video/${recording.documentId}/playlist.m3u8`}
          slot="media"
          crossOrigin="anonymous"
          playsInline
          autoPlay
          muted
        >
          <track
            default
            kind="metadata"
            label="thumbnails"
            src={`/video/${recording.documentId}/thumbnails.vtt`}
          />
        </HlsVideo>

        <MediaPosterImage
          slot="poster"
          src={`/video/${recording.documentId}/screenshot.jpg`}
        />

        <MediaLoadingIndicator
          slot="centered-chrome"
          loadingdelay="0"
          style={{
            "--media-loading-indicator-transition-delay": "0ms",
          }}
        />

        <MediaControlBar>
          <MediaPlayButton />
          <MediaTimeRange />
          <MediaTimeDisplay showduration />
          <MediaSeekForwardButton seekoffset="10" />

          <div className="volume-hover-container">
            <MediaVolumeRange />
            <MediaMuteButton title="" />
          </div>
        </MediaControlBar>
      </MediaController>
    </>
  );
}
