"use client";

import { Recording } from "@/lib/types/strapi-autogenerated";
import type { HlsVideoElement } from "hls-video-element";
import "hls-video-element";
import "media-chrome";
import { useSearchParams } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import {
  HlsVideo,
  MediaControlBar,
  MediaController,
  MediaLoadingIndicator,
  MediaMuteButton,
  MediaPlayButton,
  MediaPosterImage,
  MediaSeekForwardButton,
  MediaTimeDisplay,
  MediaTimeRange,
  MediaVolumeRange,
} from "./media-chrome";

interface VideoPlayerProps {
  recording: Recording;
  defaultMuted?: boolean;
  onMuteChange?: (muted: boolean) => void;
  autoPlay?: boolean;
  onPlay?: () => void;
}

export function VideoPlayer({
  recording,
  defaultMuted = true,
  onMuteChange,
  autoPlay = false,
  onPlay,
}: VideoPlayerProps) {
  const searchParams = useSearchParams();
  const startTime = Number(searchParams.get("t")) || 0;

  const controllerRef = useRef<HTMLElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const [initialAutoPlay] = useState(autoPlay);


  // Destroy HLS on unmount (scroll away kills VideoPlayer via VideoSlide)
  useEffect(() => {
    const controller = controllerRef.current;
    return () => {
      if (!controller) return;
      const hlsEl = controller.querySelector("hls-video") as HlsVideoElement | null;
      if (!hlsEl) return;

      hlsEl.pause();
      if (hlsEl.api) {
        hlsEl.api.stopLoad();
        hlsEl.api.detachMedia();
        hlsEl.api.destroy();
        hlsEl.api = null;
      }
    };
  }, [recording.documentId]);

  // Handle seek to start time
  useEffect(() => {
    const video = videoRef.current;
    if (!video || !startTime) return;

    const handleLoaded = () => {
      video.currentTime = startTime;
    };

    video.addEventListener("loadedmetadata", handleLoaded, { once: true });

    return () => {
      video.removeEventListener("loadedmetadata", handleLoaded);
    };
  }, [startTime]);

  // Notify parent on first play (unlocks autoplay for subsequent videos)
  useEffect(() => {
    const video = videoRef.current;
    if (!video || !onPlay) return;

    const handlePlay = () => onPlay();
    video.addEventListener("play", handlePlay, { once: true });
    return () => video.removeEventListener("play", handlePlay);
  }, [onPlay]);

  // Track mute changes
  useEffect(() => {
    const video = videoRef.current;
    if (!video || !onMuteChange) return;

    const handleVolumeChange = () => {
      onMuteChange(video.muted);
    };

    video.addEventListener("volumechange", handleVolumeChange);
    return () => video.removeEventListener("volumechange", handleVolumeChange);
  }, [onMuteChange]);

  const handleDoubleClick = () => {
    const controller = controllerRef.current;
    if (!controller) return;

    if (document.fullscreenElement) {
      document.exitFullscreen();
    } else {
      const el = controller as HTMLElement & {
        webkitRequestFullscreen?: () => Promise<void>;
      };
      if (el.requestFullscreen) {
        el.requestFullscreen();
      } else if (el.webkitRequestFullscreen) {
        el.webkitRequestFullscreen();
      }
    }
  };

  return (
    <>
      <style>{`
        media-controller:not([mediapaused]) media-play-button[slot="centered-chrome"] {
          display: none !important;
        }
        media-controller[mediapaused] media-loading-indicator[slot="centered-chrome"] {
          display: none !important;
        }
      `}</style>
      <MediaController
        ref={controllerRef}
        onDoubleClick={handleDoubleClick}
        style={{
          width: "100%",
          height: "100%",
          background: "#000",
        }}
      >
        <HlsVideo
          ref={videoRef}
          src={`/video/${recording.documentId}/playlist.m3u8`}
          slot="media"
          crossOrigin="anonymous"
          playsInline
          autoPlay={initialAutoPlay || undefined}
          preload={initialAutoPlay ? undefined : "none"}
          muted={defaultMuted}
        >
          {typeof window !== "undefined" &&
            window.matchMedia("(pointer: fine)").matches && (
              <track
                default
                kind="metadata"
                label="thumbnails"
                src={`/video/${recording.documentId}/thumbnails.vtt`}
              />
            )}
        </HlsVideo>

        <MediaPosterImage
          slot="poster"
          src={`/video/${recording.documentId}/screenshot.jpg`}
        />

        <MediaPlayButton
          slot="centered-chrome"
          noautohide
          style={{
            "--media-button-icon-height": "64px",
            "--media-button-icon-width": "64px",
          }}
        />

        <MediaLoadingIndicator
          slot="centered-chrome"
          noautohide
          loadingdelay="0"
          style={{
            "--media-loading-indicator-transition-delay": "0ms",
          }}
        />

        <MediaControlBar>
          <MediaPlayButton />
          <MediaTimeRange />
          <MediaTimeDisplay showduration />
          <MediaSeekForwardButton seekoffset="10" />

          <div className="volume-hover-container">
            <MediaVolumeRange />
            <MediaMuteButton title="" />
          </div>
        </MediaControlBar>
      </MediaController>
    </>
  );
}
