"use client";

import { getImageUrl } from "@/app/lib/media-url";
import { Recording } from "@/lib/types/strapi-autogenerated";
import "hls-video-element";
import type { HlsVideoElement } from "hls-video-element";
import "media-chrome";
import "@player.style/yt";
import { useSearchParams } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { HlsVideo, MediaLoadingIndicator, MediaPosterImage } from "./media-chrome";

interface VideoPlayerProps {
  recording: Recording;
  defaultMuted?: boolean;
  onMuteChange?: (muted: boolean) => void;
  autoPlay?: boolean;
  onPlay?: () => void;
}

export function VideoPlayer({
  recording,
  defaultMuted = true,
  onMuteChange,
  autoPlay = false,
  onPlay,
}: VideoPlayerProps) {
  const searchParams = useSearchParams();
  const startTime = Number(searchParams.get("t")) || 0;

  const controllerRef = useRef<HTMLElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const [initialAutoPlay] = useState(autoPlay);

  // Destroy HLS on unmount (scroll away kills VideoPlayer via VideoSlide)
  useEffect(() => {
    const controller = controllerRef.current;
    return () => {
      if (!controller) return;
      const hlsEl = controller.querySelector(
        "hls-video",
      ) as HlsVideoElement | null;
      if (!hlsEl) return;

      hlsEl.pause();
      if (hlsEl.api) {
        hlsEl.api.stopLoad();
        hlsEl.api.detachMedia();
        hlsEl.api.destroy();
        hlsEl.api = null;
      }
    };
  }, [recording.documentId]);

  // Handle seek to start time
  useEffect(() => {
    const video = videoRef.current;
    if (!video || !startTime) return;

    const handleLoaded = () => {
      video.currentTime = startTime;
    };

    video.addEventListener("loadedmetadata", handleLoaded, { once: true });

    return () => {
      video.removeEventListener("loadedmetadata", handleLoaded);
    };
  }, [startTime]);

  // Notify parent on first play (unlocks autoplay for subsequent videos)
  useEffect(() => {
    const video = videoRef.current;
    if (!video || !onPlay) return;

    const handlePlay = () => onPlay();
    video.addEventListener("play", handlePlay, { once: true });
    return () => video.removeEventListener("play", handlePlay);
  }, [onPlay]);

  // Change seek offset to 10s and focus player on play
  useEffect(() => {
    const theme = controllerRef.current;
    if (!theme) return;

    const inject = () => {
      const shadow = theme.shadowRoot;
      if (!shadow) return;

      // Focus media-controller on play so arrow keys work
      const mc = shadow.querySelector("media-controller") as HTMLElement;
      const video = videoRef.current;
      if (mc && video) {
        const handlePlay = () => mc.focus();
        video.addEventListener("playing", handlePlay);
      }

      // Change seek offset from 30s to 10s
      shadow.querySelectorAll("media-seek-backward-button, media-seek-forward-button").forEach((btn) => {
        btn.setAttribute("seekoffset", "10");
      });
    };

    inject();
    const timer = setTimeout(inject, 500);
    return () => clearTimeout(timer);
  }, [recording.documentId]);

  // Track mute changes
  useEffect(() => {
    const video = videoRef.current;
    if (!video || !onMuteChange) return;

    const handleVolumeChange = () => {
      onMuteChange(video.muted);
    };

    video.addEventListener("volumechange", handleVolumeChange);
    return () => video.removeEventListener("volumechange", handleVolumeChange);
  }, [onMuteChange]);

  const handleDoubleClick = () => {
    const controller = controllerRef.current;
    if (!controller) return;

    if (document.fullscreenElement) {
      document.exitFullscreen();
    } else {
      const el = controller as HTMLElement & {
        webkitRequestFullscreen?: () => Promise<void>;
      };
      if (el.requestFullscreen) {
        el.requestFullscreen();
      } else if (el.webkitRequestFullscreen) {
        el.webkitRequestFullscreen();
      }
    }
  };

  return (
    <>
      {/* @ts-expect-error - web component */}
      <media-theme-yt
        ref={controllerRef}
        onDoubleClick={handleDoubleClick}
        style={{
          width: "100%",
          height: "100%",
        }}
      >
        <HlsVideo
          ref={videoRef}
          src={`/video/${recording.documentId}/playlist.m3u8`}
          slot="media"
          crossOrigin="anonymous"
          playsInline
          autoPlay={initialAutoPlay || undefined}
          preload={initialAutoPlay ? undefined : "none"}
          muted={defaultMuted}
        >
          {typeof window !== "undefined" &&
            window.matchMedia("(pointer: fine)").matches && (
              <track
                default
                kind="metadata"
                label="thumbnails"
                src={`/video/${recording.documentId}/thumbnails.vtt`}
              />
            )}
          <track
            default
            kind="chapters"
            src={`/video/${recording.documentId}/chapters.vtt`}
          />
        </HlsVideo>

        <MediaPosterImage
          slot="poster"
          src={getImageUrl(recording.documentId!, "screenshot.jpg", recording.sources?.at(-1))}
        />

        <MediaLoadingIndicator
          slot="centered-chrome"
          noautohide
          loadingdelay="0"
          style={{
            "--media-loading-indicator-transition-delay": "0ms",
          }}
        />

      {/* @ts-expect-error - web component */}
      </media-theme-yt>
    </>
  );
}
