// lib/search-params.ts
import { getDateRange } from "@/app/lib/get-date-range";
import { ScopeEnum } from "@/lib/types/strapi-autogenerated";
import { deepMerge } from "@mantine/core";
import {
  createSearchParamsCache,
  inferParserType,
  parseAsBoolean,
  parseAsString,
  parseAsStringEnum,
} from "nuqs/server";

export const followingDefaultOptions = {
  scope: ScopeEnum.Following,
  filters: {
    sources: {
      state: {
        $eq: ["done"],
      },
    },
  },
  populate: {
    sources: {
      fields: ["*"],
      filters: {
        state: {
          $eq: "done",
        },
      },
    },
    follower: {
      fields: ["username", "type"],
      populate: {
        avatar: {
          fields: ["url"],
        },
      },
    },
  },
};

export enum FollowingSortOptions {
  updatedAtDesc = "updatedAt:desc",
  updatedAtAsc = "updatedAt:asc",
}

export const followingParsers = {
  sort: parseAsStringEnum<FollowingSortOptions>(
    Object.values(FollowingSortOptions),
  ).withDefault(FollowingSortOptions.updatedAtDesc),
  scope: parseAsStringEnum<ScopeEnum>(Object.values(ScopeEnum)).withDefault(
    ScopeEnum.Following,
  ),
  gender: parseAsString,
  country: parseAsString,
  language: parseAsString,
  type: parseAsString,
  search: parseAsString,
  dateRange: parseAsString,
  favorites: parseAsBoolean.withDefault(false),
};

export const followingParamsCache = createSearchParamsCache(followingParsers);

export type FollowingFilters = inferParserType<typeof followingParsers>;

export const buildFollowingFilters = (filters: FollowingFilters) =>
  [
    filters.gender ? { follower: { gender: { $eq: filters.gender } } } : {},
    filters.country
      ? { follower: { countryCode: { $eq: filters.country } } }
      : {},
    filters.language
      ? { follower: { languageCode: { $eq: filters.language } } }
      : {},
    filters.type ? { follower: { type: { $eq: filters.type } } } : {},
    filters.search
      ? {
          follower: {
            username: {
              $containsi: decodeURIComponent(filters.search).replace(/^@/, ""),
            },
          },
        }
      : {},
    filters.dateRange ? getDateRange(filters.dateRange, "updatedAt") : {},
  ].reduce((acc, curr) => deepMerge(acc, curr), {});
