"use client";

import { useWatchLater } from "@/app/hooks/use-watch-later";
import { safeRelativeTime } from "@/app/lib/safe-relative-time";
import { Recording, SourceStateEnum } from "@/lib/types/strapi-autogenerated";
import { Button, Group, Loader, SimpleGrid, Stack, Text } from "@mantine/core";
import { keepPreviousData, useQuery } from "@tanstack/react-query";
import { useFormatter, useNow, useTranslations } from "next-intl";
import { useState } from "react";
import { ImageSpritePreview } from "../../components/image-sprite-preview";
import { RecordingMenu } from "../../components/recording-menu";
import { getRecordingsByIds } from "../actions";

const PAGE_SIZE = 12;

interface Props {
  initialIds: string[];
}

export default function WatchLaterList({ initialIds }: Props) {
  const t = useTranslations("protected.watchLater");
  const tCommon = useTranslations("protected.common.recordings");
  const format = useFormatter();
  const now = useNow({ updateInterval: 1000 * 30 });
  const { watchLater: clientWatchLater, isInitialized } = useWatchLater();
  const [visibleCount, setVisibleCount] = useState(PAGE_SIZE);

  // Use client state once initialized, otherwise use server-provided initial IDs
  const watchLater = isInitialized ? clientWatchLater : initialIds;

  // Only fetch the IDs we need to display
  const idsToFetch = watchLater.slice(0, visibleCount);

  const { data: recordings, isLoading } = useQuery({
    queryKey: ["watch-later", idsToFetch],
    queryFn: () => getRecordingsByIds(idsToFetch),
    enabled: idsToFetch.length > 0,
    placeholderData: keepPreviousData,
  });

  // Only show loading on initial load, not when removing items
  if (isLoading && !recordings && watchLater.length > 0) {
    return (
      <Stack align="center" py="xl">
        <Loader size="lg" />
      </Stack>
    );
  }

  if (!watchLater.length) {
    return (
      <Stack align="center" py="xl">
        <Text c="dimmed">{t("empty")}</Text>
      </Stack>
    );
  }

  // Sort recordings to match watchLater order
  const sortedRecordings = idsToFetch
    .map((id) => recordings?.find((r: Recording) => r.documentId === id))
    .filter(Boolean) as Recording[];

  const hasMore = visibleCount < watchLater.length;

  const loadMore = () => {
    setVisibleCount((prev) => prev + PAGE_SIZE);
  };

  return (
    <Stack gap="lg">
      <SimpleGrid cols={{ base: 1, sm: 2, md: 3, xl: 4 }} spacing="lg">
        {sortedRecordings.map((rec) => {
          const isRecording = rec.sources?.some(
            (s) =>
              s.state === SourceStateEnum.Recording ||
              s.state === SourceStateEnum.Uploading,
          );

          return (
            <Stack key={rec.documentId} gap={4}>
              {rec.follower?.username && rec.follower?.type ? (
                <ImageSpritePreview
                  recording={rec}
                  username={rec.follower?.username}
                  type={rec.follower?.type}
                />
              ) : null}

              <Group justify="space-between" align="center">
                <Text size="xs" suppressHydrationWarning>
                  {isRecording
                    ? tCommon("liveAgo", {
                        time: safeRelativeTime(format, rec.createdAt, {
                          style: "narrow",
                          now,
                        }),
                      })
                    : format.dateTime(new Date(rec.createdAt || ""), {
                        dateStyle: "medium",
                        timeStyle: "short",
                      })}
                </Text>
                <RecordingMenu
                  recording={rec}
                  username={rec.follower?.username}
                  type={rec.follower?.type}
                />
              </Group>
            </Stack>
          );
        })}
      </SimpleGrid>

      {hasMore && (
        <Button variant="light" onClick={loadMore} fullWidth>
          {t("loadMore")}
        </Button>
      )}
    </Stack>
  );
}
