import publicApi from "@/lib/public-api";
import { FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { unstable_cache } from "next/cache";

const REVALIDATE = 3600;

export const getFollowerFilters = unstable_cache(
  async (type?: FollowerTypeEnum) => {
    const { data: filtersData } = await publicApi.follower.getFollowerFilters(
      type ? { type } : { type: undefined },
    );
    return {
      genders: (filtersData.genders ?? [])
        .filter((g) => g.value)
        .map((g) => ({
          value: g.value || "",
          label: `${g.value} (${g.count})`,
        })),
      countryCodes: (filtersData.countryCodes ?? [])
        .filter((c) => c.value !== "-")
        .map((c) => ({
          value: c.value || "",
          label: `${c.value} (${c.count})`,
        })),
      types: (filtersData.types ?? []).map((l) => ({
        value: l.value || "",
        label: `${l.value} (${l.count})`,
      })),
      languageCodes: (filtersData.languageCodes ?? []).map((l) => ({
        value: l.value || "",
        label: `${l.value} (${l.count})`,
      })),
    };
  },
  ["recording-follower-filters"],
  { revalidate: REVALIDATE },
);

export const getRecordings = unstable_cache(
  async (type: string, page: number) => {
    const {
      data: { data: recordings, meta },
    } = await publicApi.recording.getRecordings({
      filters: {
        ...(type === "all"
          ? {}
          : {
              follower: {
                type,
              },
            }),
        sources: {
          state: {
            $eq: ["done"],
          },
        },
      },
      "pagination[pageSize]": 20,
      "pagination[page]": page,
      sort: "createdAt:desc",
      populate: {
        sources: {
          fields: ["*"],
          filters: {
            state: {
              $eq: "done",
            },
          },
        },
        follower: {
          fields: ["*"],
        },
      },
    });
    return { recordings: recordings ?? [], meta };
  },
  ["recordings"],
  { revalidate: REVALIDATE },
);

export const getRecordingsByCountry = unstable_cache(
  async (type: string, countryCode: string, page: number) => {
    const {
      data: { data: recordings, meta },
    } = await publicApi.recording.getRecordings({
      filters: {
        ...(type === "all"
          ? {
              follower: {
                countryCode,
              },
            }
          : {
              follower: {
                type,
                countryCode,
              },
            }),
        sources: {
          state: {
            $eq: ["done"],
          },
        },
      },
      "pagination[pageSize]": 20,
      "pagination[page]": page,
      sort: "createdAt:desc",
      populate: {
        sources: {
          fields: ["*"],
          filters: {
            state: {
              $eq: "done",
            },
          },
        },
        follower: {
          fields: ["*"],
        },
      },
    });
    return { recordings: recordings ?? [], meta };
  },
  ["recordings-by-country"],
  { revalidate: REVALIDATE },
);
