"use client";

import { trackEvent } from "@/app/lib/analytics";
import { useRole } from "@/app/providers/ability-provider";
import { useUser } from "@/app/providers/user-provider";
import { GetUsersPermissionsUsersRolesData } from "@/lib/types/strapi-autogenerated";
import {
  Alert,
  Anchor,
  Badge,
  Button,
  Card,
  Divider,
  Flex,
  Grid,
  GridCol,
  Group,
  Modal,
  Paper,
  Radio,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import { useDisclosure } from "@mantine/hooks";
import {
  IconBell,
  IconBrandAmazon,
  IconBrandApple,
  IconBrandGoogle,
  IconBrandMastercard,
  IconBrandPaypal,
  IconBrandVisa,
  IconChartBar,
  IconCheck,
  IconCrown,
  IconDownload,
  IconHeadset,
  IconLanguage,
  IconMovie,
  IconScissors,
  IconShare,
  IconSparkles,
  IconUsers,
  IconVideo,
} from "@tabler/icons-react";
import { useTranslations } from "next-intl";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { cancelSubscription } from "./actions";
import { FreemiusPaymentButton } from "./components/freemius-payment-button";
import { StripePaymentButton } from "./components/stripe-payment-button";

// Extend user type with subscription fields from schema
type UserWithSubscription = GetUsersPermissionsUsersRolesData & {
  subscriptionStatus?: "active" | "cancelled" | "expired";
  subscriptionEndDate?: string;
  billingPeriod?: string;
};

export default function PremiumClient() {
  const t = useTranslations("protected.premium");
  const [selectedBilling, setSelectedBilling] = useState("12months");
  const [selectedPayment, setSelectedPayment] = useState<string | null>(
    "stripe",
  );

  const handlePaymentChange = (value: string | null) => {
    setSelectedPayment(value);
  };

  const user = useUser() as UserWithSubscription | null;
  const role = useRole();
  const router = useRouter();
  const [
    cancelModalOpened,
    { open: openCancelModal, close: closeCancelModal },
  ] = useDisclosure(false);
  const [cancelling, setCancelling] = useState(false);

  const BILLING_OPTIONS = [
    {
      id: "1month",
      label: t("billing1MonthLabel"),
      price: 15,
      perMonth: 15,
      savings: null,
      badge: null,
      billingCycle: "monthly" as const,
      stripeOnly: false,
    },
    {
      id: "3months",
      label: t("billing3MonthsLabel"),
      price: 30,
      perMonth: 10,
      savings: t("billing3MonthsSavings"),
      badge: null,
      billingCycle: "quarterly" as const,
      stripeOnly: true,
    },
    {
      id: "12months",
      label: t("billing12MonthsLabel"),
      price: 96,
      perMonth: 8,
      savings: t("billing12MonthsSavings"),
      badge: t("billing12MonthsBadge"),
      billingCycle: "annual" as const,
      stripeOnly: false,
    },
    /*{
      id: "lifetime",
      label: t("billingLifetimeLabel"),
      price: 199,
      perMonth: null,
      savings: t("billingLifetimeSavings"),
      badge: t("billingLifetimeBadge"),
      billingCycle: "lifetime" as const,
      stripeOnly: false,
    },*/
  ];

  const filteredBillingOptions =
    selectedPayment === "stripe"
      ? BILLING_OPTIONS
      : BILLING_OPTIONS.filter((o) => !o.stripeOnly);

  const PREMIUM_FEATURES = [
    { icon: IconUsers, label: t("premiumRecord100"), color: "#a78bfa" },
    { icon: IconDownload, label: t("premiumFullControl"), color: "#60a5fa" },
    { icon: IconBell, label: t("premiumNotifications"), color: "#fbbf24" },
    { icon: IconMovie, label: t("premiumAiHighlights"), color: "#34d399" },
    { icon: IconLanguage, label: t("premiumAiSubtitles"), color: "#f472b6" },
    { icon: IconSparkles, label: t("premiumAiMemes"), color: "#fb923c" },
    { icon: IconShare, label: t("premiumPublishSocial"), color: "#38bdf8" },
    { icon: IconScissors, label: t("premiumClipEditor"), color: "#ef4444" },
    { icon: IconVideo, label: t("premiumWatchLater"), color: "#c084fc" },

    { icon: IconChartBar, label: t("premiumTiktokInsights"), color: "#22d3ee" },
    {
      icon: IconDownload,
      label: t("premiumDownloadRecordings"),
      color: "#4ade80",
    },
    { icon: IconHeadset, label: t("premiumPrioritySupport"), color: "#a78bfa" },
  ];

  const selectedPlan = filteredBillingOptions.find(
    (o) => o.id === selectedBilling,
  );

  // Translate billing period
  const getTranslatedBillingPeriod = (period?: string) => {
    switch (period) {
      case "monthly":
        return t("billingPeriodMonthly");
      case "quarterly":
        return t("billingPeriodQuarterly");
      case "annual":
        return t("billingPeriodAnnual");
      case "lifetime":
        return t("billingPeriodLifetime");
      default:
        return period || "";
    }
  };

  // Determine if user is premium (admin, champion, or has active/cancelled subscription)
  const isPremiumRole = role?.type === "admin" || role?.type === "champion";
  const hasActiveSubscription =
    user?.subscriptionStatus === "active" ||
    user?.subscriptionStatus === "cancelled";
  const isPremium = isPremiumRole || hasActiveSubscription;
  const canCancel =
    user?.subscriptionStatus === "active" &&
    !isPremiumRole &&
    user?.billingPeriod !== "lifetime";

  const handlePlanSelect = (planId: string) => {
    const plan = BILLING_OPTIONS.find((o) => o.id === planId);
    if (plan && planId !== selectedBilling) {
      trackEvent("premium_plan_selected", {
        plan: plan.label,
        billing_cycle: plan.billingCycle,
        price: plan.price,
      });
    }
    setSelectedBilling(planId);
    // 3 months is only available via Stripe, so auto-switch payment method
    if (plan?.stripeOnly && selectedPayment !== "stripe") {
      setSelectedPayment("stripe");
    }
  };

  const handleCancelSubscription = async () => {
    setCancelling(true);
    const result = await cancelSubscription();
    setCancelling(false);

    if (result.success) {
      closeCancelModal();
      router.refresh();
    } else {
      console.error("Failed to cancel:", result.error);
    }
  };

  return (
    <Stack w="100%">
      {/* Header */}
      <Stack gap={4}>
        <Group gap="xs">
          <IconCrown size={28} color="#fbbf24" />
          <Title order={2}>{t("title")}</Title>
        </Group>
        <Text size="sm" c="dimmed">
          {isPremium ? t("descriptionPremium") : t("descriptionNonPremium")}
        </Text>
      </Stack>

      <Divider mx={{ base: "-xs", sm: "-md" }} />

      <Grid gutter="md" overflow="hidden">
        {/* Left Column - Plan & Features */}
        <GridCol span={{ base: 12, md: isPremium ? 12 : 7 }}>
          <Stack gap="lg">
            {/* Current Plan (premium users) */}
            {isPremium && (
              <Card
                padding="lg"
                radius="md"
                withBorder
                style={{
                  background:
                    "linear-gradient(135deg, rgba(139, 92, 246, 0.15) 0%, rgba(124, 58, 237, 0.08) 100%)",
                  borderColor: "rgba(139, 92, 246, 0.35)",
                }}
              >
                <Stack gap="md">
                  <Group gap="xs">
                    <IconCrown size={20} color="#fbbf24" />
                    <Text fw={600} size="lg">
                      {isPremiumRole ? role?.name : t("title")}
                    </Text>
                    {user?.subscriptionStatus === "cancelled" && (
                      <Badge size="sm" variant="light" color="orange">
                        {t("cancelled")}
                      </Badge>
                    )}
                  </Group>

                  <Alert color="violet" variant="light">
                    <Text size="sm">
                      {isPremiumRole
                        ? t("adminAccess")
                        : user?.subscriptionStatus === "cancelled"
                          ? t("cancelledMessage", {
                              billingPeriod: getTranslatedBillingPeriod(
                                user?.billingPeriod,
                              ),
                              endDate: new Date(
                                user.subscriptionEndDate!,
                              ).toLocaleDateString(),
                            })
                          : user?.billingPeriod === "lifetime"
                            ? t("lifetimeMessage")
                            : t("activeMessage", {
                                billingPeriod: getTranslatedBillingPeriod(
                                  user?.billingPeriod,
                                ),
                                renewDate: new Date(
                                  user?.subscriptionEndDate || "",
                                ).toLocaleDateString(),
                              })}
                    </Text>
                  </Alert>

                  {canCancel && (
                    <Button
                      variant="subtle"
                      color="gray"
                      size="xs"
                      onClick={openCancelModal}
                    >
                      {t("cancelSubscription")}
                    </Button>
                  )}
                </Stack>
              </Card>
            )}

            {/* Choose Plan (non-premium users) */}
            {!isPremium && (
              <Stack gap="sm">
                {/* Free tier - current plan */}
                <Paper
                  p="md"
                  radius="md"
                  withBorder
                  style={{
                    borderColor: "rgba(100, 116, 139, 0.4)",
                    background: "rgba(100, 116, 139, 0.06)",
                  }}
                >
                  <Group justify="space-between" wrap="nowrap">
                    <Group gap="md" wrap="nowrap" ml="xl">
                      <Text fw={500}>{t("currentPlan")}</Text>
                    </Group>
                    <Text fw={700} size="lg" c="dimmed">
                      {t("free")}
                    </Text>
                  </Group>
                </Paper>

                <Radio.Group
                  value={selectedBilling}
                  onChange={handlePlanSelect}
                >
                  <Stack gap="sm">
                    {filteredBillingOptions.map((option) => (
                      <Paper
                        key={option.id}
                        p="md"
                        radius="md"
                        withBorder
                        style={{
                          cursor: "pointer",
                          borderColor:
                            selectedBilling === option.id
                              ? "var(--mantine-color-violet-6)"
                              : undefined,
                          background:
                            selectedBilling === option.id
                              ? "rgba(139, 92, 246, 0.08)"
                              : undefined,
                        }}
                        onClick={() => handlePlanSelect(option.id)}
                      >
                        <Group justify="space-between" wrap="nowrap">
                          <Group gap="md" wrap="nowrap">
                            <Radio value={option.id} />
                            <div>
                              <Group gap="xs">
                                <Text fw={500}>{option.label}</Text>
                                {option.badge && (
                                  <Badge
                                    size="xs"
                                    variant="filled"
                                    color="violet"
                                  >
                                    {option.badge}
                                  </Badge>
                                )}
                              </Group>
                              {option.savings && (
                                <Text size="xs" c="green">
                                  {option.savings}
                                </Text>
                              )}
                            </div>
                          </Group>
                          <div style={{ textAlign: "right" }}>
                            {option.perMonth ? (
                              <>
                                <Text fw={700} size="lg">
                                  ${option.perMonth}/month
                                </Text>
                                <Text size="xs" c="dimmed">
                                  ${option.price} total
                                </Text>
                              </>
                            ) : (
                              <>
                                <Text fw={700} size="lg">
                                  ${option.price}
                                </Text>
                                <Text size="xs" c="dimmed">
                                  {t("oneTime")}
                                </Text>
                              </>
                            )}
                          </div>
                        </Group>
                      </Paper>
                    ))}
                  </Stack>
                </Radio.Group>
              </Stack>
            )}

            {/* Premium Features */}
            <Card
              padding="lg"
              radius="md"
              withBorder
              style={{
                background:
                  "linear-gradient(135deg, rgba(139, 92, 246, 0.15) 0%, rgba(124, 58, 237, 0.08) 100%)",
                borderColor: "rgba(139, 92, 246, 0.35)",
              }}
            >
              <Stack gap="md">
                <Group gap="xs">
                  <IconSparkles size={20} color="#a78bfa" />
                  <Text fw={600} size="lg">
                    {isPremium
                      ? t("yourPremiumFeatures")
                      : t("unlockPremiumFeatures")}
                  </Text>
                </Group>

                <Grid gutter="sm">
                  {PREMIUM_FEATURES.map((feature) => (
                    <GridCol span={6} key={feature.label}>
                      <Group gap="xs" wrap="nowrap">
                        <feature.icon size={18} color={feature.color} />
                        <Text size="sm">{feature.label}</Text>
                      </Group>
                    </GridCol>
                  ))}
                </Grid>

                <Text size="xs" c="dimmed">
                  {t("futureFeatures")}{" "}
                  <Anchor href="/changelog" size="xs">
                    {t("seeWhatsNew")}
                  </Anchor>
                </Text>

                <Text size="xs" c="dimmed">
                  {t("supportMessage")}
                </Text>
              </Stack>
            </Card>
          </Stack>
        </GridCol>

        {/* Right Column - Payment (only for non-premium users) */}
        {!isPremium && (
          <GridCol span={{ base: 12, md: 5 }}>
            <Card
              padding="lg"
              radius="md"
              withBorder
              style={{
                background:
                  "linear-gradient(135deg, rgba(34, 197, 94, 0.1) 0%, rgba(22, 163, 74, 0.05) 100%)",
                borderColor: "rgba(34, 197, 94, 0.3)",
              }}
            >
              <Stack gap="lg">
                <Group gap="xs">
                  <IconCrown size={20} color="#fbbf24" />
                  <Text fw={600} size="lg">
                    {t("paymentMethod")}
                  </Text>
                </Group>

                <Radio.Group
                  value={selectedPayment}
                  onChange={handlePaymentChange}
                >
                  <Stack gap="sm">
                    {/* Stripe Option */}
                    <Paper
                      p="md"
                      radius="md"
                      withBorder
                      style={{
                        cursor: "pointer",
                        borderColor:
                          selectedPayment === "stripe"
                            ? "var(--mantine-color-green-6)"
                            : "rgba(255,255,255,0.1)",
                        background:
                          selectedPayment === "stripe"
                            ? "rgba(34, 197, 94, 0.1)"
                            : "rgba(0,0,0,0.2)",
                      }}
                      onClick={() => handlePaymentChange("stripe")}
                    >
                      <Stack gap="sm">
                        <Group justify="space-between" wrap="nowrap">
                          <Group gap="md" wrap="nowrap">
                            <Radio value="stripe" color="green" />
                            <div>
                              <Text fw={500}>Stripe</Text>
                              <Text size="xs" c="dimmed">
                                {t("stripeDescription")}
                              </Text>
                            </div>
                          </Group>
                        </Group>

                        <Group gap="xs" mt="xs" wrap="wrap">
                          <Card
                            withBorder
                            radius="sm"
                            bg="transparent"
                            c="green"
                            py={2}
                            px="xs"
                          >
                            <IconBrandVisa stroke={1.5} />
                          </Card>
                          <Card
                            withBorder
                            radius="sm"
                            bg="transparent"
                            c="green"
                            py={2}
                            px="xs"
                          >
                            <IconBrandMastercard stroke={1.5} />
                          </Card>
                          <Card
                            withBorder
                            radius="sm"
                            bg="transparent"
                            c="green"
                            py={2}
                            px="xs"
                          >
                            <IconBrandApple stroke={1.5} />
                          </Card>
                          <Card
                            withBorder
                            radius="sm"
                            bg="transparent"
                            c="green"
                            py={2}
                            px="xs"
                          >
                            <IconBrandGoogle stroke={1.5} />
                          </Card>
                          <Card
                            withBorder
                            radius="sm"
                            bg="transparent"
                            c="green"
                            py={2}
                            px="xs"
                          >
                            <IconBrandAmazon stroke={1.5} />
                          </Card>
                        </Group>
                      </Stack>
                    </Paper>

                    {/* Freemius Option - hidden when 3 months (Stripe-only) is selected */}
                    {selectedBilling !== "3months" && (
                      <Paper
                        p="md"
                        radius="md"
                        withBorder
                        style={{
                          cursor: "pointer",
                          borderColor:
                            selectedPayment === "freemius"
                              ? "var(--mantine-color-green-6)"
                              : "rgba(255,255,255,0.1)",
                          background:
                            selectedPayment === "freemius"
                              ? "rgba(34, 197, 94, 0.1)"
                              : "rgba(0,0,0,0.2)",
                        }}
                        onClick={() => handlePaymentChange("freemius")}
                      >
                        <Stack gap="sm">
                          <Group justify="space-between" wrap="nowrap">
                            <Group gap="md" wrap="nowrap">
                              <Radio value="freemius" color="green" />
                              <div>
                                <Text fw={500}>Freemius</Text>
                                <Text size="xs" c="dimmed">
                                  {t("freemiusDescription")}
                                </Text>
                              </div>
                            </Group>
                          </Group>

                          <Group gap="xs" mt="xs" wrap="wrap">
                            <Card
                              withBorder
                              radius="sm"
                              bg="transparent"
                              c="green"
                              py={2}
                              px="xs"
                            >
                              <IconBrandVisa stroke={1.5} />
                            </Card>
                            <Card
                              withBorder
                              radius="sm"
                              bg="transparent"
                              c="green"
                              py={2}
                              px="xs"
                            >
                              <IconBrandMastercard stroke={1.5} />
                            </Card>
                            <Card
                              withBorder
                              radius="sm"
                              bg="transparent"
                              c="green"
                              py={2}
                              px="xs"
                            >
                              <IconBrandPaypal stroke={1.5} />
                            </Card>
                          </Group>
                        </Stack>
                      </Paper>
                    )}
                  </Stack>
                </Radio.Group>

                <Divider />

                {/* Order Summary */}
                <Stack gap="xs">
                  <Group justify="space-between">
                    <Text size="sm" c="dimmed">
                      {t("plan")}
                    </Text>
                    <Text size="sm">{selectedPlan?.label}</Text>
                  </Group>
                  <Group justify="space-between">
                    <Text size="sm" c="dimmed">
                      {t("subtotal")}
                    </Text>
                    <Text size="sm">${selectedPlan?.price}</Text>
                  </Group>
                  {selectedPlan?.savings && (
                    <Group justify="space-between">
                      <Text size="sm" c="dimmed">
                        {t("discount")}
                      </Text>
                      <Text size="sm" c="green">
                        {selectedPlan.savings}
                      </Text>
                    </Group>
                  )}
                  <Divider my="xs" />
                  <Group justify="space-between">
                    <Text fw={600}>{t("total")}</Text>
                    <Text fw={700} size="xl" c="violet">
                      ${selectedPlan?.price}
                    </Text>
                  </Group>
                </Stack>

                {/* VAT Notice */}
                <Text size="xs" c="dimmed" ta="center">
                  {t("vatNotice")}
                </Text>

                {/* Pay Button */}
                {selectedPayment === "stripe" ? (
                  <StripePaymentButton
                    billingCycle={selectedPlan?.billingCycle || "annual"}
                    planLabel={selectedPlan?.label || "Premium"}
                    userEmail={user?.email || ""}
                    userId={String(user?.id || "")}
                    fullWidth
                    size="lg"
                    radius="md"
                    disabled={!selectedPayment}
                    style={{
                      background:
                        "linear-gradient(135deg, #8b5cf6 0%, #6366f1 100%)",
                    }}
                  >
                    {selectedBilling === "lifetime"
                      ? t("buyNow")
                      : t("subscribe")}
                  </StripePaymentButton>
                ) : (
                  <FreemiusPaymentButton
                    billingCycle={selectedPlan?.billingCycle || "annual"}
                    planLabel={selectedPlan?.label || "Premium"}
                    fullWidth
                    size="lg"
                    radius="md"
                    disabled={!selectedPayment}
                    style={{
                      background:
                        "linear-gradient(135deg, #8b5cf6 0%, #6366f1 100%)",
                    }}
                  >
                    {selectedBilling === "lifetime"
                      ? t("buyNow")
                      : t("subscribe")}
                  </FreemiusPaymentButton>
                )}

                {/* Security Note */}
                <Flex gap="xs" align="center" justify="center">
                  <IconCheck size={14} color="var(--mantine-color-green-6)" />
                  <Text size="xs" c="dimmed">
                    {t("securePayment")}
                  </Text>
                </Flex>
              </Stack>
            </Card>
          </GridCol>
        )}
      </Grid>

      {/* Cancel Subscription Modal */}
      <Modal
        opened={cancelModalOpened}
        onClose={closeCancelModal}
        title={t("cancelModalTitle")}
        centered
      >
        <Stack gap="md">
          <Text size="sm">
            {t("cancelModalMessage", {
              endDate: user?.subscriptionEndDate
                ? new Date(user.subscriptionEndDate).toLocaleDateString()
                : "",
            })}
          </Text>
          <Text size="sm" c="dimmed">
            {t("cancelModalAfter")}
          </Text>
          <Group justify="flex-end" mt="md">
            <Button variant="default" onClick={closeCancelModal}>
              {t("keepSubscription")}
            </Button>
            <Button
              color="red"
              onClick={handleCancelSubscription}
              loading={cancelling}
            >
              {t("yesCancel")}
            </Button>
          </Group>
        </Stack>
      </Modal>
    </Stack>
  );
}
