"use client";

import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { safeRelativeTime } from "@/app/lib/safe-relative-time";
import { FollowerTypeEnum, Recording } from "@/lib/types/strapi-autogenerated";
import {
  ActionIcon,
  Anchor,
  Avatar,
  Grid,
  Group,
  Stack,
  Text,
  Tooltip,
} from "@mantine/core";
import { IconSparkles } from "@tabler/icons-react";
import { useFormatter, useNow, useTranslations } from "next-intl";
import Image from "next/image";
import Link from "next/link";
import { getProfileUrl } from "../../../../components/open-social";
import { ImageSpritePreview } from "../../components/image-sprite-preview";

interface Props {
  recording: Recording;
}

export default function RecordingItem({ recording }: Props) {
  const format = useFormatter();
  const now = useNow({ updateInterval: 1000 * 30 });
  const t = useTranslations("protected.common.recordings");

  return (
    <Grid gutter="xs" key={recording.documentId} w="100%">
      {recording.follower && (
        <Grid.Col span={12}>
          <ImageSpritePreview
            username={recording.follower?.username || "unknown"}
            type={recording.follower?.type || FollowerTypeEnum.Tiktok}
            recording={recording}
          />
        </Grid.Col>
      )}
      <Grid.Col span={12}>
        <Group gap="xs" justify="space-between">
          <Group gap="xs">
            <Anchor component={Link} href={getProfileUrl(recording.follower)}>
              <Avatar size={38}>
                {recording.follower?.avatar?.url && (
                  <Image
                    src={generateAvatarUrl(recording.follower?.avatar?.url)}
                    alt={"Avatar"}
                    width={38}
                    height={38}
                  />
                )}
              </Avatar>
            </Anchor>
            <Stack gap="0">
              <Anchor
                component={Link}
                href={getProfileUrl(recording.follower)}
                size="md"
                truncate
                maw={110}
                display="inline-block"
              >
                {recording.follower?.username}
              </Anchor>
              <Text size="xs" suppressHydrationWarning>
                {t("recordedAgo", {
                  time: safeRelativeTime(format, recording.updatedAt, {
                    now,
                  }),
                })}
              </Text>
            </Stack>
          </Group>
          <Tooltip label={t("createWithAI")}>
            <ActionIcon
              component={Link}
              href={`/ai-studio/create/${recording.documentId}`}
              variant="outline"
              color="violet"
              size="lg"
            >
              <IconSparkles size={20} />
            </ActionIcon>
          </Tooltip>
        </Group>
      </Grid.Col>
    </Grid>
  );
}
