"use client";

import { DownloadUpgradeModal } from "@/app/[locale]/(protected)/components/download-upgrade-modal";
import {
  HlsVideo,
  MediaController,
  MediaLoadingIndicator,
  MediaPlayButton,
  MediaPosterImage,
} from "@/app/[locale]/(protected)/components/video/media-chrome";
import { trackEvent } from "@/app/lib/analytics";
import { useUser } from "@/app/providers/user-provider";
import { Recording } from "@/lib/types/strapi-autogenerated";
import { Box, Button, Flex, Skeleton, Text } from "@mantine/core";
import { notifications } from "@mantine/notifications";
import { IconDeviceFloppy, IconDownload } from "@tabler/icons-react";
import "hls-video-element";
import "media-chrome";
import { useLocale, useTranslations } from "next-intl";
import { useEffect, useRef, useState } from "react";
import {
  cropDownloadVideo,
  cropExportVideo,
} from "../../../actions/edit-video";
import { CustomSlider } from "../../../components/custom-slider";

interface Props {
  recording: Recording;
}

function formatTime(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  if (h > 0)
    return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
  return `${m}:${String(s).padStart(2, "0")}`;
}

export default function VideoEditor({ recording }: Props) {
  const user = useUser();
  const locale = useLocale();
  const t = useTranslations("protected.videoEditor");
  const videoRef = useRef<HTMLVideoElement>(null);

  const [duration, setDuration] = useState(0);
  const [currentTime, setCurrentTime] = useState(0);
  const [startTime, setStartTime] = useState(0);
  const [endTime, setEndTime] = useState(0);
  const [isExporting, setIsExporting] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  const [downloadUpgradeOpened, setDownloadUpgradeOpened] = useState(false);

  const isPremium = user?.role?.type !== "authenticated";

  const MAX_CLIP_DURATION = 300; // 5 minutes
  const clipDuration = endTime - startTime;
  const isOverLimit = clipDuration > MAX_CLIP_DURATION;

  // Load video duration
  useEffect(() => {
    trackEvent("video_editor_open");
    const video = videoRef.current;
    if (!video) return;

    const handleMetadata = () => {
      const dur = Math.floor(video.duration || 0);
      if (dur > 0) {
        setDuration(dur);
        setEndTime(Math.min(dur, MAX_CLIP_DURATION));
      }
    };

    // Check if metadata is already loaded (cached video)
    if (video.readyState >= 1 && video.duration > 0) {
      handleMetadata();
    } else {
      video.addEventListener("loadedmetadata", handleMetadata);
    }

    return () => video.removeEventListener("loadedmetadata", handleMetadata);
  }, []);

  // Track current time and loop within range
  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;

    const handleTimeUpdate = () => {
      setCurrentTime(video.currentTime);
      // Keep playhead within range
      if (video.currentTime < startTime) {
        video.currentTime = startTime;
      } else if (video.currentTime >= endTime && endTime > 0) {
        video.pause();
        video.currentTime = startTime;
      }
    };

    video.addEventListener("timeupdate", handleTimeUpdate);
    return () => video.removeEventListener("timeupdate", handleTimeUpdate);
  }, [startTime, endTime]);

  const handleRangeChange = (start: number, end: number) => {
    if (end - start > MAX_CLIP_DURATION) {
      // Clamp: if user moved the end, cap it; if user moved the start, adjust end
      if (start !== startTime) {
        end = Math.min(start + MAX_CLIP_DURATION, duration);
      } else {
        start = Math.max(end - MAX_CLIP_DURATION, 0);
      }
    }
    setStartTime(start);
    setEndTime(end);
  };

  const handleSeek = (time: number) => {
    const video = videoRef.current;
    if (!video) return;
    const clampedTime = Math.min(Math.round(time), duration - 1);
    video.currentTime = clampedTime;
    setCurrentTime(clampedTime);

    // If seeking outside the range, move the range to include this position
    if (clampedTime < startTime || clampedTime >= endTime) {
      const rangeSize = endTime - startTime;
      let newStart = Math.round(Math.max(0, time - rangeSize / 2));
      let newEnd = Math.round(newStart + rangeSize);
      if (newEnd > duration) {
        newEnd = Math.round(duration);
        newStart = Math.round(Math.max(0, newEnd - rangeSize));
      }
      setStartTime(newStart);
      setEndTime(newEnd);
    }
  };

  const handleExport = async () => {
    if (!user?.id || !recording.documentId || clipDuration <= 0) return;
    setIsExporting(true);
    try {
      await cropExportVideo(recording.documentId, user.id, locale, startTime, endTime);
      notifications.show({
        title: t("notifications.exportStarted.title"),
        message: t("notifications.exportStarted.message"),
        color: "green",
      });
    } finally {
      setIsExporting(false);
    }
  };

  const handleDownload = async () => {
    if (!user?.id || !recording.documentId || clipDuration <= 0) return;
    if (!isPremium) {
      setDownloadUpgradeOpened(true);
      return;
    }
    trackEvent("video_editor_download", {
      recording_id: recording.documentId,
      original_duration: duration,
      clip_duration: clipDuration,
    });
    setIsDownloading(true);
    try {
      await cropDownloadVideo(
        recording.documentId,
        user.id,
        locale,
        startTime,
        endTime,
      );
      notifications.show({
        title: t("notifications.downloadQueued.title"),
        message: t("notifications.downloadQueued.message"),
        color: "green",
      });
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <>
      <style>{`
        /* Hide play button when playing */
        media-controller:not([mediapaused]) media-play-button[slot="centered-chrome"] {
          display: none !important;
        }
        /* Hide loading indicator when paused (including before first play) */
        media-controller[mediapaused] media-loading-indicator[slot="centered-chrome"] {
          display: none !important;
        }
      `}</style>
      <Box
        style={{
          width: "100%",
          height: "clamp(200px, 35vh, 400px)",
          borderRadius: "var(--mantine-radius-md)",
          overflow: "hidden",
          background: "#000",
        }}
      >
        <MediaController
          style={{ width: "100%", height: "100%", background: "#000" }}
        >
          <HlsVideo
            ref={videoRef}
            src={`/video/${recording.documentId}/playlist.m3u8`}
            slot="media"
            playsInline
          >
            <track
              default
              kind="metadata"
              label="thumbnails"
              src={`/video/${recording.documentId}/thumbnails.vtt`}
            />
          </HlsVideo>
          <MediaPosterImage
            slot="poster"
            src={`/video/${recording.documentId}/screenshot.jpg`}
          />
          <MediaPlayButton
            slot="centered-chrome"
            style={{
              "--media-button-icon-height": "64px",
              "--media-button-icon-width": "64px",
            }}
          />
          <MediaLoadingIndicator slot="centered-chrome" />
        </MediaController>
      </Box>

      {duration === 0 && (
        <Skeleton height={142} radius="md" my="md" />
      )}
      {duration > 0 && (
        <CustomSlider
          duration={duration}
          currentTime={currentTime}
          startTime={startTime}
          endTime={endTime}
          maxRange={MAX_CLIP_DURATION}
          onRangeChange={handleRangeChange}
          onSeek={handleSeek}
          formatTime={formatTime}
          vttUrl={`/video/${recording.documentId}/thumbnails.vtt`}
        />
      )}

      <Text size="xs" c="dimmed" ta="center" mb="md">
        {t("maxDuration", { minutes: MAX_CLIP_DURATION / 60 })} — {formatTime(clipDuration)} / {formatTime(MAX_CLIP_DURATION)}
      </Text>

      <Flex direction="row" gap="md">
        <Button
          fullWidth
          size="lg"
          radius="md"
          leftSection={<IconDeviceFloppy />}
          onClick={handleExport}
          loading={isExporting}
          disabled={clipDuration <= 0}
        >
          {t("actions.saveClip")}
        </Button>

        <Button
          fullWidth
          size="lg"
          radius="md"
          variant="light"
          leftSection={<IconDownload />}
          onClick={handleDownload}
          loading={isDownloading}
          disabled={clipDuration <= 0}
        >
          {t("actions.downloadClip")}
        </Button>
      </Flex>

      <DownloadUpgradeModal
        opened={downloadUpgradeOpened}
        onClose={() => setDownloadUpgradeOpened(false)}
      />
    </>
  );
}
