"use client";

import {
  HlsVideo,
  MediaController,
  MediaLoadingIndicator,
  MediaPlayButton,
  MediaPosterImage,
} from "@/app/[locale]/(protected)/components/video/media-chrome";
import { useUser } from "@/app/providers/user-provider";
import { Recording } from "@/lib/types/strapi-autogenerated";
import { Box, Button } from "@mantine/core";
import { notifications } from "@mantine/notifications";
import { IconCut, IconDownload } from "@tabler/icons-react";
import "hls-video-element";
import "media-chrome";
import { useLocale, useTranslations } from "next-intl";
import { useEffect, useRef, useState } from "react";
import { DownloadUpgradeModal } from "@/app/[locale]/(protected)/components/download-upgrade-modal";
import { cropDownloadVideo, cropExportVideo } from "../../../actions/edit-video";
import { CustomSlider } from "../../../components/custom-slider";

interface Props {
  recording: Recording;
}

function formatTime(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  if (h > 0)
    return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
  return `${m}:${String(s).padStart(2, "0")}`;
}

export default function VideoEditor({ recording }: Props) {
  const user = useUser();
  const locale = useLocale();
  const t = useTranslations("protected.videoEditor");
  const videoRef = useRef<HTMLVideoElement>(null);

  const [duration, setDuration] = useState(0);
  const [currentTime, setCurrentTime] = useState(0);
  const [startTime, setStartTime] = useState(0);
  const [endTime, setEndTime] = useState(0);
  const [isExporting, setIsExporting] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  const [downloadUpgradeOpened, setDownloadUpgradeOpened] = useState(false);

  const isPremium = user?.role?.type !== "authenticated";

  const clipDuration = endTime - startTime;

  // Load video duration
  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;
    const handleMetadata = () => {
      const dur = Math.floor(video.duration || 0);
      setDuration(dur);
      setEndTime(dur);
    };
    video.addEventListener("loadedmetadata", handleMetadata, { once: true });
    return () => video.removeEventListener("loadedmetadata", handleMetadata);
  }, []);

  // Track current time and loop within range
  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;

    const handleTimeUpdate = () => {
      setCurrentTime(video.currentTime);
      // Keep playhead within range
      if (video.currentTime < startTime) {
        video.currentTime = startTime;
      } else if (video.currentTime >= endTime && endTime > 0) {
        video.pause();
        video.currentTime = startTime;
      }
    };

    video.addEventListener("timeupdate", handleTimeUpdate);
    return () => video.removeEventListener("timeupdate", handleTimeUpdate);
  }, [startTime, endTime]);

  const handleRangeChange = (start: number, end: number) => {
    setStartTime(start);
    setEndTime(end);
  };

  const handleSeek = (time: number) => {
    const video = videoRef.current;
    if (!video) return;
    video.currentTime = time;
    setCurrentTime(time);
  };

  const handleExport = async () => {
    if (!user?.id || !recording.documentId || clipDuration <= 0) return;
    setIsExporting(true);
    try {
      await cropExportVideo(recording.documentId, user.id, startTime, endTime);
      notifications.show({
        title: t("notifications.exportStarted.title"),
        message: t("notifications.exportStarted.message"),
        color: "green",
      });
    } finally {
      setIsExporting(false);
    }
  };

  const handleDownload = async () => {
    if (!user?.id || !recording.documentId || clipDuration <= 0) return;
    if (!isPremium) {
      setDownloadUpgradeOpened(true);
      return;
    }
    setIsDownloading(true);
    try {
      await cropDownloadVideo(
        recording.documentId,
        user.id,
        locale,
        startTime,
        endTime,
      );
      notifications.show({
        title: t("notifications.downloadQueued.title"),
        message: t("notifications.downloadQueued.message"),
        color: "green",
      });
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <>
      <style>{`
        /* Hide play button when playing */
        media-controller:not([mediapaused]) media-play-button[slot="centered-chrome"] {
          display: none !important;
        }
        /* Hide loading indicator when paused (including before first play) */
        media-controller[mediapaused] media-loading-indicator[slot="centered-chrome"] {
          display: none !important;
        }
      `}</style>
      <Box
        style={{
          width: "100%",
          height: "55vh",
          borderRadius: "var(--mantine-radius-md)",
          overflow: "hidden",
          background: "#000",
        }}
      >
        <MediaController
          style={{ width: "100%", height: "100%", background: "#000" }}
        >
          <HlsVideo
            ref={videoRef}
            src={`/video/${recording.documentId}/playlist.m3u8`}
            slot="media"
            playsInline
          >
            <track
              default
              kind="metadata"
              label="thumbnails"
              src={`/video/${recording.documentId}/thumbnails.vtt`}
            />
          </HlsVideo>
          <MediaPosterImage
            slot="poster"
            src={`/video/${recording.documentId}/screenshot.jpg`}
          />
          <MediaPlayButton
            slot="centered-chrome"
            style={{
              "--media-button-icon-height": "64px",
              "--media-button-icon-width": "64px",
            }}
          />
          <MediaLoadingIndicator slot="centered-chrome" />
        </MediaController>
      </Box>

      <CustomSlider
        duration={duration}
        currentTime={currentTime}
        startTime={startTime}
        endTime={endTime}
        onRangeChange={handleRangeChange}
        onSeek={handleSeek}
        formatTime={formatTime}
        vttUrl={`/video/${recording.documentId}/thumbnails.vtt`}
      />

      <Button
        fullWidth
        size="lg"
        radius="md"
        leftSection={<IconDownload />}
        onClick={handleDownload}
        loading={isDownloading}
        disabled={clipDuration <= 0}
      >
        {t("actions.downloadClip")}
      </Button>

      <DownloadUpgradeModal
        opened={downloadUpgradeOpened}
        onClose={() => setDownloadUpgradeOpened(false)}
      />
    </>
  );
}
