"use client";

import { exportClip, downloadClip } from "@/app/actions/clip-recording";
import { useUser } from "@/app/providers/user-provider";
import { Recording } from "@/lib/types/strapi-autogenerated";
import {
  ActionIcon,
  Box,
  Button,
  Card,
  Flex,
  Group,
  RangeSlider,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import { notifications } from "@mantine/notifications";
import {
  IconArrowLeft,
  IconCut,
  IconDownload,
  IconFlag,
} from "@tabler/icons-react";
import "hls-video-element";
import "media-chrome";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useLayoutEffect, useRef, useState } from "react";
import {
  HlsVideo,
  MediaControlBar,
  MediaController,
  MediaLoadingIndicator,
  MediaMuteButton,
  MediaPlayButton,
  MediaSeekBackwardButton,
  MediaSeekForwardButton,
  MediaTimeDisplay,
  MediaTimeRange,
  MediaVolumeRange,
} from "@/app/[locale]/(protected)/components/video/media-chrome";
import { getProfileUrl } from "@/app/components/open-social";

interface Props {
  recording: Recording;
}

function formatTime(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  if (h > 0) return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
  return `${m}:${String(s).padStart(2, "0")}`;
}

export default function VideoEditor({ recording }: Props) {
  const user = useUser();
  const params = useParams<{ type: string; username: string; id: string }>();
  const videoRef = useRef<HTMLVideoElement>(null);
  const timeRangeRef = useRef<HTMLElement>(null);
  const timeDisplayRef = useRef<HTMLElement>(null);
  const seekWrapperRef = useRef<HTMLDivElement>(null);

  const [duration, setDuration] = useState(0);
  const [startTime, setStartTime] = useState(0);
  const [endTime, setEndTime] = useState(0);
  const [clipCurrentTime, setClipCurrentTime] = useState(0);
  const [isExporting, setIsExporting] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);

  const profileUrl = getProfileUrl({ username: params.username, type: params.type as any });
  const clipDuration = endTime - startTime;

  // Use refs so the event listener below always sees current values without re-registration
  const startTimeRef = useRef(startTime);
  const clipDurationRef = useRef(clipDuration);
  useEffect(() => { startTimeRef.current = startTime; }, [startTime]);
  useEffect(() => { clipDurationRef.current = clipDuration; }, [clipDuration]);

  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;
    const handleMetadata = () => {
      const dur = Math.floor(video.duration || 0);
      setDuration(dur);
      setEndTime(dur);
    };
    video.addEventListener("loadedmetadata", handleMetadata, { once: true });
    return () => video.removeEventListener("loadedmetadata", handleMetadata);
  }, []);

  // Always enforce clip boundaries and track clip-relative time
  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;

    const handleTimeUpdate = () => {
      if (video.currentTime < startTime) {
        video.currentTime = startTime;
        return;
      }
      if (video.currentTime >= endTime && endTime > 0) {
        video.pause();
        video.currentTime = startTime;
        setClipCurrentTime(0);
        return;
      }
      setClipCurrentTime(video.currentTime - startTime);
    };

    video.addEventListener("timeupdate", handleTimeUpdate);
    return () => video.removeEventListener("timeupdate", handleTimeUpdate);
  }, [startTime, endTime]);

  // Intercept mediaseekrequest from MediaTimeRange and translate to absolute video time.
  // Registered once — uses refs internally so no re-registration needed.
  useEffect(() => {
    const el = seekWrapperRef.current;
    if (!el) return;

    const handleSeekRequest = (e: Event) => {
      e.stopPropagation();
      const video = videoRef.current;
      if (!video) return;
      const seekTo = (e as CustomEvent).detail.seekTo as number;
      video.currentTime = startTimeRef.current + Math.max(0, Math.min(clipDurationRef.current, seekTo));
    };

    el.addEventListener("mediaseekrequest", handleSeekRequest);
    return () => el.removeEventListener("mediaseekrequest", handleSeekRequest);
  }, []);

  // After every render, override media-chrome's automatic attributes with clip-relative values.
  // useLayoutEffect runs before paint, so the controller's writes (which happen on timeupdate)
  // are overwritten before the browser draws the frame — no visible flicker.
  useLayoutEffect(() => {
    const tr = timeRangeRef.current as any;
    const td = timeDisplayRef.current as any;
    const seekable = `0:${clipDuration}`;
    if (tr) {
      tr.setAttribute("mediacurrenttime", String(clipCurrentTime));
      tr.setAttribute("mediaduration", String(clipDuration));
      tr.setAttribute("mediaseekable", seekable);
    }
    if (td) {
      td.setAttribute("mediacurrenttime", String(clipCurrentTime));
      td.setAttribute("mediaduration", String(clipDuration));
    }
  });

  // When clip range changes, seek to new startTime
  const handleRangeChangeEnd = (value: [number, number]) => {
    const video = videoRef.current;
    if (!video) return;
    video.currentTime = value[0];
    setClipCurrentTime(0);
  };

  const handleRangeChange = (value: [number, number]) => {
    setStartTime(value[0]);
    setEndTime(value[1]);
  };

  const handleSetStart = () => {
    const video = videoRef.current;
    if (!video) return;
    const t = Math.floor(video.currentTime);
    if (t >= endTime) {
      notifications.show({ message: "Start time must be before end time", color: "red" });
      return;
    }
    setStartTime(t);
    setClipCurrentTime(0);
  };

  const handleSetEnd = () => {
    const video = videoRef.current;
    if (!video) return;
    const actual = Math.ceil(video.currentTime);
    if (actual <= startTime) {
      notifications.show({ message: "End time must be after start time", color: "red" });
      return;
    }
    setEndTime(actual);
  };

  const handleExport = async () => {
    if (!user?.id || !recording.documentId || clipDuration <= 0) return;
    setIsExporting(true);
    try {
      await exportClip(recording.documentId, user.id, startTime, endTime);
      notifications.show({ title: "Export started", message: "Your clip is being processed and will be saved to your storage", color: "green" });
    } finally {
      setIsExporting(false);
    }
  };

  const handleDownload = async () => {
    if (!user?.id || !recording.documentId || clipDuration <= 0) return;
    setIsDownloading(true);
    try {
      await downloadClip(recording.documentId, user.id, "en", startTime, endTime);
      notifications.show({ title: "Download queued", message: "Your clip will be emailed to you when ready", color: "green" });
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <Stack gap="md">
      <Group>
        <ActionIcon component={Link} href={`${profileUrl}/video/${params.id}`} variant="subtle" size="lg">
          <IconArrowLeft />
        </ActionIcon>
        <Title order={4}>Edit Clip</Title>
        {recording.follower?.username && (
          <Text c="dimmed" size="sm">{decodeURIComponent(recording.follower.username)}</Text>
        )}
      </Group>

      {/* Video Player — native media-chrome controls show clip-relative time */}
      <Box mx="auto" style={{ aspectRatio: "9/16", maxHeight: "55vh", width: "auto", borderRadius: "var(--mantine-radius-md)", overflow: "hidden", background: "#000" }}>
        <style>{`
          media-controller:not([mediapaused]) media-play-button[slot="centered-chrome"] { display: none !important; }
          media-controller[mediapaused] media-loading-indicator[slot="centered-chrome"] { display: none !important; }
        `}</style>
        <MediaController style={{ width: "100%", height: "100%", background: "#000" }}>
          <HlsVideo ref={videoRef} src={`/video/${recording.documentId}/playlist.m3u8`} slot="media" playsInline>
            <track default kind="metadata" label="thumbnails" src={`/video/${recording.documentId}/thumbnails.vtt`} />
          </HlsVideo>
          <MediaPlayButton slot="centered-chrome" />
          <MediaLoadingIndicator slot="centered-chrome" />
          <MediaControlBar>
            <MediaPlayButton />
            <MediaSeekBackwardButton seekoffset="10" />
            <MediaSeekForwardButton seekoffset="10" />
            {/* Wrapper intercepts seek requests and translates to absolute video time */}
            <div ref={seekWrapperRef} style={{ display: "contents" }}>
              <MediaTimeRange ref={timeRangeRef as any} />
              <MediaTimeDisplay showduration ref={timeDisplayRef as any} />
            </div>
            <div className="volume-hover-container">
              <MediaVolumeRange />
              <MediaMuteButton title="" />
            </div>
          </MediaControlBar>
        </MediaController>
      </Box>

      {/* Clip Range */}
      <Card withBorder p="md">
        <Stack gap="md">
          <Group justify="space-between">
            <Text fw={600} size="sm">Clip Range</Text>
            {clipDuration > 0 && <Text size="xs" c="dimmed">Duration: {formatTime(clipDuration)}</Text>}
          </Group>

          <Box px={4}>
            <RangeSlider
              min={0}
              max={duration || 100}
              step={1}
              value={[startTime, endTime]}
              onChange={handleRangeChange}
              onChangeEnd={handleRangeChangeEnd}
              disabled={duration === 0}
              label={formatTime}
              marks={[
                { value: 0, label: formatTime(0) },
                ...(duration > 0 ? [{ value: duration, label: formatTime(duration) }] : []),
              ]}
              mb="xl"
            />
          </Box>

          <Group grow>
            <Stack gap={4}>
              <Group justify="space-between">
                <Text size="xs" c="dimmed">Start</Text>
                <Text size="xs" fw={600} c="blue">{formatTime(startTime)}</Text>
              </Group>
              <Button variant="light" size="xs" leftSection={<IconFlag size={12} />} onClick={handleSetStart}>
                Mark current as start
              </Button>
            </Stack>

            <Stack gap={4}>
              <Group justify="space-between">
                <Text size="xs" c="dimmed">End</Text>
                <Text size="xs" fw={600} c="blue">{formatTime(endTime)}</Text>
              </Group>
              <Button variant="light" size="xs" leftSection={<IconFlag size={12} />} onClick={handleSetEnd}>
                Mark current as end
              </Button>
            </Stack>
          </Group>
        </Stack>
      </Card>

      {/* Export */}
      <Card withBorder p="md">
        <Stack gap="sm">
          <Text fw={600} size="sm">Export</Text>
          <Flex gap="sm">
            <Button flex={1} variant="light" leftSection={<IconCut size={16} />} onClick={handleExport} loading={isExporting} disabled={clipDuration <= 0}>
              Export to storage
            </Button>
            <Button flex={1} leftSection={<IconDownload size={16} />} onClick={handleDownload} loading={isDownloading} disabled={clipDuration <= 0}>
              Download clip
            </Button>
          </Flex>
        </Stack>
      </Card>
    </Stack>
  );
}
