import {
  countryCodeToSlug,
  countrySlugToCode,
  getCountryName,
} from "@/app/lib/country-utils";
import { streamingPlatforms } from "@/app/lib/streaming-platforms";
import { FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import {
  Badge,
  Container,
  Group,
  Image as MantineImage,
  Stack,
  Text,
  Title,
  Tooltip,
} from "@mantine/core";
import { IconArrowLeft, IconMapPin } from "@tabler/icons-react";
import { getLocale, getTranslations } from "next-intl/server";
import Image from "next/image";
import Link from "@/app/components/link";
import { getFollowerFilters } from "../../cache";

interface LayoutProps {
  params: Promise<{
    type: string;
    country: string;
  }>;
  children: React.ReactNode;
}

export default async function Layout({ params, children }: LayoutProps) {
  const { type, country } = await params;
  const locale = await getLocale();
  const t = await getTranslations("recordings");

  const platform = streamingPlatforms.find(
    (p) => p.name.toLowerCase() === type,
  ) || {
    color: "#ff0050",
    name: "",
    file: "creators.png",
  };

  const platformKey = platform.name ? type : "all";
  const platformName = platform.name || "All";
  const countryCode = countrySlugToCode(country, locale);
  const countryName = countryCode
    ? getCountryName(countryCode, locale)
    : getCountryName(country, locale);

  const { countryCodes } = await getFollowerFilters(
    platformKey as FollowerTypeEnum,
  );

  return (
    <Container size="xl">
      <div
        style={{
          position: "absolute",
          top: 0,
          left: 0,
          width: "100%",
          height: 700,
          zIndex: 0,
          pointerEvents: "none",
        }}
      >
        <Image
          src="/recordings.svg"
          alt="background"
          fill
          priority
          style={{ objectFit: "cover" }}
        />
      </div>
      <Stack align="center" gap={24} mb={60}>
        <Badge
          size="lg"
          variant="light"
          color="violet"
          leftSection={<IconMapPin size={14} />}
        >
          {countryName}
        </Badge>

        <Title
          order={1}
          ta="center"
          style={{
            fontSize: "clamp(2.5rem, 6vw, 4rem)",
            fontWeight: 800,
            lineHeight: 1.2,
            letterSpacing: "-0.03em",
            background:
              "linear-gradient(135deg, #ffffff 0%, #e2e8f0 50%, #94a3b8 100%)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
            paddingBottom: "0.1em",
          }}
        >
          {t("country.heroTitle", {
            platform: t(`hero.title.${platformKey}`),
            country: countryName,
          })}
        </Title>

        <Text
          size="xl"
          ta="center"
          maw={600}
          style={{ color: "#94a3b8", lineHeight: 1.7 }}
        >
          {t("country.heroSubtitle", {
            platform: platformName,
            country: countryName,
          })}
        </Text>
      </Stack>

      {/* Back to platform link */}
      <Group justify="center" mb="lg">
        <Link
          href={`/recordings/${type}`}
          style={{
            display: "flex",
            alignItems: "center",
            gap: 8,
            color: "#94a3b8",
            textDecoration: "none",
            fontSize: 14,
          }}
        >
          <IconArrowLeft size={16} />
          {t("country.backToPlatform", {
            platform: t(`hero.title.${platformKey}`),
          })}
        </Link>
      </Group>

      {/* Country Flags */}
      {countryCodes.length > 0 && (
        <Group justify="center" gap="xs" mt="md" mb="xl">
          {countryCodes.map(({ value: code }) => {
            const slug = countryCodeToSlug(code, "en"); // Always use English for URL slugs
            const name = getCountryName(code, locale);
            const isActive = code.toUpperCase() === countryCode?.toUpperCase();

            return (
              <Tooltip key={code} label={name} withArrow>
                <Link
                  href={`/recordings/${type}/${slug}`}
                  style={{
                    display: "block",
                    borderRadius: 4,
                    overflow: "hidden",
                    border: isActive
                      ? "2px solid #6366f1"
                      : "2px solid transparent",
                    opacity: isActive ? 1 : 0.7,
                    transition: "all 0.2s ease",
                  }}
                >
                  <MantineImage
                    src={`https://flagcdn.com/w40/${code.toLowerCase()}.png`}
                    alt={name}
                    w={30}
                    h={22}
                    radius={2}
                    fit="cover"
                  />
                </Link>
              </Tooltip>
            );
          })}
        </Group>
      )}

      {children}
    </Container>
  );
}
