import api from "@/lib/api";
import { FINGERPRINT_COOKIE, MAX_PUBLIC_VIEWS } from "@/lib/constants";
import publicApi from "@/lib/public-api";
import { getBucket, getS3, proxySignedUrl } from "@/lib/s3";
import { getToken } from "@/lib/token";
import { Source } from "@/lib/types/strapi-autogenerated";
import type { S3Client } from "@aws-sdk/client-s3";
import { GetObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { unstable_cache } from "next/cache";
import { cookies } from "next/headers";
import { NextRequest } from "next/server";

async function getRecordingByDocumentId(documentId: string) {
  const response = await publicApi.recording.getRecordings({
    filters: {
      documentId: { $eq: documentId },
    },
    populate: {
      follower: {
        fields: ["documentId"],
      },
    },
    "pagination[limit]": 1,
  });
  return response.data.data?.[0] ?? null;
}


const fetchSourcePlaylists = unstable_cache(
  async (documentId: string, _updatedAt: string, quality: "high" | "low" = "high") => {
    const response = await publicApi.source.getSources({
      filters: {
        recording: { documentId },
        state: { $eq: "done" },
      },
      sort: "createdAt:asc",
      fields: ["path", "createdAt", "bucket"],
    } as any);

    const sources = response.data.data ?? [];
    if (!sources.length) return null;

    const s3Client = getS3();
    const bucket = getBucket(process.env.MEDIA_BUCKET!, sources[0].createdAt, sources[0].path, sources[0].bucket);
    const sourcesWithPlaylists = await fetchPlaylistsFromS3(
      s3Client,
      bucket,
      sources,
      quality,
    );

    return { sourcesWithPlaylists, createdAt: sources[0].createdAt, path: sources[0].path, bucket: sources[0].bucket };
  },
  ["playlist-sources"],
  { revalidate: 300 },
);

async function buildPlaylist(documentId: string, updatedAt: string, quality: "high" | "low" = "high") {
  const cached = await fetchSourcePlaylists(documentId, updatedAt, quality);
  if (!cached) return null;

  const s3Client = getS3();
  const bucket = getBucket(process.env.MEDIA_BUCKET!, cached.createdAt, cached.path, cached.bucket);
  return combinePlaylistsWithSignedUrls(s3Client, bucket, cached.sourcesWithPlaylists);
}

async function checkLowQualityExists(documentId: string, updatedAt: string): Promise<boolean> {
  const cached = await fetchSourcePlaylists(documentId, updatedAt, "low");
  if (!cached) return false;
  return cached.sourcesWithPlaylists.every((s) => s.playlist != null);
}

function buildMasterPlaylist(documentId: string): string {
  const base = `/video/${documentId}/playlist.m3u8`;
  return `#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=2000000,RESOLUTION=1920x1080,NAME="Original"
${base}?q=high
#EXT-X-STREAM-INF:BANDWIDTH=600000,RESOLUTION=1280x720,NAME="HD"
${base}?q=low
`;
}

export type SourceWithPlaylist = Source & { playlist?: string | null };

type AccessResult =
  | { allowed: true }
  | { allowed: false; reason: "sign-in" | "upgrade" };

async function checkAccess(
  recordingDocumentId: string,
  followerDocumentId?: string,
): Promise<AccessResult> {
  const token = await getToken();
  const isLoggedIn = !!token;

  if (isLoggedIn) {
    // Get user role
    const user =
      await api.usersPermissionsUsersRoles.getUsersPermissionsUsersRoles({
        populate: {
          role: true,
          followers: {
            fields: ["id"],
          },
        },
      });

    const role = user?.data?.role;
    const roleType = (role as any)?.type;
    //const subscriptionStatus = (user?.data as any)?.subscriptionStatus;

    // Admin, champion, or active subscription = full access
    if (
      roleType === "admin" ||
      roleType === "champion" ||
      roleType === "premium"
    ) {
      return { allowed: true };
    }

    // Basic user - check if following this creator
    if (followerDocumentId) {
      const userFollowers = (user?.data as any)?.followers || [];
      const isFollowing = userFollowers.some(
        (f: any) => f.documentId === followerDocumentId,
      );

      if (isFollowing) {
        return { allowed: true };
      }
    }

    // Basic user not following - check view limit by user ID
    const userId = (user?.data as any)?.documentId;
    if (userId) {
      const userFingerprint = `user:${userId}`;

      const { data: viewsData } = await publicApi.visitorView.getVisitorViews({
        filters: {
          fingerprint: { $eq: userFingerprint },
        },
        populate: "recording",
        "pagination[limit]": MAX_PUBLIC_VIEWS + 1,
      });

      const viewedRecordings = new Set(
        viewsData.data?.map((v) => v.recording?.documentId).filter(Boolean),
      );

      const alreadyViewed = viewedRecordings.has(recordingDocumentId);

      if (alreadyViewed) {
        return { allowed: true };
      }

      if (viewedRecordings.size >= MAX_PUBLIC_VIEWS) {
        return { allowed: false, reason: "upgrade" };
      }

      // Record this view for user
      await publicApi.visitorView.postVisitorViews({
        data: {
          fingerprint: userFingerprint,
          recording: recordingDocumentId,
        },
      });

      return { allowed: true };
    }

    // Basic user not following, no user ID (shouldn't happen)
    return { allowed: false, reason: "upgrade" };
  }

  // Public user - check fingerprint view count
  const cookieStore = await cookies();
  const fingerprint = cookieStore.get(FINGERPRINT_COOKIE)?.value;

  if (!fingerprint) {
    // No fingerprint yet, allow (will be set client-side)
    return { allowed: true };
  }

  // Count unique recordings this fingerprint has viewed
  const { data: viewsData } = await publicApi.visitorView.getVisitorViews({
    filters: {
      fingerprint: { $eq: fingerprint },
    },
    populate: "recording",
    "pagination[limit]": MAX_PUBLIC_VIEWS + 1,
  });

  const viewedRecordings = new Set(
    viewsData.data?.map((v) => v.recording?.documentId).filter(Boolean),
  );

  const alreadyViewed = viewedRecordings.has(recordingDocumentId);

  if (alreadyViewed) {
    return { allowed: true };
  }

  if (viewedRecordings.size >= MAX_PUBLIC_VIEWS) {
    return { allowed: false, reason: "sign-in" };
  }

  // Record this view
  await publicApi.visitorView.postVisitorViews({
    data: {
      fingerprint,
      recording: recordingDocumentId,
    },
  });

  return { allowed: true };
}

async function getPlaceholderPlaylist(
  type: "sign-in" | "upgrade",
): Promise<string> {
  const cookieStore = await cookies();
  const locale = cookieStore.get("NEXT_LOCALE")?.value || "en";

  const baseName = type === "sign-in" ? "please-sign-in" : "please-upgrade";
  const filename = `${baseName}-${locale}.mp4`;

  return `#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:4
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:3.0,
${process.env.NEXT_PUBLIC_BASE_URL}/media/${filename}
#EXT-X-ENDLIST
`;
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ documentId: string }> },
) {
  const { documentId } = await params;

  // Get recording with follower info for access check
  const recording = await getRecordingByDocumentId(documentId);
  if (!recording) {
    return new Response("Not found", { status: 404 });
  }

  // Check access
  const accessResult = await checkAccess(
    recording.documentId!,
    recording.follower?.documentId,
  );

  if (!accessResult.allowed) {
    const playlist = await getPlaceholderPlaylist(accessResult.reason);
    return new Response(playlist, {
      headers: {
        "Content-Type": "application/vnd.apple.mpegurl",
        "Cache-Control": "no-cache",
      },
    });
  }

  const qualityParam = request.nextUrl.searchParams.get("q") as "high" | "low" | null;

  // If specific quality requested, serve that playlist
  if (qualityParam === "high" || qualityParam === "low") {
    const playlist = await buildPlaylist(documentId, recording.updatedAt || "", qualityParam);
    if (!playlist) {
      return new Response("Not found", { status: 404 });
    }
    return new Response(playlist, {
      headers: {
        "Content-Type": "application/vnd.apple.mpegurl",
        "Cache-Control": "no-store",
      },
    });
  }

  // No quality param — check if low quality exists
  const hasLow = await checkLowQualityExists(documentId, recording.updatedAt || "");

  if (hasLow) {
    // Serve master playlist with both qualities
    return new Response(buildMasterPlaylist(documentId), {
      headers: {
        "Content-Type": "application/vnd.apple.mpegurl",
        "Cache-Control": "no-store",
      },
    });
  }

  // No low quality — serve single playlist directly
  const playlist = await buildPlaylist(documentId, recording.updatedAt || "");
  if (!playlist) {
    return new Response("Not found", { status: 404 });
  }

  return new Response(playlist, {
    headers: {
      "Content-Type": "application/vnd.apple.mpegurl",
      "Cache-Control": "no-store",
    },
  });
}

async function fetchFromS3(
  s3Client: S3Client,
  bucket: string,
  key: string,
): Promise<string | null> {
  const abortController = new AbortController();

  try {
    const command = new GetObjectCommand({
      Bucket: bucket,
      Key: key,
    });
    const response = await s3Client.send(command, {
      abortSignal: abortController.signal,
    });

    if (!response.Body) {
      abortController.abort();
      return null;
    }

    return await response.Body.transformToString();
  } catch (error) {
    abortController.abort();

    // Only log if not NoSuchKey (reduce noise)
    if (
      (error as any).Code !== "NoSuchKey" &&
      (error as any).name !== "NoSuchKey"
    ) {
      console.error("Error fetching playlist from S3", { key }, error);
    }

    return null;
  }
}

async function fetchPlaylistsFromS3(
  s3Client: S3Client,
  bucket: string,
  sources: Source[],
  quality: "high" | "low",
): Promise<SourceWithPlaylist[]> {
  const filename = quality === "low" ? "playlist_low.m3u8" : "playlist.m3u8";

  // Fetch all playlists in parallel
  const playlists = await Promise.all(
    sources.map((source) =>
      source.path
        ? fetchFromS3(
            s3Client,
            bucket,
            `${source.path.substring(1)}${filename}`,
          )
        : Promise.resolve(null),
    ),
  );

  return sources.map((source, i) => ({
    ...source,
    playlist: playlists[i],
  }));
}

async function combinePlaylistsWithSignedUrls(
  s3Client: S3Client,
  bucket: string,
  sources: SourceWithPlaylist[],
): Promise<string> {
  if (!sources || sources.length === 0) return "";

  // Collect all segments that need signing
  const toSign: { mapKey: string; s3Key: string }[] = [];
  const seen = new Set<string>();

  for (const source of sources) {
    if (!source.playlist || !source.path) continue;
    const lines = source.playlist.split("\n");
    for (const line of lines) {
      const mapMatch = line.match(/URI="([^"]+)"/);
      if (mapMatch) {
        const filename = mapMatch[1];
        const mapKey = `${source.path}${filename}`;
        if (!seen.has(mapKey)) {
          seen.add(mapKey);
          toSign.push({
            mapKey,
            s3Key: `${source.path.substring(1)}${filename}`,
          });
        }
      }
      if (line.includes(".mp4") && !line.startsWith("#")) {
        const segMatch = line.trim().match(/(\S+\.mp4)/);
        if (segMatch) {
          const filename = segMatch[1];
          const mapKey = `${source.path}${filename}`;
          if (!seen.has(mapKey)) {
            seen.add(mapKey);
            toSign.push({
              mapKey,
              s3Key: `${source.path.substring(1)}${filename}`,
            });
          }
        }
      }
    }
  }

  // Sign all URLs in parallel
  const signedEntries = await Promise.all(
    toSign.map(async ({ mapKey, s3Key }) => {
      const command = new GetObjectCommand({ Bucket: bucket, Key: s3Key });
      const url = await getSignedUrl(s3Client, command, { expiresIn: 14400 });
      return [mapKey, proxySignedUrl(url)] as const;
    }),
  );
  const urlMap = new Map(signedEntries);

  // Build the combined playlist
  let combined = "#EXTM3U\n#EXT-X-VERSION:7\n";
  let maxDuration = 0;
  let isFirst = true;

  for (const source of sources) {
    const playlist = source.playlist;
    if (!playlist) continue;

    const lines = playlist.split("\n");

    for (const line of lines) {
      if (line.startsWith("#EXTM3U")) continue;
      if (line.startsWith("#EXT-X-VERSION")) continue;
      if (line.startsWith("#EXT-X-MEDIA-SEQUENCE")) continue;
      if (line.startsWith("#EXT-X-ENDLIST")) continue;

      if (line.startsWith("#EXT-X-TARGETDURATION")) {
        const dur = parseInt(line.split(":")[1]);
        if (dur > maxDuration) maxDuration = dur;
        continue;
      }

      if (line.startsWith("#EXT-X-MAP")) {
        if (!isFirst) {
          combined += "#EXT-X-DISCONTINUITY\n";
        }
        isFirst = false;
        combined +=
          line.replace(
            /URI="([^"]+)"/,
            (_, filename) =>
              `URI="${urlMap.get(`${source.path}${filename}`) || filename}"`,
          ) + "\n";
        continue;
      }

      if (line.includes(".mp4")) {
        combined +=
          line.replace(
            /(\S+\.mp4)/g,
            (filename) =>
              urlMap.get(`${source.path}${filename}`) || filename,
          ) + "\n";
      } else if (line.trim()) {
        combined += line + "\n";
      }
    }
  }

  combined = combined.replace(
    "#EXT-X-VERSION:7\n",
    `#EXT-X-VERSION:7\n#EXT-X-TARGETDURATION:${maxDuration || 12}\n`,
  );

  combined += "#EXT-X-ENDLIST\n";
  return combined;
}
