"use client";

import { Clip } from "@/lib/types/strapi-autogenerated";
import {
  Alert,
  Anchor,
  AspectRatio,
  Button,
  Card,
  Grid,
  Group,
  Loader,
  Select,
  Stack,
  Text,
  TextInput,
  Textarea,
} from "@mantine/core";
import { useForm } from "@mantine/form";
import { notifications } from "@mantine/notifications";
import {
  IconAlertCircle,
  IconArrowLeft,
  IconBrandYoutube,
} from "@tabler/icons-react";
import { useTranslations } from "next-intl";
import Link from "@/app/components/link";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { getYouTubeConnection } from "../../../../settings/actions/youtube";
import { shareToYouTube } from "../../../actions/share-youtube";

interface YouTubePublishFormProps {
  clip: Clip;
  videoUrl: string;
}

export function YouTubePublishForm({
  clip,
  videoUrl,
}: YouTubePublishFormProps) {
  const t = useTranslations("protected.myClips.youtubePublishPage");
  const router = useRouter();
  const videoRef = useRef<HTMLVideoElement>(null);
  const [loading, setLoading] = useState(false);
  const [checkingConnection, setCheckingConnection] = useState(true);
  const [connected, setConnected] = useState(false);

  // Check YouTube connection on mount
  useEffect(() => {
    getYouTubeConnection().then((data) => {
      setConnected(!!data?.connected);
      setCheckingConnection(false);
    });
  }, []);

  const form = useForm({
    initialValues: {
      title: clip.title || "",
      description: "",
      privacyStatus: "private",
      tags: "",
    },
    validate: {
      title: (value) => (!value.trim() ? t("validation.titleRequired") : null),
    },
  });

  const handleSubmit = async (values: typeof form.values) => {
    if (!clip.documentId) return;

    setLoading(true);
    const result = await shareToYouTube({
      clipDocumentId: clip.documentId,
      title: values.title,
      description: values.description,
      privacyStatus: values.privacyStatus,
      tags: values.tags
        .split(",")
        .map((t) => t.trim())
        .filter(Boolean),
    });
    setLoading(false);

    if (result.success) {
      notifications.show({
        title: t("success"),
        message: t("successMessage"),
        color: "green",
        autoClose: 5000,
      });
      router.push("/my-clips");
    } else {
      notifications.show({
        title: t("error"),
        message: result.error,
        color: "red",
      });
    }
  };

  if (checkingConnection) {
    return (
      <Stack align="center" py="xl">
        <Loader size="lg" />
        <Text c="dimmed">{t("checkingConnection")}</Text>
      </Stack>
    );
  }

  if (!connected) {
    return (
      <Stack gap="md" align="center" py="xl">
        <Alert
          icon={<IconAlertCircle size={16} />}
          color="orange"
          title={t("noYoutubeConnection.title")}
        >
          <Text size="sm">{t("noYoutubeConnection.description")}</Text>
        </Alert>
        <Group>
          <Button
            component={Link}
            href="/my-clips"
            variant="light"
            color="gray"
            leftSection={<IconArrowLeft size={18} />}
          >
            {t("cancel")}
          </Button>
          <Button component={Link} href="/settings">
            {t("noYoutubeConnection.goToSettings")}
          </Button>
        </Group>
      </Stack>
    );
  }

  return (
    <form onSubmit={form.onSubmit(handleSubmit)}>
      <Grid gutter="xl" overflow="hidden">
        <Grid.Col span={{ base: 12, md: 8 }} order={{ base: 2, sm: 1 }}>
          <Stack gap="lg">
            <TextInput
              label={t("titleLabel")}
              placeholder={t("titlePlaceholder")}
              maxLength={100}
              size="lg"
              rightSection={
                <Text size="sm" c="dimmed" pr="xs">
                  {form.values.title.length}/100
                </Text>
              }
              rightSectionWidth={60}
              withAsterisk
              {...form.getInputProps("title")}
            />

            <Textarea
              label={t("descriptionLabel")}
              placeholder={t("descriptionPlaceholder")}
              maxLength={5000}
              minRows={4}
              size="md"
              {...form.getInputProps("description")}
            />

            <Select
              label={t("privacyLabel")}
              data={[
                { value: "public", label: t("privacy.public") },
                { value: "unlisted", label: t("privacy.unlisted") },
                { value: "private", label: t("privacy.private") },
              ]}
              size="lg"
              {...form.getInputProps("privacyStatus")}
            />

            <TextInput
              label={t("tagsLabel")}
              placeholder={t("tagsPlaceholder")}
              description={t("tagsDescription")}
              size="md"
              {...form.getInputProps("tags")}
            />

            <Alert
              variant="light"
              color="yellow"
              icon={<IconAlertCircle size={16} />}
            >
              <Text size="sm">{t("quotaWarning")}</Text>
            </Alert>

            <Text size="md" c="dimmed" ta="center">
              {t("confirmationPrefix")}{" "}
              <Anchor href="/terms" target="_blank">
                {t("termsOfServiceLink")}
              </Anchor>{" "}
              {t("andText")}{" "}
              <Anchor href="https://www.youtube.com/t/terms" target="_blank">
                {t("youtubeTermsLink")}
              </Anchor>
            </Text>

            <Group grow>
              <Button
                component={Link}
                href="/my-clips"
                variant="light"
                color="gray"
                size="md"
                leftSection={<IconArrowLeft size={18} />}
              >
                {t("cancel")}
              </Button>

              <Button
                type="submit"
                loading={loading}
                size="md"
                color="red"
                leftSection={<IconBrandYoutube size={18} />}
              >
                {t("uploadButton")}
              </Button>
            </Group>
          </Stack>
        </Grid.Col>
        <Grid.Col span={{ base: 12, md: 4 }} order={{ base: 1, sm: 2 }}>
          <Card withBorder radius="md">
            <AspectRatio ratio={9 / 16}>
              <video
                ref={videoRef}
                src={videoUrl}
                controls
                playsInline
                style={{
                  width: "100%",
                  height: "100%",
                  objectFit: "cover",
                  background: "#000",
                }}
              />
            </AspectRatio>
          </Card>
        </Grid.Col>
      </Grid>
    </form>
  );
}
