import { Follower, FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { ActionIcon, Tooltip } from "@mantine/core";
import { IconWindowMaximize } from "@tabler/icons-react";

type UrlPattern = (username: string) => string;

export const SOCIAL_URL_PATTERNS: Partial<Record<FollowerTypeEnum, UrlPattern>> = {
  [FollowerTypeEnum.Tiktok]: (username) =>
    `https://www.tiktok.com/@${decodeURIComponent(username).replace(
      /^@/,
      "",
    )}/live`,
  [FollowerTypeEnum.Twitch]: (username) => `https://www.twitch.tv/${username}`,
  [FollowerTypeEnum.Kick]: (username) => `https://www.kick.com/${username}`,
  [FollowerTypeEnum.Youtube]: (username) =>
    `https://www.youtube.com/@${username}/live`,
  [FollowerTypeEnum.Afreecatv]: (username) =>
    `https://play.afreecatv.com/${username}`,
  [FollowerTypeEnum.Pandalive]: (username) =>
    `https://www.pandalive.co.kr/play/${username}`,
  [FollowerTypeEnum.Bigo]: (username) => `https://www.bigo.tv/${username}`,
  [FollowerTypeEnum.Buzzcast]: (username) =>
    `https://www.buzzcast.com/web/personalInfo/${username}`,
};

export const URL_PATTERNS: Partial<Record<FollowerTypeEnum, UrlPattern>> = {
  [FollowerTypeEnum.Tiktok]: (username) =>
    `/tiktok/@${username.replace(/^(%40|@)/, "")}`,
  [FollowerTypeEnum.Twitch]: (username) => `/twitch/${username}`,
  [FollowerTypeEnum.Kick]: (username) => `/kick/${username}`,
  [FollowerTypeEnum.Youtube]: (username) =>
    `/youtube/@${username.replace(/^(%40|@)/, "")}`,
  [FollowerTypeEnum.Afreecatv]: (username) => `/afreecatv/${username}`,
  [FollowerTypeEnum.Pandalive]: (username) => `/pandalive/${username}`,
  [FollowerTypeEnum.Bigo]: (username) => `/bigo/${username}`,
  [FollowerTypeEnum.Buzzcast]: (username) => `/buzzcast/${username}`,
};

export const getSocialUrl = (
  follower?: Partial<Pick<Follower, "username" | "type">>,
) => {
  const patternFn =
    SOCIAL_URL_PATTERNS[follower?.type || FollowerTypeEnum.Tiktok];
  return patternFn ? patternFn(follower?.username || "unknown") : "/404";
};

export const getProfileUrl = (
  follower?: Partial<Pick<Follower, "username" | "type">>,
) => {
  const patternFn = URL_PATTERNS[follower?.type || FollowerTypeEnum.Tiktok];
  return patternFn ? patternFn(follower?.username || "unknown") : "/404";
};

export default function OpenSocial({ follower }: { follower: Follower }) {
  const href = SOCIAL_URL_PATTERNS[follower.type]?.(follower.username);

  return (
    <Tooltip label={`Go to ${follower.type}`}>
      <ActionIcon component="a" size="lg" href={href} target="_blank">
        <IconWindowMaximize size={24} />
      </ActionIcon>
    </Tooltip>
  );
}
