"use client";

import { Flex, Loader, Modal } from "@mantine/core";
import { useInfiniteQuery } from "@tanstack/react-query";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { useQueryStates } from "nuqs";
import { useCallback, useMemo } from "react";

import { VideoScrollPlayer } from "@/app/[locale]/(protected)/components/video/video-scroll-player";
import { fetchFollowers } from "@/app/[locale]/(protected)/discover/actions/fetch-followers";
import { exploreParsers } from "@/app/[locale]/(protected)/discover/lib/search-params";
import { getProfileUrl } from "@/app/components/open-social";
import { Recording } from "@/lib/types/strapi-autogenerated";

export default function DiscoverRecordingModalClient() {
  const router = useRouter();
  const params = useParams<{
    id: string;
    username: string;
    type: string;
  }>();
  const searchParams = useSearchParams();
  const [filters] = useQueryStates(exploreParsers);

  const {
    data,
    fetchNextPage,
    hasNextPage,
    isFetchingNextPage,
    isLoading,
    isFetching,
  } = useInfiniteQuery({
    queryKey: ["creators", "discover", filters],
    queryFn: ({ pageParam }) => fetchFollowers(filters, pageParam),
    initialPageParam: 1,
    getNextPageParam: (lastPage) => {
      const { page = 1, pageCount = 0 } = lastPage.meta?.pagination ?? {};
      return page < pageCount ? page + 1 : undefined;
    },
  });

  // Flatten followers -> recordings, keeping follower reference
  const recordings: Recording[] = useMemo(() => {
    const followers = data?.pages.flatMap((p) => p.data) ?? [];
    return followers.flatMap((follower) =>
      (follower.recordings ?? []).map((recording) => ({
        ...recording,
        follower: {
          username: follower.username,
          type: follower.type,
          avatar: follower.avatar,
        },
      })),
    );
  }, [data]);

  const handleClose = () => {
    router.back();
  };

  const handleVisibleChange = useCallback(
    (recording: Recording) => {
      const basePath = `${getProfileUrl(recording.follower)}/video/${recording.documentId}`;
      const search = searchParams.toString();
      const url = search ? `${basePath}?${search}` : basePath;
      window.history.replaceState(null, "", url);
    },
    [searchParams],
  );

  const handleNotFound = () => {
    router.replace("/discover");
  };

  const videoExists = recordings.some((r) => r.documentId === params.id);

  if (isLoading || (isFetching && !videoExists)) {
    return (
      <Modal.Root opened={true} onClose={handleClose} fullScreen>
        <Modal.Content>
          <Flex h="100dvh" justify="center" align="center">
            <Loader size="lg" />
          </Flex>
        </Modal.Content>
      </Modal.Root>
    );
  }

  return (
    <Modal.Root
      opened={true}
      onClose={handleClose}
      fullScreen
      styles={{
        body: { height: "100%", padding: 0, overflow: "hidden" },
        content: { overflow: "hidden" },
      }}
    >
      <Modal.Content>
        <Modal.Body p={0} h="100%">
          <VideoScrollPlayer
            recordings={recordings}
            initialId={params.id}
            hasNextPage={hasNextPage}
            isFetchingNextPage={isFetchingNextPage}
            onFetchNextPage={fetchNextPage}
            onVisibleChange={handleVisibleChange}
            onClose={handleClose}
            onNotFound={handleNotFound}
          />
        </Modal.Body>
      </Modal.Content>
    </Modal.Root>
  );
}
