import publicApi from "@/lib/public-api";
import { FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import { unstable_cache } from "next/cache";

const REVALIDATE = 3600;

export const getFollowerFilters = unstable_cache(
  async (type?: FollowerTypeEnum) => {
    const { data: filtersData } = await publicApi.follower.getFollowerFilters(
      type ? { type } : { type: undefined },
    );
    return {
      genders: (filtersData.genders ?? [])
        .filter((g) => g.value)
        .map((g) => ({
          value: g.value || "",
          label: `${g.value} (${g.count})`,
        })),
      countryCodes: (filtersData.countryCodes ?? [])
        .filter((c) => c.value !== "-")
        .map((c) => ({
          value: c.value || "",
          label: `${c.value} (${c.count})`,
        })),
      types: (filtersData.types ?? []).map((l) => ({
        value: l.value || "",
        label: `${l.value} (${l.count})`,
      })),
      languageCodes: (filtersData.languageCodes ?? []).map((l) => ({
        value: l.value || "",
        label: `${l.value} (${l.count})`,
      })),
    };
  },
  ["creator-follower-filters"],
  { revalidate: REVALIDATE },
);

export const getCreators = unstable_cache(
  async (type: string, page: number) => {
    const {
      data: { data: followers, meta },
    } = await publicApi.follower.getFollowers({
      ...(type === "all" ? {} : { filters: { type } }),
      "pagination[pageSize]": 20,
      "pagination[page]": page,
      sort: "createdAt:desc",
      populate: { avatar: true },
    });
    return { followers: followers ?? [], meta };
  },
  ["creators"],
  { revalidate: REVALIDATE },
);

export const getCreatorsByCountry = unstable_cache(
  async (type: string, countryCode: string, page: number) => {
    const {
      data: { data: followers, meta },
    } = await publicApi.follower.getFollowers({
      filters: {
        ...(type === "all" ? {} : { type }),
        countryCode,
      },
      "pagination[pageSize]": 20,
      "pagination[page]": page,
      sort: "createdAt:desc",
      populate: { avatar: true },
    });
    return { followers: followers ?? [], meta };
  },
  ["creators-by-country"],
  { revalidate: REVALIDATE },
);
