"use server";

import api from "@/lib/api";
import { ProviderEnum } from "@/lib/types/strapi-autogenerated";

export async function getTikTokConnection() {
  try {
    const response = await api.socialAccount.meGetSocialAccounts({
      provider: ProviderEnum.Tiktok,
    });
    const data = response.data?.data;
    if (!data?.length) return null;

    return {
      documentId: data[0].documentId!,
      connected: true,
    };
  } catch {
    return null;
  }
}

export async function disconnectTikTok(id: string) {
  try {
    const response = await api.socialAccount.meGetSocialAccounts({
      provider: ProviderEnum.Tiktok,
    });
    const tiktokData = response.data?.data?.[0];

    if (tiktokData?.accessToken) {
      await fetch("https://open.tiktokapis.com/v2/oauth/revoke/", {
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
        },
        body: new URLSearchParams({
          token: tiktokData.accessToken,
          client_key: process.env.TIKTOK_CLIENT_KEY!,
          client_secret: process.env.TIKTOK_CLIENT_SECRET!,
        }),
      });
    }

    await api.socialAccount.meDeleteSocialAccountsId({ id });
    return { success: true };
  } catch (error) {
    console.error("Error disconnecting TikTok:", error);
    return { success: false, error: "Failed to disconnect TikTok" };
  }
}
