"use server";

import api from "@/lib/api";
import { ProviderEnum } from "@/lib/types/strapi-autogenerated";

export async function getYouTubeConnection() {
  try {
    const response = await api.socialAccount.meGetSocialAccounts({
      provider: "youtube" as ProviderEnum,
    });
    const data = response.data?.data;
    if (!data?.length) return null;

    return {
      documentId: data[0].documentId!,
      connected: true,
    };
  } catch {
    return null;
  }
}

export async function disconnectYouTube(id: string) {
  try {
    const response = await api.socialAccount.meGetSocialAccounts({
      provider: "youtube" as ProviderEnum,
    });
    const youtubeData = response.data?.data?.[0];

    // Revoke Google token
    if (youtubeData?.accessToken) {
      await fetch(
        `https://oauth2.googleapis.com/revoke?token=${youtubeData.accessToken}`,
        { method: "POST" },
      );
    }

    await api.socialAccount.meDeleteSocialAccountsId({ id });
    return { success: true };
  } catch (error) {
    console.error("Error disconnecting YouTube:", error);
    return { success: false, error: "Failed to disconnect YouTube" };
  }
}
