"use client";

import { getRandomClip } from "@/app/actions/clip";
import { getClipUrl } from "@/app/lib/clip-url";
import { getProfileUrl } from "@/app/components/open-social";
import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { Clip } from "@/lib/types/strapi-autogenerated";
import {
  ActionIcon,
  Avatar,
  Box,
  Card,
  Center,
  Flex,
  Group,
  Loader,
  Stack,
  Text,
} from "@mantine/core";
import {
  IconChevronDown,
  IconChevronUp,
  IconMessage,
  IconMessageOff,
  IconPlayerPause,
  IconPlayerPlay,
  IconVolume,
  IconVolumeOff,
} from "@tabler/icons-react";
import { useLocale } from "next-intl";
import Image from "next/image";
import Link from "@/app/components/link";
import { useCallback, useEffect, useRef, useState, useTransition } from "react";
import "./clips-viewer.css";

interface ClipCardProps {
  clip: Clip;
  isActive: boolean;
}

function ClipCard({ clip, isActive }: ClipCardProps) {
  const locale = useLocale();
  const videoRef = useRef<HTMLVideoElement>(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [isMuted, setIsMuted] = useState(false);
  const [progress, setProgress] = useState(0);
  const [showSubtitles, setShowSubtitles] = useState(true);
  const [isLoading, setIsLoading] = useState(true);

  // Control play/pause based on isActive
  useEffect(() => {
    if (!videoRef.current) return;

    if (isActive) {
      videoRef.current.play().catch(() => {});
    } else {
      videoRef.current.pause();
      videoRef.current.currentTime = 0;
      setIsLoading(true);
    }
  }, [isActive]);

  // Listen to video events to track playing state, progress, and loading
  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;

    const onPlay = () => setIsPlaying(true);
    const onPause = () => setIsPlaying(false);
    const onTimeUpdate = () => {
      if (video.duration) {
        setProgress((video.currentTime / video.duration) * 100);
      }
    };
    const onWaiting = () => setIsLoading(true);
    const onCanPlay = () => setIsLoading(false);
    const onPlaying = () => setIsLoading(false);

    video.addEventListener("play", onPlay);
    video.addEventListener("pause", onPause);
    video.addEventListener("timeupdate", onTimeUpdate);
    video.addEventListener("waiting", onWaiting);
    video.addEventListener("canplay", onCanPlay);
    video.addEventListener("playing", onPlaying);

    return () => {
      video.removeEventListener("play", onPlay);
      video.removeEventListener("pause", onPause);
      video.removeEventListener("timeupdate", onTimeUpdate);
      video.removeEventListener("waiting", onWaiting);
      video.removeEventListener("canplay", onCanPlay);
      video.removeEventListener("playing", onPlaying);
    };
  }, []);

  // Handle subtitles toggle
  useEffect(() => {
    const video = videoRef.current;
    if (!video || !video.textTracks[0]) return;
    video.textTracks[0].mode = showSubtitles ? "showing" : "hidden";
  }, [showSubtitles]);

  const togglePlay = () => {
    if (!videoRef.current) return;
    if (isPlaying) {
      videoRef.current.pause();
    } else {
      videoRef.current.play();
    }
  };

  const toggleMute = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (!videoRef.current) return;
    videoRef.current.muted = !videoRef.current.muted;
    setIsMuted(!isMuted);
  };

  const toggleSubtitles = (e: React.MouseEvent) => {
    e.stopPropagation();
    setShowSubtitles(!showSubtitles);
  };

  const handleProgressClick = (e: React.MouseEvent<HTMLDivElement>) => {
    e.stopPropagation();
    if (!videoRef.current) return;
    const rect = e.currentTarget.getBoundingClientRect();
    const percent = (e.clientX - rect.left) / rect.width;
    videoRef.current.currentTime = percent * videoRef.current.duration;
  };

  return (
    <Flex
      pos="relative"
      w="100%"
      h="100%"
      justify="center"
      style={{
        scrollSnapAlign: "start",
        scrollSnapStop: "always",
        flexShrink: 0,
        overflow: "hidden",
      }}
    >
      <Card
        bg="black"
        pos="relative"
        miw={{ base: "100%", sm: "480px" }}
        radius="lg"
        p="0"
        m="0"
        onClick={togglePlay}
        style={{ cursor: "pointer" }}
      >
        <video
          ref={videoRef}
          src={getClipUrl(clip.documentId!, "clip.mp4", clip.path)}
          poster={getClipUrl(clip.documentId!, "thumbnail.jpg", clip.path)}
          loop
          muted={isMuted}
          playsInline
          preload={isActive ? "auto" : "metadata"}
          style={{
            width: "100%",
            height: "100%",
            objectFit: "contain",
          }}
        >
          <track
            kind="subtitles"
            src={`/clip/${clip.documentId}/subtitles.vtt?locale=${locale}`}
            srcLang="en"
            label="Subtitles"
            default
          />
        </video>

        {/* Loading indicator */}
        {isActive && isLoading && (
          <Center
            pos="absolute"
            top={0}
            left={0}
            right={0}
            bottom={0}
            style={{ pointerEvents: "none" }}
          >
            <Loader color="white" size="lg" />
          </Center>
        )}
      </Card>

      {/* Play/Pause overlay */}
      <Center
        pos="absolute"
        top={0}
        left={0}
        right={0}
        bottom={0}
        c="rgba(255,255,255,0.9)"
        style={{
          opacity: isPlaying || isLoading ? 0 : 1,
          transition: "opacity 0.2s",
          pointerEvents: "none",
        }}
      >
        {isPlaying ? (
          <IconPlayerPause size={64} stroke={1.5} />
        ) : (
          <IconPlayerPlay size={64} stroke={1.5} />
        )}
      </Center>

      {/* Controls at bottom */}
      <Box pos="absolute" bottom={0} left={0} right={0} p="md">
        {/* Progress bar */}
        <Box
          h={4}
          bg="rgba(255,255,255,0.3)"
          style={{ borderRadius: 2, cursor: "pointer" }}
          onClick={handleProgressClick}
          mb="sm"
        >
          <Box
            h="100%"
            bg="white"
            style={{
              borderRadius: 2,
              width: `${progress}%`,
              transition: "width 0.1s",
            }}
          />
        </Box>

        {/* Controls row */}
        <Group justify="space-between" align="center">
          <Link
            href={getProfileUrl(clip.follower as never)}
            style={{ textDecoration: "none" }}
          >
            <Group gap="sm">
              <Avatar size={36} radius="xl" color="blue">
                {clip.follower?.avatar?.url && (
                  <Image
                    src={generateAvatarUrl(clip.follower?.avatar?.url)}
                    alt={"Avatar"}
                    width={38}
                    height={38}
                  />
                )}
              </Avatar>
              <Box>
                <Text fw={600} size="sm" c="white">
                  {clip.follower?.nickname}
                </Text>
                {clip.title && (
                  <Text size="xs" c="dimmed" lineClamp={1}>
                    {clip.title}
                  </Text>
                )}
              </Box>
            </Group>
          </Link>

          {/* Right side - controls */}
          <Group gap="xs">
            <ActionIcon
              variant="subtle"
              color="white"
              size={32}
              onClick={toggleSubtitles}
            >
              {showSubtitles ? (
                <IconMessage size={18} />
              ) : (
                <IconMessageOff size={18} />
              )}
            </ActionIcon>
            <ActionIcon
              variant="subtle"
              color="white"
              size={32}
              onClick={toggleMute}
            >
              {isMuted ? <IconVolumeOff size={18} /> : <IconVolume size={18} />}
            </ActionIcon>
          </Group>
        </Group>
      </Box>
    </Flex>
  );
}

interface ClipsViewerProps {
  initialClips: Clip[];
}

export function ClipsViewer({ initialClips }: ClipsViewerProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [clips, setClips] = useState<Clip[]>(initialClips);
  const [activeIndex, setActiveIndex] = useState(0);
  const [isPending, startTransition] = useTransition();
  const loadingRef = useRef(false);

  const prefetchNext = useCallback(async () => {
    if (loadingRef.current) return;
    loadingRef.current = true;

    startTransition(async () => {
      const newClip = await getRandomClip();
      if (newClip) {
        setClips((prev) => [...prev, newClip]);
      }
      loadingRef.current = false;
    });
  }, []);

  useEffect(() => {
    if (activeIndex >= clips.length - 2) {
      prefetchNext();
    }
  }, [activeIndex, clips.length, prefetchNext]);

  const scrollToIndex = useCallback(
    (index: number) => {
      if (!containerRef.current) return;
      const clampedIndex = Math.max(0, Math.min(index, clips.length - 1));
      const clipHeight = containerRef.current.clientHeight;
      containerRef.current.scrollTo({
        top: clampedIndex * clipHeight,
        behavior: "smooth",
      });
    },
    [clips.length],
  );

  const handleScroll = useCallback(() => {
    if (!containerRef.current) return;
    const { scrollTop, clientHeight } = containerRef.current;
    const newIndex = Math.round(scrollTop / clientHeight);
    if (newIndex !== activeIndex) {
      setActiveIndex(newIndex);

      // Update URL to current clip (preserve locale from current path)
      const currentClip = clips[newIndex];
      if (currentClip) {
        const pathname = window.location.pathname;
        const shortsIndex = pathname.indexOf("/shorts");
        const basePath = pathname.substring(0, shortsIndex);
        window.history.replaceState(
          null,
          "",
          `${basePath}/shorts/${currentClip.documentId}`,
        );
      }
    }
  }, [activeIndex, clips]);

  const goUp = useCallback(
    () => scrollToIndex(activeIndex - 1),
    [activeIndex, scrollToIndex],
  );
  const goDown = useCallback(
    () => scrollToIndex(activeIndex + 1),
    [activeIndex, scrollToIndex],
  );

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "ArrowUp") {
        e.preventDefault();
        goUp();
      } else if (e.key === "ArrowDown") {
        e.preventDefault();
        goDown();
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [goDown, goUp]);

  useEffect(() => {
    const currentClip = clips[0];
    if (currentClip) {
      const pathname = window.location.pathname;
      const shortsIndex = pathname.indexOf("/shorts");
      const basePath = pathname.substring(0, shortsIndex);
      window.history.replaceState(
        null,
        "",
        `${basePath}/shorts/${currentClip.documentId}`,
      );
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <Box
      pos="relative"
      w="100%"
      h="calc(100dvh - 60px)"
      style={{ overflow: "hidden" }}
    >
      <Box
        ref={containerRef}
        onScroll={handleScroll}
        className="clips-container"
        w="100%"
        h="100%"
        style={{
          overflowY: "scroll",
          scrollSnapType: "y mandatory",
          scrollBehavior: "smooth",
          scrollbarWidth: "none",
          msOverflowStyle: "none",
        }}
      >
        {clips.map((clip, index) => (
          <ClipCard
            key={`${clip.id}-${index}`}
            clip={clip}
            isActive={index === activeIndex}
          />
        ))}

        {isPending && (
          <Center h={100} w="100%">
            <Loader color="white" size="sm" />
          </Center>
        )}
      </Box>

      {/* Navigation buttons */}
      <Stack
        pos="absolute"
        right={24}
        top="50%"
        gap="xs"
        style={{ transform: "translateY(-50%)", zIndex: 100 }}
      >
        <ActionIcon
          variant="filled"
          size={44}
          radius="xl"
          onClick={goUp}
          disabled={activeIndex === 0}
          bg="rgba(30,30,30,0.9)"
          c="white"
          style={{
            backdropFilter: "blur(10px)",
            border: "1px solid rgba(255,255,255,0.1)",
          }}
        >
          <IconChevronUp size={24} />
        </ActionIcon>
        <ActionIcon
          variant="filled"
          size={44}
          radius="xl"
          onClick={goDown}
          bg="rgba(30,30,30,0.9)"
          c="white"
          style={{
            backdropFilter: "blur(10px)",
            border: "1px solid rgba(255,255,255,0.1)",
          }}
        >
          <IconChevronDown size={24} />
        </ActionIcon>
      </Stack>
    </Box>
  );
}
