"use server";

import analyticsApi from "@/lib/analytics-api";
import {
  Battle,
  DailyEarnings,
  Opponent,
  ScheduleDay,
  StreamerStats,
  StreamSession,
  TopGifter,
} from "@/lib/types/analytics-autogenerated";

export type BattlesPage = {
  data: Battle[];
  total: number;
  hasMore: boolean;
};

export type ActivityPage = {
  data: StreamSession[];
  total: number;
  hasMore: boolean;
};

export async function getStreamerStats(
  username: string,
): Promise<StreamerStats | null> {
  try {
    const res = await analyticsApi.streamer.getStreamerStats({ username });
    return res.data;
  } catch {
    return null;
  }
}

export async function getStreamerEarnings(
  username: string,
): Promise<DailyEarnings[]> {
  try {
    const res = await analyticsApi.streamer.getStreamerEarnings({ username });
    return res.data;
  } catch {
    return [];
  }
}

export async function getStreamerTopGifters(
  username: string,
): Promise<TopGifter[]> {
  try {
    const res = await analyticsApi.streamer.getStreamerTopGifters({ username });
    return res.data;
  } catch {
    return [];
  }
}

export async function getStreamerBattles(
  username: string,
  limit = 10,
  offset = 0,
): Promise<BattlesPage> {
  try {
    const res = await analyticsApi.streamer.getStreamerBattles({
      username,
      limit,
      offset,
    });
    return {
      data: res.data.data ?? [],
      total: res.data.total,
      hasMore: res.data.hasMore,
    };
  } catch {
    return { data: [], total: 0, hasMore: false };
  }
}

export async function getStreamerTopOpponents(
  username: string,
  limit = 10,
  offset = 0,
): Promise<Opponent[]> {
  try {
    const res = await analyticsApi.streamer.getStreamerTopOpponents({
      username,
      limit,
      offset,
    });
    return res.data.data ?? [];
  } catch {
    return [];
  }
}

export async function getStreamerActivity(
  username: string,
  limit = 20,
  offset = 0,
): Promise<ActivityPage> {
  try {
    const res = await analyticsApi.streamer.getStreamerActivity({
      username,
      limit,
      offset,
    });
    return {
      data: res.data.data ?? [],
      total: res.data.total,
      hasMore: res.data.hasMore,
    };
  } catch {
    return { data: [], total: 0, hasMore: false };
  }
}

export async function getStreamerSchedule(
  username: string,
): Promise<ScheduleDay[]> {
  try {
    const res = await analyticsApi.streamer.getStreamerSchedule({ username });
    return res.data;
  } catch {
    return [];
  }
}
