"use server";

import { setToken } from "@/lib/token";
import { Api } from "@/lib/types/strapi-autogenerated";
import { getLocale } from "next-intl/server";
import { redirect } from "next/navigation";
import validator from "validator";

const api = new Api({
  baseURL: (process.env.STRAPI_URL || "http://localhost:1337") + "/api",
});

export async function login(prevState: any, formData: FormData) {
  const identifier = formData.get("email") as string;
  const password = formData.get("password") as string;

  try {
    const { data } = await api.usersPermissionsAuth.localCreate({
      identifier,
      password,
    });

    await setToken(data.jwt!);
  } catch (err: any) {
    return { error: err.response?.data?.error?.message || "Login failed" };
  }

  redirect("/dashboard");
}

export async function register(prevState: any, formData: FormData) {
  const username = formData.get("username") as string;
  const email =
    validator.normalizeEmail(formData.get("email") as string, {
      gmail_remove_dots: false,
    }) || "";
  const password = formData.get("password") as string;
  const locale = await getLocale();

  try {
    const response = await fetch(
      `${process.env.STRAPI_URL || "http://localhost:1337"}/api/auth/local/register?locale=${locale}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ username, email, password }),
      },
    );

    if (!response.ok) {
      const data = await response.json();
      return {
        error: data?.error?.message || "Registration failed",
      };
    }
  } catch {
    return {
      error: "Unable to connect to server",
    };
  }

  return { success: true };
}

export async function forgotPassword(prevState: unknown, formData: FormData) {
  const email = formData.get("email") as string;
  const locale = await getLocale();

  try {
    const response = await fetch(
      `${process.env.STRAPI_URL}/api/auth/forgot-password?locale=${locale}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ email }),
      },
    );

    if (!response.ok) {
      const data = await response.json();
      return {
        success: false,
        error: data?.error?.message || "Something went wrong",
      };
    }

    return { success: true };
  } catch (error) {
    return {
      success: false,
      error: "Unable to connect to server",
    };
  }
}

export async function resetPassword(prevState: unknown, formData: FormData) {
  const password = formData.get("password") as string;
  const passwordConfirmation = formData.get("passwordConfirmation") as string;
  const code = formData.get("code") as string;

  if (password !== passwordConfirmation) {
    return {
      success: false,
      error: "Passwords do not match",
    };
  }

  try {
    const response = await fetch(
      `${process.env.STRAPI_URL}/api/auth/reset-password`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          code,
          password,
          passwordConfirmation,
        }),
      },
    );

    if (!response.ok) {
      const data = await response.json();
      return {
        success: false,
        error: data?.error?.message || "Something went wrong",
      };
    }

    return { success: true };
  } catch (error) {
    return {
      success: false,
      error: "Unable to connect to server",
    };
  }
}
