"use client";

import { Flex, Loader, Modal } from "@mantine/core";
import { useInfiniteQuery } from "@tanstack/react-query";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { useQueryStates } from "nuqs";
import { useMemo } from "react";

import { VideoScrollPlayer } from "@/app/[locale]/(protected)/components/video/video-scroll-player";
import { fetchProfileRecordings } from "@/app/[locale]/(protected)/protected/[type]/[username]/actions/actions";
import { profileParsers } from "@/app/[locale]/(protected)/protected/[type]/[username]/lib/search-params";
import { getProfileUrl } from "@/app/components/open-social";
import { FollowerTypeEnum, Recording } from "@/lib/types/strapi-autogenerated";

export default function ProfileRecordingModalClient() {
  const router = useRouter();
  const { id, username, type } = useParams<{
    id: string;
    username: string;
    type: FollowerTypeEnum;
  }>();

  const searchParams = useSearchParams();
  const [filters] = useQueryStates(profileParsers);

  const {
    data,
    fetchNextPage,
    hasNextPage,
    isFetchingNextPage,
    isLoading,
    isFetching,
  } = useInfiniteQuery({
    queryKey: ["profile-recordings", type, username, filters],
    queryFn: ({ pageParam }) =>
      fetchProfileRecordings(type, username, filters, pageParam),
    initialPageParam: 1,
    getNextPageParam: (lastPage) => {
      const { page = 1, pageCount = 0 } = lastPage.meta?.pagination ?? {};
      return page < pageCount ? page + 1 : undefined;
    },
  });

  const recordings = useMemo(
    () => data?.pages.flatMap((p) => p.data) ?? [],
    [data],
  );

  const handleClose = () => {
    router.back();
  };

  const handleVisibleChange = (recording: Recording) => {
    const basePath = `${getProfileUrl({ type, username })}/video/${recording.documentId}`;
    const search = searchParams.toString();
    const url = search ? `${basePath}?${search}` : basePath;
    window.history.replaceState(null, "", url);
  };

  const handleNotFound = () => {
    router.replace(`/${type}/${decodeURIComponent(username)}`);
  };

  const videoExists = recordings.some((r) => r.documentId === id);

  if (isLoading || (isFetching && !videoExists)) {
    return (
      <Modal.Root opened={true} onClose={handleClose} fullScreen>
        <Modal.Content>
          <Flex h="100dvh" justify="center" align="center">
            <Loader size="lg" />
          </Flex>
        </Modal.Content>
      </Modal.Root>
    );
  }

  return (
    <Modal.Root
      opened={true}
      onClose={handleClose}
      fullScreen
      styles={{
        body: { height: "100%", padding: 0, overflow: "hidden" },
        content: { overflow: "hidden" },
      }}
    >
      <Modal.Content>
        <Modal.Body p={0} h="100%">
          <VideoScrollPlayer
            recordings={recordings}
            initialId={id}
            hasNextPage={hasNextPage}
            isFetchingNextPage={isFetchingNextPage}
            onFetchNextPage={fetchNextPage}
            onVisibleChange={handleVisibleChange}
            onClose={handleClose}
            onNotFound={handleNotFound}
            showCloseButton={true}
            height="100dvh"
          />
        </Modal.Body>
      </Modal.Content>
    </Modal.Root>
  );
}
