"use client";

import type { HlsVideoElement } from "hls-video-element";
import { checkVideoAccess } from "@/app/actions/video-access";
import { VideoUpgradeModal } from "@/app/[locale]/(protected)/components/video-upgrade-modal";
import { VideoScrollPlayer } from "@/app/[locale]/(protected)/components/video/video-scroll-player";
import { fetchProfileRecordings } from "@/app/[locale]/(protected)/protected/[type]/[username]/actions/actions";
import { profileParsers } from "@/app/[locale]/(protected)/protected/[type]/[username]/lib/search-params";
import { getProfileUrl } from "@/app/components/open-social";
import { FollowerTypeEnum, Recording } from "@/lib/types/strapi-autogenerated";
import { Flex, Loader, Modal } from "@mantine/core";
import { useInfiniteQuery, useQuery } from "@tanstack/react-query";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { useQueryStates } from "nuqs";
import { useCallback, useMemo, useState } from "react";

export default function ProfileRecordingModalClient() {
  const router = useRouter();
  const { id, username, type } = useParams<{
    id: string;
    username: string;
    type: FollowerTypeEnum;
  }>();

  const [currentVideoId, setCurrentVideoId] = useState(id);
  const searchParams = useSearchParams();
  const [filters] = useQueryStates(profileParsers);

  const { data: access, isLoading: isAccessLoading } = useQuery({
    queryKey: ["video-access", currentVideoId],
    queryFn: () => checkVideoAccess(currentVideoId),
  });

  const {
    data,
    fetchNextPage,
    hasNextPage,
    isFetchingNextPage,
    isLoading,
    isFetching,
  } = useInfiniteQuery({
    queryKey: ["profile-recordings", type, username, filters],
    queryFn: ({ pageParam }) =>
      fetchProfileRecordings(type, username, filters, pageParam),
    initialPageParam: 1,
    getNextPageParam: (lastPage) => {
      const { page = 1, pageSize } = lastPage.meta?.pagination ?? {};
      return lastPage.data.length === pageSize ? page + 1 : undefined;
    },
  });

  const recordings = useMemo(
    () => data?.pages.flatMap((p) => p.data) ?? [],
    [data],
  );

  const handleClose = () => {
    document.querySelectorAll<HlsVideoElement>("hls-video").forEach((el) => {
      el.pause();
      if (el.api) {
        el.api.stopLoad();
        el.api.detachMedia();
        el.api.destroy();
        el.api = null;
      }
    });
    setTimeout(() => router.back(), 50);
  };

  const handleVisibleChange = useCallback((recording: Recording) => {
    setCurrentVideoId(recording.documentId!);
    const basePath = `${getProfileUrl({ type, username })}/video/${recording.documentId}`;
    const search = searchParams.toString();
    const url = search ? `${basePath}?${search}` : basePath;
    window.history.replaceState(null, "", url);
  }, [type, username, searchParams]);

  const handleNotFound = () => {
    router.replace(`/${type}/${decodeURIComponent(username)}`);
  };

  const videoExists = recordings.some((r) => r.documentId === id);

  // Only block on access loading for the initial video.
  // After scrolling, currentVideoId changes — don't unmount the player
  // or it will remount with the original initialId and jump back.
  const isInitialAccessLoading = isAccessLoading && currentVideoId === id;

  if (isLoading || isInitialAccessLoading || (isFetching && !videoExists)) {
    return (
      <Modal.Root opened={true} onClose={handleClose} fullScreen>
        <Modal.Content>
          <Flex h="100dvh" justify="center" align="center">
            <Loader size="lg" />
          </Flex>
        </Modal.Content>
      </Modal.Root>
    );
  }

  if (access && !access.allowed) {
    return <VideoUpgradeModal opened={true} onClose={handleClose} />;
  }

  return (
    <Modal.Root
      opened={true}
      onClose={handleClose}
      fullScreen
      styles={{
        body: { height: "100%", padding: 0, overflow: "hidden" },
        content: { overflow: "hidden" },
      }}
    >
      <Modal.Content>
        <Modal.Body p={0} h="100%">
          <VideoScrollPlayer
            recordings={recordings}
            initialId={id}
            hasNextPage={hasNextPage}
            isFetchingNextPage={isFetchingNextPage}
            onFetchNextPage={fetchNextPage}
            onVisibleChange={handleVisibleChange}
            onClose={handleClose}
            onNotFound={handleNotFound}
            showCloseButton={true}
            height="100dvh"
          />
        </Modal.Body>
      </Modal.Content>
    </Modal.Root>
  );
}
