"use client";

import { useIntlNames } from "@/app/[locale]/(protected)/hooks/use-intl-names";
import { CountryEntry } from "@/lib/types/analytics-autogenerated";
import {
  Badge,
  Box,
  Button,
  Group,
  Image,
  Paper,
  Table,
  TableScrollContainer,
  TableTbody,
  TableTd,
  TableTh,
  TableThead,
  TableTr,
  Text,
  Title,
} from "@mantine/core";
import { useTranslations } from "next-intl";
import { use, useState } from "react";

const INITIAL_VISIBLE = 10;
import { formatCompact } from "../lib";

const FlagIcon = ({ code, size = 20 }: { code: string; size?: number }) => (
  <Image
    src={`https://flagcdn.com/w40/${code.toLowerCase()}.png`}
    alt={code}
    w={size}
    h={Math.round(size * 0.75)}
    radius={2}
    fit="cover"
  />
);

interface CountryLeaderboardProps {
  dataPromise: Promise<CountryEntry[]>;
}

export function CountryLeaderboard({ dataPromise }: CountryLeaderboardProps) {
  const t = useTranslations("protected.tiktokInsights");
  const { getCountryName } = useIntlNames();
  const entries = use(dataPromise);
  const [visible, setVisible] = useState(INITIAL_VISIBLE);

  const header = (
    <Box
      style={{
        background: "linear-gradient(150deg, #FFD4E8, #E852A0)",
        borderTopLeftRadius: 8,
        borderTopRightRadius: 8,
      }}
      p="md"
    >
      <Title order={5} c="black">
        {t("countryLeaderboard.title")}
      </Title>
    </Box>
  );

  if (!entries.length) {
    return (
      <Paper withBorder radius="md">
        {header}
        <Box p="md">
          <Text c="dimmed" size="sm">{t("countryLeaderboard.empty")}</Text>
        </Box>
      </Paper>
    );
  }

  return (
    <Paper withBorder radius="md">
      {header}
      <TableScrollContainer minWidth={800}>
        <Table striped highlightOnHover fz="sm">
          <TableThead>
            <TableTr>
              <TableTh>{t("countryLeaderboard.rank")}</TableTh>
              <TableTh>{t("countryLeaderboard.country")}</TableTh>
              <TableTh>{t("countryLeaderboard.diamonds")}</TableTh>
              <TableTh>{t("countryLeaderboard.gifts")}</TableTh>
              <TableTh>{t("countryLeaderboard.streamers")}</TableTh>
              <TableTh>{t("countryLeaderboard.gifters")}</TableTh>
            </TableTr>
          </TableThead>
          <TableTbody>
            {entries.slice(0, visible).map((entry, i) => (
              <TableTr key={entry.country ?? i}>
                <TableTd>
                  <Text size="sm" c="dimmed">{i + 1}</Text>
                </TableTd>
                <TableTd>
                  {entry.country ? (
                    <Group gap={8} wrap="nowrap">
                      <FlagIcon code={entry.country} size={20} />
                      <Text size="sm" fw={500}>{getCountryName(entry.country)}</Text>
                    </Group>
                  ) : (
                    <Text size="sm" c="dimmed">—</Text>
                  )}
                </TableTd>
                <TableTd>
                  <Badge color="yellow" variant="light" size="sm">
                    {formatCompact(entry.diamonds ?? 0)}
                  </Badge>
                </TableTd>
                <TableTd>
                  <Text size="sm">{formatCompact(entry.gifts ?? 0)}</Text>
                </TableTd>
                <TableTd>
                  <Text size="sm">{entry.streamers ?? 0}</Text>
                </TableTd>
                <TableTd>
                  <Text size="sm">{formatCompact(entry.unique_gifters ?? 0)}</Text>
                </TableTd>
              </TableTr>
            ))}
          </TableTbody>
        </Table>
      </TableScrollContainer>
      {visible < entries.length && (
        <Box p="md" style={{ display: "flex", justifyContent: "center" }}>
          <Button
            variant="subtle"
            size="sm"
            onClick={() => setVisible((v) => Math.min(v + INITIAL_VISIBLE, entries.length))}
          >
            {t("countryLeaderboard.loadMore")} ({entries.length - visible})
          </Button>
        </Box>
      )}
    </Paper>
  );
}
