"use client";

import { useIntlNames } from "@/app/[locale]/(protected)/hooks/use-intl-names";
import { DailyStats } from "@/lib/types/analytics-autogenerated";
import { AreaChart } from "@mantine/charts";
import {
  Badge,
  Box,
  Group,
  Image,
  LoadingOverlay,
  Paper,
  Select,
  SelectProps,
  Title,
} from "@mantine/core";
import { useTranslations } from "next-intl";
import { use, useState, useTransition } from "react";
import { getGlobalDailyEarnings } from "../actions";

const FlagIcon = ({ code, size = 20 }: { code: string; size?: number }) => (
  <Image
    src={`https://flagcdn.com/w40/${code.toLowerCase()}.png`}
    alt={code}
    w={size}
    h={Math.round(size * 0.75)}
    radius={2}
    fit="cover"
  />
);

interface DailyEarningsChartProps {
  earningsPromise: Promise<DailyStats[]>;
  countriesPromise: Promise<string[]>;
  languagesPromise: Promise<string[]>;
}

export function DailyEarningsChart({
  earningsPromise,
  countriesPromise,
  languagesPromise,
}: DailyEarningsChartProps) {
  const t = useTranslations("protected.tiktokInsights");
  const { getCountryName, getLanguageName } = useIntlNames();
  const initialEarnings = use(earningsPromise);
  const countries = use(countriesPromise);
  const languages = use(languagesPromise);

  const [earnings, setEarnings] = useState<DailyStats[]>(initialEarnings);
  const [country, setCountry] = useState<string | null>(null);
  const [language, setLanguage] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  const handleFilterChange = (newCountry: string | null, newLanguage: string | null) => {
    startTransition(async () => {
      const result = await getGlobalDailyEarnings(
        newCountry ?? undefined,
        newLanguage ?? undefined,
      );
      setEarnings(result);
    });
  };

  const countryOptions = [
    { value: "", label: t("dailyEarnings.allCountries") },
    ...countries.map((c) => ({ value: c, label: getCountryName(c) })),
  ];

  const languageOptions = [
    { value: "", label: t("dailyEarnings.allLanguages") },
    ...languages.map((l) => ({ value: l, label: getLanguageName(l) })),
  ];

  const renderCountryOption: SelectProps["renderOption"] = ({ option }) =>
    option.value === "" ? (
      <span>{option.label}</span>
    ) : (
      <Group gap="sm">
        <FlagIcon code={option.value} size={18} />
        <span>{option.label}</span>
      </Group>
    );

  const renderLanguageOption: SelectProps["renderOption"] = ({ option }) =>
    option.value === "" ? (
      <span>{option.label}</span>
    ) : (
      <Group gap="sm">
        <Badge size="xs" variant="light" tt="uppercase" w={36}>
          {option.value}
        </Badge>
        <span>{option.label}</span>
      </Group>
    );

  const data = [...earnings].reverse().map((e) => ({
    date: e.date ?? "",
    diamonds: e.diamonds ?? 0,
  }));

  const header = (
    <Box
      style={{
        background: "linear-gradient(150deg, #FFFDB4, #E8C252)",
        borderTopLeftRadius: 8,
        borderTopRightRadius: 8,
      }}
      p="md"
    >
      <Group justify="space-between" wrap="wrap" gap="xs">
        <Title order={5} c="black">
          {t("dailyEarnings.title")}
        </Title>
        <Group gap="xs" wrap="nowrap">
          <Select
            size="xs"
            data={countryOptions}
            value={country ?? ""}
            onChange={(val) => {
              const newCountry = val || null;
              setCountry(newCountry);
              handleFilterChange(newCountry, language);
            }}
            renderOption={renderCountryOption}
            styles={{ input: { minWidth: 140 } }}
            comboboxProps={{ withinPortal: true }}
            searchable
          />
          <Select
            size="xs"
            data={languageOptions}
            value={language ?? ""}
            onChange={(val) => {
              const newLanguage = val || null;
              setLanguage(newLanguage);
              handleFilterChange(country, newLanguage);
            }}
            renderOption={renderLanguageOption}
            styles={{ input: { minWidth: 140 } }}
            comboboxProps={{ withinPortal: true }}
            searchable
          />
        </Group>
      </Group>
    </Box>
  );

  return (
    <Paper withBorder radius="md" style={{ minWidth: 0 }}>
      {header}
      <Box p="md" style={{ position: "relative" }}>
        <LoadingOverlay visible={isPending} zIndex={1} overlayProps={{ radius: "sm", blur: 2 }} />
        <AreaChart
          h={220}
          w="100%"
          data={data}
          dataKey="date"
          series={[{ name: "diamonds", label: t("dailyEarnings.seriesLabel"), color: "yellow.5" }]}
          curveType="monotone"
          tickLine="xy"
          gridAxis="xy"
          withLegend
          withTooltip
        />
      </Box>
    </Paper>
  );
}
