"use client";

import { getProfileUrl } from "@/app/components/open-social";
import { GifterRelationship } from "@/lib/types/analytics-autogenerated";
import { FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import {
  Anchor,
  Badge,
  Box,
  Group,
  LoadingOverlay,
  Pagination,
  Paper,
  Table,
  TableScrollContainer,
  TableTbody,
  TableTd,
  TableTh,
  TableThead,
  TableTr,
  Text,
  Title,
} from "@mantine/core";
import { useTranslations } from "next-intl";
import { use, useState } from "react";
import { getGlobalGifterRelationships, GlobalPage } from "../actions";
import { formatCompact } from "../lib";

const LIMIT = 10;

interface GifterRelationshipsProps {
  initialPromise: Promise<GlobalPage<GifterRelationship>>;
}

export function GifterRelationships({
  initialPromise,
}: GifterRelationshipsProps) {
  const t = useTranslations("protected.tiktokInsights");
  const initialData = use(initialPromise);

  const [relationships, setRelationships] = useState<GifterRelationship[]>(
    initialData.data,
  );
  const [total, setTotal] = useState(initialData.total);
  const [activePage, setActivePage] = useState(1);
  const [loading, setLoading] = useState(false);

  const totalPages = Math.ceil(total / LIMIT);

  const handlePageChange = async (page: number) => {
    setActivePage(page);
    setLoading(true);
    const result = await getGlobalGifterRelationships(
      LIMIT,
      (page - 1) * LIMIT,
    );
    setRelationships(result.data);
    setTotal(result.total);
    setLoading(false);
  };

  const header = (
    <Box
      style={{
        background: "linear-gradient(150deg, #B4D4FF, #5280E8)",
        borderTopLeftRadius: 8,
        borderTopRightRadius: 8,
      }}
      p="md"
    >
      <Title order={5} c="black">
        {t("gifterRelationships.title")}
      </Title>
      <Text c="black" size="xs">
        {t("gifterRelationships.description")}
      </Text>
    </Box>
  );

  if (!relationships.length && !loading) {
    return (
      <Paper withBorder radius="md">
        {header}
        <Box p="md">
          <Text c="dimmed" size="sm">
            {t("gifterRelationships.empty")}
          </Text>
        </Box>
      </Paper>
    );
  }

  return (
    <Paper withBorder radius="md">
      {header}
      <Box style={{ position: "relative" }}>
        <LoadingOverlay
          visible={loading}
          zIndex={1}
          overlayProps={{ radius: "sm", blur: 2 }}
        />
        <TableScrollContainer minWidth={800}>
          <Table striped highlightOnHover fz="sm">
            <TableThead>
              <TableTr>
                <TableTh>#</TableTh>
                <TableTh>{t("gifterRelationships.pair")}</TableTh>
                <TableTh>{t("gifterRelationships.diamonds")}</TableTh>
                <TableTh>{t("gifterRelationships.gifts")}</TableTh>
              </TableTr>
            </TableThead>
            <TableTbody>
              {relationships.map((r, i) => (
                <TableTr key={`${r.gifter}-${r.streamer}-${i}`}>
                  <TableTd>
                    <Text size="sm" c="dimmed">
                      {(activePage - 1) * LIMIT + i + 1}
                    </Text>
                  </TableTd>
                  <TableTd>
                    <Group gap={6} wrap="nowrap">
                      <Text size="sm" fw={500}>@{r.gifter ?? "—"}</Text>
                      <Text size="xs" c="dimmed">{t("gifterRelationships.supported")}</Text>
                      {r.streamer ? (
                        <Anchor
                          href={getProfileUrl({
                            username: r.streamer,
                            type: FollowerTypeEnum.Tiktok,
                          })}
                          size="sm"
                          fw={500}
                        >
                          @{r.streamer}
                        </Anchor>
                      ) : (
                        <Text size="sm" c="dimmed">—</Text>
                      )}
                    </Group>
                  </TableTd>
                  <TableTd>
                    <Badge color="yellow" variant="light" size="sm">
                      {formatCompact(r.diamonds ?? 0)}
                    </Badge>
                  </TableTd>
                  <TableTd>
                    <Text size="sm">{formatCompact(r.gift_count ?? 0)}</Text>
                  </TableTd>
                </TableTr>
              ))}
            </TableTbody>
          </Table>
        </TableScrollContainer>
      </Box>
      {totalPages > 1 && (
        <Box p="md" style={{ display: "flex", justifyContent: "center" }}>
          <Pagination
            total={totalPages}
            value={activePage}
            onChange={handlePageChange}
            size="sm"
          />
        </Box>
      )}
    </Paper>
  );
}
