"use client";

import { GlobalTopGifter } from "@/lib/types/analytics-autogenerated";
import {
  Avatar,
  Badge,
  Box,
  Group,
  LoadingOverlay,
  Pagination,
  Paper,
  Table,
  TableScrollContainer,
  TableTbody,
  TableTd,
  TableTh,
  TableThead,
  TableTr,
  Text,
  Title,
} from "@mantine/core";
import { useTranslations } from "next-intl";
import { use, useState } from "react";
import { getGlobalTopGifters, GlobalPage } from "../actions";
import { formatCompact } from "../lib";

const LIMIT = 10;

interface GlobalTopGiftersProps {
  initialPromise: Promise<GlobalPage<GlobalTopGifter>>;
}

export function GlobalTopGifters({ initialPromise }: GlobalTopGiftersProps) {
  const t = useTranslations("protected.tiktokInsights");
  const initialData = use(initialPromise);

  const [gifters, setGifters] = useState<GlobalTopGifter[]>(initialData.data);
  const [total, setTotal] = useState(initialData.total);
  const [activePage, setActivePage] = useState(1);
  const [loading, setLoading] = useState(false);

  const totalPages = Math.ceil(total / LIMIT);

  const handlePageChange = async (page: number) => {
    setActivePage(page);
    setLoading(true);
    const result = await getGlobalTopGifters(LIMIT, (page - 1) * LIMIT);
    setGifters(result.data);
    setTotal(result.total);
    setLoading(false);
  };

  const header = (
    <Box
      style={{
        background: "linear-gradient(150deg, #FFB4F0, #E852D0)",
        borderTopLeftRadius: 8,
        borderTopRightRadius: 8,
      }}
      p="md"
    >
      <Title order={5} c="black">
        {t("topGifters.title")}
        {total > 0 && (
          <Text span size="sm" fw={400} c="dark.3" ml={8}>
            ({total})
          </Text>
        )}
      </Title>
      <Text c="black" size="xs" mt={2}>{t("topGifters.description")}</Text>
    </Box>
  );

  if (!gifters.length && !loading) {
    return (
      <Paper withBorder radius="md">
        {header}
        <Box p="md">
          <Text c="dimmed" size="sm">{t("topGifters.empty")}</Text>
        </Box>
      </Paper>
    );
  }

  return (
    <Paper withBorder radius="md">
      {header}
      <Box style={{ position: "relative" }}>
        <LoadingOverlay visible={loading} zIndex={1} overlayProps={{ radius: "sm", blur: 2 }} />
        <TableScrollContainer minWidth={800}>
          <Table striped highlightOnHover fz="sm">
            <TableThead>
              <TableTr>
                <TableTh>#</TableTh>
                <TableTh>{t("topGifters.username")}</TableTh>
                <TableTh>{t("topGifters.diamonds")}</TableTh>
                <TableTh>{t("topGifters.gifts")}</TableTh>
              </TableTr>
            </TableThead>
            <TableTbody>
              {gifters.map((g, i) => (
                <TableTr key={g.sender_username ?? i}>
                  <TableTd>
                    <Text size="sm" c="dimmed">{(activePage - 1) * LIMIT + i + 1}</Text>
                  </TableTd>
                  <TableTd>
                    <Group gap="xs" wrap="nowrap">
                      <Avatar size="sm" color="violet" radius="xl">
                        {(g.sender_username ?? "?")[0].toUpperCase()}
                      </Avatar>
                      <div>
                        <Text size="sm" fw={500}>@{g.sender_username ?? "—"}</Text>
                        {g.sender_nickname && (
                          <Text size="xs" c="dimmed">{g.sender_nickname}</Text>
                        )}
                      </div>
                    </Group>
                  </TableTd>
                  <TableTd>
                    <Badge color="yellow" variant="light" size="sm">
                      {formatCompact(g.diamonds ?? 0)}
                    </Badge>
                  </TableTd>
                  <TableTd>
                    <Text size="sm">{formatCompact(g.gift_count ?? 0)}</Text>
                  </TableTd>
                </TableTr>
              ))}
            </TableTbody>
          </Table>
        </TableScrollContainer>
      </Box>
      {totalPages > 1 && (
        <Box p="md" style={{ display: "flex", justifyContent: "center" }}>
          <Pagination total={totalPages} value={activePage} onChange={handlePageChange} size="sm" />
        </Box>
      )}
    </Paper>
  );
}
