"use client";

import { useIntlNames } from "@/app/[locale]/(protected)/hooks/use-intl-names";
import { LanguageEntry } from "@/lib/types/analytics-autogenerated";
import {
  Badge,
  Box,
  Button,
  Group,
  Paper,
  Table,
  TableScrollContainer,
  TableTbody,
  TableTd,
  TableTh,
  TableThead,
  TableTr,
  Text,
  Title,
} from "@mantine/core";
import { useTranslations } from "next-intl";
import { use, useState } from "react";

const INITIAL_VISIBLE = 10;
import { formatCompact } from "../lib";

interface LanguageLeaderboardProps {
  dataPromise: Promise<LanguageEntry[]>;
}

export function LanguageLeaderboard({ dataPromise }: LanguageLeaderboardProps) {
  const t = useTranslations("protected.tiktokInsights");
  const { getLanguageName } = useIntlNames();
  const entries = use(dataPromise);
  const [visible, setVisible] = useState(INITIAL_VISIBLE);

  const header = (
    <Box
      style={{
        background: "linear-gradient(150deg, #D4B4FF, #8852E8)",
        borderTopLeftRadius: 8,
        borderTopRightRadius: 8,
      }}
      p="md"
    >
      <Title order={5} c="black">
        {t("languageLeaderboard.title")}
      </Title>
    </Box>
  );

  if (!entries.length) {
    return (
      <Paper withBorder radius="md">
        {header}
        <Box p="md">
          <Text c="dimmed" size="sm">{t("languageLeaderboard.empty")}</Text>
        </Box>
      </Paper>
    );
  }

  return (
    <Paper withBorder radius="md">
      {header}
      <TableScrollContainer minWidth={800}>
        <Table striped highlightOnHover fz="sm">
          <TableThead>
            <TableTr>
              <TableTh>{t("languageLeaderboard.rank")}</TableTh>
              <TableTh>{t("languageLeaderboard.language")}</TableTh>
              <TableTh>{t("languageLeaderboard.diamonds")}</TableTh>
              <TableTh>{t("languageLeaderboard.gifts")}</TableTh>
              <TableTh>{t("languageLeaderboard.streamers")}</TableTh>
              <TableTh>{t("languageLeaderboard.gifters")}</TableTh>
            </TableTr>
          </TableThead>
          <TableTbody>
            {entries.slice(0, visible).map((entry, i) => (
              <TableTr key={entry.language ?? i}>
                <TableTd>
                  <Text size="sm" c="dimmed">{i + 1}</Text>
                </TableTd>
                <TableTd>
                  {entry.language ? (
                    <Group gap={8} wrap="nowrap">
                      <Badge size="sm" variant="light" tt="uppercase" w={40}>
                        {entry.language}
                      </Badge>
                      <Text size="sm" fw={500}>{getLanguageName(entry.language)}</Text>
                    </Group>
                  ) : (
                    <Text size="sm" c="dimmed">—</Text>
                  )}
                </TableTd>
                <TableTd>
                  <Badge color="yellow" variant="light" size="sm">
                    {formatCompact(entry.diamonds ?? 0)}
                  </Badge>
                </TableTd>
                <TableTd>
                  <Text size="sm">{formatCompact(entry.gifts ?? 0)}</Text>
                </TableTd>
                <TableTd>
                  <Text size="sm">{entry.streamers ?? 0}</Text>
                </TableTd>
                <TableTd>
                  <Text size="sm">{formatCompact(entry.unique_gifters ?? 0)}</Text>
                </TableTd>
              </TableTr>
            ))}
          </TableTbody>
        </Table>
      </TableScrollContainer>
      {visible < entries.length && (
        <Box p="md" style={{ display: "flex", justifyContent: "center" }}>
          <Button
            variant="subtle"
            size="sm"
            onClick={() => setVisible((v) => Math.min(v + INITIAL_VISIBLE, entries.length))}
          >
            {t("languageLeaderboard.loadMore")} ({entries.length - visible})
          </Button>
        </Box>
      )}
    </Paper>
  );
}
