"use client";

import { useIntlNames } from "@/app/[locale]/(protected)/hooks/use-intl-names";
import { getProfileUrl } from "@/app/components/open-social";
import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import {
  Anchor,
  Avatar,
  Badge,
  Box,
  Group,
  Image,
  LoadingOverlay,
  Pagination,
  Paper,
  Select,
  SelectProps,
  Table,
  TableScrollContainer,
  TableTbody,
  TableTd,
  TableTh,
  TableThead,
  TableTr,
  Text,
  Title,
} from "@mantine/core";
import { useTranslations } from "next-intl";
import { use, useState } from "react";
import { EnrichedTopEarner, getGlobalTopEarners, GlobalPage } from "../actions";
import { formatCompact } from "../lib";

const LIMIT = 10;

const FlagIcon = ({ code, size = 16 }: { code: string; size?: number }) => (
  <Image
    src={`https://flagcdn.com/w40/${code.toLowerCase()}.png`}
    alt={code}
    w={size}
    h={Math.round(size * 0.75)}
    radius={2}
    fit="cover"
  />
);

interface TopEarnersProps {
  initialPromise: Promise<GlobalPage<EnrichedTopEarner>>;
  countriesPromise: Promise<string[]>;
  languagesPromise: Promise<string[]>;
}

export function TopEarners({
  initialPromise,
  countriesPromise,
  languagesPromise,
}: TopEarnersProps) {
  const t = useTranslations("protected.tiktokInsights");
  const { getCountryName, getLanguageName } = useIntlNames();
  const initialData = use(initialPromise);
  const countries = use(countriesPromise);
  const languages = use(languagesPromise);

  const [earners, setEarners] = useState<EnrichedTopEarner[]>(initialData.data);
  const [total, setTotal] = useState(initialData.total);
  const [activePage, setActivePage] = useState(1);
  const [country, setCountry] = useState<string | null>(null);
  const [language, setLanguage] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const totalPages = Math.ceil(total / LIMIT);

  const fetchPage = async (
    page: number,
    c: string | null,
    l: string | null,
  ) => {
    setLoading(true);
    const result = await getGlobalTopEarners(
      LIMIT,
      (page - 1) * LIMIT,
      c ?? undefined,
      l ?? undefined,
    );
    setEarners(result.data);
    setTotal(result.total);
    setLoading(false);
  };

  const handlePageChange = (page: number) => {
    setActivePage(page);
    fetchPage(page, country, language);
  };

  const handleCountryChange = (val: string | null) => {
    const newCountry = val || null;
    setCountry(newCountry);
    setActivePage(1);
    fetchPage(1, newCountry, language);
  };

  const handleLanguageChange = (val: string | null) => {
    const newLanguage = val || null;
    setLanguage(newLanguage);
    setActivePage(1);
    fetchPage(1, country, newLanguage);
  };

  const countryOptions = [
    { value: "", label: t("topEarners.allCountries") },
    ...countries.map((c) => ({ value: c, label: getCountryName(c) })),
  ];

  const languageOptions = [
    { value: "", label: t("topEarners.allLanguages") },
    ...languages.map((l) => ({ value: l, label: getLanguageName(l) })),
  ];

  const renderCountryOption: SelectProps["renderOption"] = ({ option }) =>
    option.value === "" ? (
      <span>{option.label}</span>
    ) : (
      <Group gap="sm">
        <FlagIcon code={option.value} size={18} />
        <span>{option.label}</span>
      </Group>
    );

  const renderLanguageOption: SelectProps["renderOption"] = ({ option }) =>
    option.value === "" ? (
      <span>{option.label}</span>
    ) : (
      <Group gap="sm">
        <Badge size="xs" variant="light" tt="uppercase" w={36}>
          {option.value}
        </Badge>
        <span>{option.label}</span>
      </Group>
    );

  const header = (
    <Box
      style={{
        background: "linear-gradient(150deg, #B4E8FF, #52A0E8)",
        borderTopLeftRadius: 8,
        borderTopRightRadius: 8,
      }}
      p="md"
    >
      <Group justify="space-between" wrap="wrap" gap="xs">
        <Title order={5} c="black">
          {t("topEarners.title")}
        </Title>
        <Group gap="xs" wrap="nowrap">
          <Select
            size="xs"
            data={countryOptions}
            value={country ?? ""}
            onChange={handleCountryChange}
            renderOption={renderCountryOption}
            styles={{ input: { minWidth: 130 } }}
            comboboxProps={{ withinPortal: true }}
            searchable
          />
          <Select
            size="xs"
            data={languageOptions}
            value={language ?? ""}
            onChange={handleLanguageChange}
            renderOption={renderLanguageOption}
            styles={{ input: { minWidth: 130 } }}
            comboboxProps={{ withinPortal: true }}
            searchable
          />
        </Group>
      </Group>
    </Box>
  );

  if (!earners.length && !loading) {
    return (
      <Paper withBorder radius="md">
        {header}
        <Box p="md">
          <Text c="dimmed" size="sm">
            {t("topEarners.empty")}
          </Text>
        </Box>
      </Paper>
    );
  }

  return (
    <Paper withBorder radius="md">
      {header}
      <Box style={{ position: "relative" }}>
        <LoadingOverlay
          visible={loading}
          zIndex={1}
          overlayProps={{ radius: "sm", blur: 2 }}
        />
        <TableScrollContainer minWidth={800}>
          <Table striped highlightOnHover fz="sm">
            <TableThead>
              <TableTr>
                <TableTh>#</TableTh>
                <TableTh>{t("topEarners.username")}</TableTh>
                <TableTh>{t("topEarners.country")}</TableTh>
                <TableTh>{t("topEarners.language")}</TableTh>
                <TableTh>{t("topEarners.diamonds")}</TableTh>
                <TableTh>{t("topEarners.gifts")}</TableTh>
                <TableTh>{t("topEarners.gifters")}</TableTh>
              </TableTr>
            </TableThead>
            <TableTbody>
              {earners.map((e, i) => (
                <TableTr key={e.owner_username ?? i}>
                  <TableTd>
                    <Text size="sm" c="dimmed">
                      {(activePage - 1) * LIMIT + i + 1}
                    </Text>
                  </TableTd>
                  <TableTd>
                    <Group gap="xs" wrap="nowrap">
                      <Avatar
                        src={
                          e.followerAvatarUrl
                            ? generateAvatarUrl(e.followerAvatarUrl)
                            : undefined
                        }
                        size="sm"
                        radius="xl"
                        color="blue"
                      >
                        {(e.owner_username ?? "?")[0].toUpperCase()}
                      </Avatar>
                      <div>
                        {e.owner_username ? (
                          <Anchor
                            href={getProfileUrl({
                              username: e.owner_username,
                              type: FollowerTypeEnum.Tiktok,
                            })}
                            size="sm"
                            fw={500}
                          >
                            @{e.owner_username}
                          </Anchor>
                        ) : (
                          <Text size="sm" c="dimmed">
                            —
                          </Text>
                        )}
                        {e.followerNickname && (
                          <Text size="xs" c="dimmed">
                            {e.followerNickname}
                          </Text>
                        )}
                      </div>
                    </Group>
                  </TableTd>
                  <TableTd>
                    {e.owner_country &&
                    /^[A-Za-z]{2}$/.test(e.owner_country) ? (
                      <Group gap={6} wrap="nowrap">
                        <FlagIcon code={e.owner_country} size={16} />
                        <Text size="sm">{getCountryName(e.owner_country)}</Text>
                      </Group>
                    ) : (
                      <Text size="sm" c="dimmed">
                        —
                      </Text>
                    )}
                  </TableTd>
                  <TableTd>
                    {e.owner_language ? (
                      <Group gap={6} wrap="nowrap">
                        <Badge size="xs" variant="light" tt="uppercase">
                          {e.owner_language}
                        </Badge>
                        <Text size="sm">
                          {getLanguageName(e.owner_language)}
                        </Text>
                      </Group>
                    ) : (
                      <Text size="sm" c="dimmed">
                        —
                      </Text>
                    )}
                  </TableTd>
                  <TableTd>
                    <Badge color="yellow" variant="light" size="sm">
                      {formatCompact(e.diamonds ?? 0)}
                    </Badge>
                  </TableTd>
                  <TableTd>
                    <Text size="sm">{formatCompact(e.gift_count ?? 0)}</Text>
                  </TableTd>
                  <TableTd>
                    <Text size="sm">
                      {formatCompact(e.unique_gifters ?? 0)}
                    </Text>
                  </TableTd>
                </TableTr>
              ))}
            </TableTbody>
          </Table>
        </TableScrollContainer>
      </Box>
      {totalPages > 1 && (
        <Box p="md" style={{ display: "flex", justifyContent: "center" }}>
          <Pagination
            total={totalPages}
            value={activePage}
            onChange={handlePageChange}
            size="sm"
          />
        </Box>
      )}
    </Paper>
  );
}
