"use server";

import api from "@/lib/api";
import { ScopeEnum } from "@/lib/types/strapi-autogenerated";
import { deepMerge } from "@mantine/core";

const defaultOptions = {
  "pagination[pageSize]": 10,
  sort: "updatedAt:desc",
  filters: {
    sources: {
      state: {
        $eq: "recording",
      },
    },
  },
  populate: {
    sources: {
      filters: {
        state: {
          $eq: "recording",
        },
      },
    },
    follower: {
      fields: ["username", "type"],
      populate: {
        avatar: {
          fields: ["url"],
        },
      },
    },
  },
};

export async function fetchLiveRecordings(
  scope: string = ScopeEnum.Following,
  page: number = 1,
  type?: string,
) {
  const typeFilter = type
    ? { filters: { follower: { type: { $eq: type } } } }
    : {};

  const response = await api.recording.browseRecordings(
    deepMerge(defaultOptions, {
      "pagination[page]": page,
      "pagination[withCount]": true,
      scope,
      ...typeFilter,
    }),
  );

  return {
    data: response.data?.data || [],
    meta: response.data?.meta,
  };
}
