"use server";

import api from "@/lib/api";
import publicApi from "@/lib/public-api";
import { FollowerTypeEnum, ScopeEnum } from "@/lib/types/strapi-autogenerated";
import { unstable_cache } from "next/cache";

const basePopulate = {
  sources: {
    fields: ["*"],
    filters: {
      state: {
        $eq: "done",
      },
    },
  },
  follower: {
    fields: ["username", "type"],
    populate: {
      avatar: {
        fields: ["url"],
      },
    },
  },
};

const baseFilters = {
  sources: {
    state: {
      $eq: ["done"],
    },
  },
};

export async function fetchFollowingByPlatform(
  platform: FollowerTypeEnum,
) {
  const response = await api.recording.browseRecordings({
    scope: ScopeEnum.Following,
    filters: {
      ...baseFilters,
      follower: {
        type: { $eq: platform },
      },
    },
    populate: basePopulate,
    sort: "updatedAt:desc",
    "pagination[page]": 1,
    "pagination[pageSize]": 4,
  });

  return response.data?.data || [];
}

export const fetchDiscoverByPlatform = unstable_cache(
  async (platform: FollowerTypeEnum) => {
    const response = await publicApi.recording.browseRecordings({
      scope: ScopeEnum.Discover,
      filters: {
        ...baseFilters,
        follower: {
          type: { $eq: platform },
        },
      },
      populate: basePopulate,
      sort: "updatedAt:desc",
      "pagination[page]": 1,
      "pagination[pageSize]": 4,
    });

    return response.data?.data || [];
  },
  ["dashboard-discover"],
  { revalidate: 900 },
);

export async function fetchLatestFollowers() {
  const response = await api.follower.getFollowers({
    sort: "createdAt:desc",
    "pagination[page]": 1,
    "pagination[pageSize]": 6,
    populate: ["avatar"],
  });

  return response.data?.data || [];
}
