import { CountryFlag } from "@/app/[locale]/(protected)/components/country-flag";
import { getProfileUrl } from "@/app/components/open-social";

import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { Follower } from "@/lib/types/strapi-autogenerated";
import { Avatar, Flex, Stack, Text } from "@mantine/core";
import Image from "next/image";
import Link from "@/app/components/link";
import styles from "./creators-slider.module.css";

export function CreatorsSlider({
  followers,
}: {
  followers: Follower[] | undefined;
}) {
  if (!followers?.length) return null;

  return (
    <div style={{ overflowX: "clip" }}>
      <div className={styles.sliderContainer}>
        <div className={styles.sliderTrack}>
          {followers.map((creator, index) => (
            <Link
              key={`${creator.id}-${index}`}
              href={getProfileUrl(creator)}
              className={styles.slide}
            >
              <Flex
                style={{
                  cursor: "pointer",
                  textAlign: "center",
                }}
                mx="md"
              >
                <Stack align="center" gap={12}>
                  <div style={{ position: "relative" }}>
                    <Avatar size={72} radius="xl">
                      {creator.avatar?.url ? (
                        <Image
                          src={generateAvatarUrl(creator.avatar?.url)}
                          alt={`${creator.username} avatar`}
                          width={72}
                          height={72}
                          quality={75}
                          loading="lazy"
                        />
                      ) : null}
                    </Avatar>
                  </div>
                  <div>
                    <Text fw={600} size="sm" style={{ color: "#f1f5f9" }}>
                      {creator.nickname || "unknown"}
                    </Text>
                    <Text size="xs" style={{ color: "#64748b" }}>
                      @{decodeURIComponent(creator.username)}
                    </Text>
                  </div>
                  <div style={{ minHeight: 24 }}>
                    {creator.countryCode && (
                      <CountryFlag
                        countryCode={creator.countryCode}
                        size={20}
                      />
                    )}
                  </div>
                </Stack>
              </Flex>
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
}
