"use client";

import { ClipPreview } from "@/app/[locale]/(protected)/my-clips/components/clip-preview";
import { Clip } from "@/lib/types/strapi-autogenerated";
import { Card, Flex, Stack, Text } from "@mantine/core";

interface ProfileClipCardProps {
  clip: Clip;
  locale: string;
}

export function ProfileClipCard({ clip, locale }: ProfileClipCardProps) {
  return (
    <Card radius="md" withBorder>
      <Stack gap="xs">
        <Flex justify="space-between" align="center">
          <Text fw="bold" fz="xs" lineClamp={1}>
            {clip.title}
          </Text>
        </Flex>

        <ClipPreview clip={clip} type={clip.follower?.type} locale={locale} />
      </Stack>
    </Card>
  );
}
