"use client";

import {
  ClipShareStateEnum1,
  ClipWithShare,
} from "@/lib/types/strapi-autogenerated";
import {
  Badge,
  Button,
  Card,
  Flex,
  Progress,
  Stack,
  Title,
} from "@mantine/core";
import {
  IconBrandTiktok,
  IconBrandYoutube,
  IconCheck,
} from "@tabler/icons-react";
import { useTranslations } from "next-intl";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { checkAndUpdateTikTokStatus } from "../actions/share-tiktok";
import { ClipPreview } from "./clip-preview";

interface ClipShareData {
  documentId?: string;
  state?: string;
  platform?: string;
  data?: { publishId?: string; videoId?: string };
}

interface ClipCardProps {
  clip: ClipWithShare & {
    clipShares?: Record<string, ClipShareData>;
  };
  locale: string;
}

function PlatformButton({
  platform,
  share,
  clipDocumentId,
  label,
  icon,
  color,
}: {
  platform: string;
  share?: ClipShareData | null;
  clipDocumentId: string;
  label: string;
  icon: React.ReactNode;
  color: string;
}) {
  const t = useTranslations("protected.myClips");
  const state = share?.state;

  if (state === ClipShareStateEnum1.Processing) {
    return (
      <Progress.Root size={40} radius="md">
        <Progress.Section value={100} color="yellow" animated>
          <Progress.Label lh={1.4}>{t("share.processing")}</Progress.Label>
        </Progress.Section>
      </Progress.Root>
    );
  }

  if (state === ClipShareStateEnum1.Completed) {
    return (
      <Button
        size="md"
        variant="light"
        color="green"
        leftSection={icon}
        rightSection={<IconCheck size={16} />}
        fullWidth
        disabled
      >
        {t("share.completed")}
      </Button>
    );
  }

  if (state === ClipShareStateEnum1.Failed) {
    return (
      <Button
        component={Link}
        href={`/my-clips/${clipDocumentId}/publish/${platform}`}
        size="md"
        variant="light"
        color="red"
        leftSection={icon}
        fullWidth
      >
        {t("share.retry")}
      </Button>
    );
  }

  return (
    <Button
      component={Link}
      href={`/my-clips/${clipDocumentId}/publish/${platform}`}
      size="md"
      variant="filled"
      color={color}
      leftSection={icon}
      fullWidth
    >
      {label}
    </Button>
  );
}

export function ClipCard({ clip, locale }: ClipCardProps) {
  const t = useTranslations("protected.myClips");
  const router = useRouter();

  const tiktokShare = clip.clipShares?.tiktok;
  const youtubeShare = clip.clipShares?.youtube;

  const [tiktokState, setTiktokState] = useState(tiktokShare?.state);

  const tiktokPublishId = (tiktokShare?.data as { publishId?: string })
    ?.publishId;
  const tiktokShareId = tiktokShare?.documentId;

  // Poll TikTok status for processing clips
  useEffect(() => {
    if (tiktokState !== "processing" || !tiktokPublishId || !tiktokShareId)
      return;

    let isMounted = true;

    const checkStatus = async () => {
      if (!isMounted) return;

      const result = await checkAndUpdateTikTokStatus(
        tiktokShareId,
        tiktokPublishId,
      );

      if (!isMounted) return;

      if (result.updated) {
        if (result.status === "PUBLISH_COMPLETE") {
          setTiktokState(ClipShareStateEnum1.Completed);
        } else if (result.status === "FAILED") {
          setTiktokState(ClipShareStateEnum1.Failed);
        }
        router.refresh();
      }
    };

    checkStatus();
    const interval = setInterval(checkStatus, 5000);

    return () => {
      isMounted = false;
      clearInterval(interval);
    };
  }, [tiktokState, tiktokPublishId, tiktokShareId, router]);

  return (
    <Card radius="md" withBorder>
      <Stack gap="xs">
        <Flex justify="space-between" align="center">
          <Title order={4} lineClamp={1}>
            {clip.title}
          </Title>
          <Badge size="lg" variant="light">
            {`${clip.viral_score}/100`}
          </Badge>
        </Flex>

        <ClipPreview clip={clip} type={clip.follower?.type} locale={locale} />

        <Stack gap="xs">
          <PlatformButton
            platform="tiktok"
            share={
              tiktokShare
                ? { ...tiktokShare, state: tiktokState }
                : undefined
            }
            clipDocumentId={clip.documentId!}
            label={t("share.tiktok")}
            icon={<IconBrandTiktok size={18} />}
            color="dark"
          />
          <PlatformButton
            platform="youtube"
            share={youtubeShare}
            clipDocumentId={clip.documentId!}
            label={t("share.youtube")}
            icon={<IconBrandYoutube size={18} />}
            color="red"
          />
        </Stack>
      </Stack>
    </Card>
  );
}
