"use client";

import {
  ClipShareStateEnum1,
  ClipWithShare,
} from "@/lib/types/strapi-autogenerated";
import {
  Badge,
  Button,
  Card,
  Flex,
  Progress,
  Stack,
  Title,
} from "@mantine/core";
import { IconBrandTiktok } from "@tabler/icons-react";
import { useTranslations } from "next-intl";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { checkAndUpdateTikTokStatus } from "../actions/share-tiktok";
import { ClipPreview } from "./clip-preview";

interface ClipCardProps {
  clip: ClipWithShare;
  locale: string;
}

export function ClipCard({ clip, locale }: ClipCardProps) {
  const t = useTranslations("protected.myClips");
  const router = useRouter();
  const [currentState, setCurrentState] = useState(clip.clipShare?.state);

  const clipShare = clip.clipShare;
  const clipShareId = clipShare?.documentId;
  const publishId = (clipShare?.data as { publishId?: string })?.publishId;

  // Poll TikTok status for processing clips
  useEffect(() => {
    if (currentState !== "processing" || !publishId || !clipShareId) return;

    let isMounted = true;

    const checkStatus = async () => {
      if (!isMounted) return;

      const result = await checkAndUpdateTikTokStatus(clipShareId, publishId);

      if (!isMounted) return;

      // Update local state if status changed to final
      if (result.updated) {
        if (result.status === "PUBLISH_COMPLETE") {
          setCurrentState(ClipShareStateEnum1.Completed);
        } else if (result.status === "FAILED") {
          setCurrentState(ClipShareStateEnum1.Failed);
        }
        router.refresh();
      }
    };

    // Initial check immediately
    checkStatus();

    // Then poll every 5 seconds
    const interval = setInterval(checkStatus, 5000);

    return () => {
      isMounted = false;
      clearInterval(interval);
    };
  }, [currentState, publishId, clipShareId, router]);

  // Get border color based on state
  const getBorderColor = () => {
    switch (currentState) {
      case "processing":
        return "var(--mantine-color-yellow-6)";
      case "completed":
        return "var(--mantine-color-green-6)";
      case "failed":
        return "var(--mantine-color-red-6)";
      default:
        return undefined;
    }
  };

  const borderColor = getBorderColor();

  const renderTikTokStatus = () => {
    if (currentState === ClipShareStateEnum1.Processing) {
      return (
        <Progress.Root size={40} radius="md">
          <Progress.Section value={100} color="yellow" animated>
            <Progress.Label lh={1.4}>{t("share.processing")}</Progress.Label>
          </Progress.Section>
        </Progress.Root>
      );
    }

    if (currentState === ClipShareStateEnum1.Completed) {
      return (
        <Progress.Root size={40} radius="md">
          <Progress.Section value={100} color="green">
            <Progress.Label>{t("share.completed")}</Progress.Label>
          </Progress.Section>
        </Progress.Root>
      );
    }

    if (currentState === ClipShareStateEnum1.Failed) {
      return (
        <Link
          href={`/my-clips/${clip.documentId}/publish`}
          style={{ textDecoration: "none" }}
        >
          <Progress.Root size={40} radius="md" style={{ cursor: "pointer" }}>
            <Progress.Section value={100} color="red">
              <Progress.Label>{t("share.retry")}</Progress.Label>
            </Progress.Section>
          </Progress.Root>
        </Link>
      );
    }

    // No share yet - big obvious button
    return (
      <Button
        component={Link}
        href={`/my-clips/${clip.documentId}/publish`}
        size="md"
        variant="filled"
        leftSection={<IconBrandTiktok size={18} />}
        fullWidth
      >
        {t("share.tiktok")}
      </Button>
    );
  };

  return (
    <Card
      radius="md"
      withBorder
      style={borderColor ? { borderColor, borderWidth: 3 } : undefined}
    >
      <Stack gap="xs">
        {/* Title and badge above video */}
        <Flex justify="space-between" align="center">
          <Title order={4} lineClamp={1}>
            {clip.title}
          </Title>
          <Badge size="lg" variant="light">
            {`${clip.viral_score}/100`}
          </Badge>
        </Flex>

        <ClipPreview clip={clip} type={clip.follower?.type} locale={locale} />

        {/* Action buttons */}
        <Stack gap="xs">
          {renderTikTokStatus()}
          {/*
          <Group grow>
            <Button
              size="sm"
              variant="light"
              color="gray"
              leftSection={<IconEdit size={16} />}
              disabled={currentState === ClipShareStateEnum1.Processing}
            >
              {t("actions.edit")}
            </Button>
            <Button
              size="sm"
              variant="light"
              color="red"
              leftSection={<IconTrash size={16} />}
              disabled={currentState === ClipShareStateEnum1.Processing}
            >
              {t("actions.delete")}
            </Button>
          </Group> */}
        </Stack>
      </Stack>
    </Card>
  );
}
