
"use client";

import { getClipUrl } from "@/app/lib/clip-url";
import { Clip } from "@/lib/types/strapi-autogenerated";
import { ScrollArea } from "@mantine/core";
import Link from "@/app/components/link";
import { useState } from "react";

function ClipItem({ clip }: { clip: Clip }) {
  const [failed, setFailed] = useState(false);

  if (failed) return null;

  return (
    <Link href={`/shorts/${clip.documentId}`}>
      <video
        poster={getClipUrl(clip.documentId!, "thumbnail.jpg", clip.path)}
        preload="metadata"
        autoPlay
        muted
        loop
        playsInline
        height={400}
        style={{
          flexShrink: 0,
          pointerEvents: "none",
          borderRadius: "8px",
        }}
        onError={() => setFailed(true)}
      >
        <source
          src={getClipUrl(clip.documentId!, "preview.mp4", clip.path)}
          type="video/mp4"
        />
      </video>
    </Link>
  );
}

export function ClipSlider({ clips }: { clips: Clip[] }) {
  return (
    <div style={{ overflow: "hidden" }}>
      <ScrollArea type="never" scrollbarSize={0} mt="xl" mx={-32}>
        <div
          style={{
            display: "flex",
            gap: "20px",
            justifyContent: "center",
            minWidth: "max-content",
          }}
        >
          {clips.map((clip) => (
            <ClipItem key={clip.id} clip={clip} />
          ))}
        </div>
      </ScrollArea>
    </div>
  );
}
