"use server";

import analyticsApi from "@/lib/analytics-api";
import {
  BattleStat,
  CountryEntry,
  DailyStats,
  GifterRelationship,
  GlobalStats,
  GlobalTopGifter,
  LanguageEntry,
  MostLiveStreamer,
  TopEarner,
} from "@/lib/types/analytics-autogenerated";
import { enrichWithFollowers, FollowerEnrichment } from "./enrich";

export type EnrichedBattleStat = BattleStat & FollowerEnrichment;
export type EnrichedTopEarner = TopEarner & FollowerEnrichment;
export type EnrichedMostLiveStreamer = MostLiveStreamer & FollowerEnrichment;

export type GlobalPage<T> = {
  data: T[];
  total: number;
  hasMore: boolean;
};

export async function getGlobalStats(): Promise<GlobalStats | null> {
  try {
    const res = await analyticsApi.global.getGlobalStats();
    return res.data;
  } catch {
    return null;
  }
}

export async function getGlobalDailyEarnings(
  country?: string,
  language?: string,
): Promise<DailyStats[]> {
  try {
    const res = await analyticsApi.global.getDailyEarnings({ country, language });
    return res.data;
  } catch {
    return [];
  }
}

export async function getAvailableCountries(): Promise<string[]> {
  try {
    const res = await analyticsApi.global.getCountries();
    return res.data;
  } catch {
    return [];
  }
}

export async function getAvailableLanguages(): Promise<string[]> {
  try {
    const res = await analyticsApi.global.getLanguages();
    return res.data;
  } catch {
    return [];
  }
}

export async function getGlobalCountryLeaderboard(): Promise<CountryEntry[]> {
  try {
    const res = await analyticsApi.global.getCountryLeaderboard();
    return res.data;
  } catch {
    return [];
  }
}

export async function getGlobalLanguageLeaderboard(): Promise<LanguageEntry[]> {
  try {
    const res = await analyticsApi.global.getLanguageLeaderboard();
    return res.data;
  } catch {
    return [];
  }
}

export async function getGlobalTopEarners(
  limit = 10,
  offset = 0,
  country?: string,
  language?: string,
): Promise<GlobalPage<EnrichedTopEarner>> {
  try {
    const res = await analyticsApi.global.getTopStreamers({ limit, offset, country, language });
    const data = await enrichWithFollowers(res.data.data ?? []);
    return { data, total: res.data.total, hasMore: res.data.hasMore };
  } catch {
    return { data: [], total: 0, hasMore: false };
  }
}

export async function getGlobalMostLive(
  limit = 10,
  offset = 0,
  country?: string,
  language?: string,
): Promise<GlobalPage<EnrichedMostLiveStreamer>> {
  try {
    const res = await analyticsApi.global.getMostLive({ limit, offset, country, language });
    const data = await enrichWithFollowers(res.data.data ?? []);
    return { data, total: res.data.total, hasMore: res.data.hasMore };
  } catch {
    return { data: [], total: 0, hasMore: false };
  }
}

export async function getGlobalTopGifters(
  limit = 10,
  offset = 0,
): Promise<GlobalPage<GlobalTopGifter>> {
  try {
    const res = await analyticsApi.global.getTopGifters({ limit, offset });
    return {
      data: res.data.data ?? [],
      total: res.data.total,
      hasMore: res.data.hasMore,
    };
  } catch {
    return { data: [], total: 0, hasMore: false };
  }
}

export async function getGlobalBattleStats(
  limit = 10,
  offset = 0,
): Promise<GlobalPage<EnrichedBattleStat>> {
  try {
    const res = await analyticsApi.global.getBattleStats({ limit, offset });
    const data = await enrichWithFollowers(res.data.data ?? []);
    return { data, total: res.data.total, hasMore: res.data.hasMore };
  } catch {
    return { data: [], total: 0, hasMore: false };
  }
}

export async function getGlobalGifterRelationships(
  limit = 10,
  offset = 0,
): Promise<GlobalPage<GifterRelationship>> {
  try {
    const res = await analyticsApi.global.getGifterRelationships({ limit, offset });
    return {
      data: res.data.data ?? [],
      total: res.data.total,
      hasMore: res.data.hasMore,
    };
  } catch {
    return { data: [], total: 0, hasMore: false };
  }
}
