"use client";

import { Recording } from "@/lib/types/strapi-autogenerated";
import {
  Alert,
  Box,
  Button,
  Checkbox,
  Group,
  Stack,
  Text,
} from "@mantine/core";
import { IconAlertTriangle, IconSparkles } from "@tabler/icons-react";
import { useTranslations } from "next-intl";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { MiniPlayer } from "../../components/video/mini-player";
import { createAiRequest } from "../actions/ai-actions";

interface Props {
  recording: Recording;
}

const MAX_SIZE_BYTES = 2 * 1024 * 1024 * 1024; // 2GB

export function AiCreateForm({ recording }: Props) {
  const t = useTranslations("protected.aiStudio.create");
  const router = useRouter();
  const [isPending, startTransition] = useTransition();

  const [generateClips, setGenerateClips] = useState(true);
  const [generateMemes, setGenerateMemes] = useState(false);
  const [generateProfile, setGenerateProfile] = useState(false);

  // Calculate total size from sources
  const totalBytes =
    recording.sources?.reduce((sum, source) => {
      return sum + parseInt(source.videoOriginal?.sizeBytes || "0", 10);
    }, 0) || 0;

  const isOverLimit = totalBytes > MAX_SIZE_BYTES;
  const sizeGB = (totalBytes / (1024 * 1024 * 1024)).toFixed(2);

  const handleSubmit = () => {
    if (!recording.documentId) return;

    startTransition(async () => {
      const result = await createAiRequest(recording.documentId!, {
        generateClips,
        generateMemes,
        generateProfile,
      });

      if (result.success && result.documentId) {
        router.push(`/ai-studio/view/${result.documentId}`);
      }
    });
  };

  const isValid = generateClips || generateMemes || generateProfile;

  return (
    <Stack gap="lg">
      <Box maw={600} pos="relative" style={{ aspectRatio: "16/9" }}>
        <MiniPlayer documentId={recording.documentId!} />
      </Box>

      {isOverLimit && (
        <Alert
          color="orange"
          icon={<IconAlertTriangle size={20} />}
          title={t("sizeWarning.title")}
        >
          {t("sizeWarning.message", { size: sizeGB })}
        </Alert>
      )}

      <Stack gap="sm">
        <Text fw={500} size="lg">
          {t("selectOptions")}
        </Text>
        <Checkbox
          size="lg"
          label={t("options.clips.label")}
          description={t("options.clips.description")}
          checked={generateClips}
          onChange={(e) => setGenerateClips(e.currentTarget.checked)}
        />
        <Checkbox
          size="lg"
          label={t("options.memes.label")}
          description={t("options.memes.description")}
          checked={generateMemes}
          onChange={(e) => setGenerateMemes(e.currentTarget.checked)}
        />
        <Checkbox
          size="lg"
          label={t("options.profile.label")}
          description={t("options.profile.description")}
          checked={generateProfile}
          onChange={(e) => setGenerateProfile(e.currentTarget.checked)}
        />
      </Stack>

      <Group>
        <Button
          leftSection={<IconSparkles size={18} />}
          onClick={handleSubmit}
          loading={isPending}
          size="lg"
          disabled={!isValid || isOverLimit}
          color="violet"
        >
          {t("submit")}
        </Button>
      </Group>
    </Stack>
  );
}
