// components/infinite-followers.tsx
"use client";

import {
  FollowerWithMeta,
  SourceStateEnum,
} from "@/lib/types/strapi-autogenerated";
import {
  Accordion,
  AccordionControlProps,
  Anchor,
  Avatar,
  Box,
  Center,
  Flex,
  Group,
  Loader,
  Pagination,
  SimpleGrid,
  Stack,
  Text,
  useMatches,
} from "@mantine/core";
import Link from "next/link";

import { ImageSpritePreview } from "@/app/[locale]/(protected)/components/image-sprite-preview";
import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { safeRelativeTime } from "@/app/lib/safe-relative-time";
import { useUser } from "@/app/providers/user-provider";
import { IconEyeOff } from "@tabler/icons-react";
import { useQuery } from "@tanstack/react-query";
import { useFormatter, useNow, useTranslations } from "next-intl";
import Image from "next/image";
import { useRef, useState } from "react";
import { getProfileUrl } from "../../../../components/open-social";
import { CountryFlag } from "../../components/country-flag";
import FollowButton from "../../components/follow-button";
import { FollowerTypeIcon } from "../../components/follower-type-icon";
import { RecordingMenu } from "../../components/recording-menu";
import UnfollowButton from "../../components/unfollow-button";
import { getRecordings } from "../actions/fetch-followers";
import { FavoriteButton } from "./favorite-button";

interface Props {
  follower: FollowerWithMeta;
  isOpen: boolean;
}

export default function FollowerItem({ follower, isOpen }: Props) {
  const [page, setPage] = useState(1);
  const accordionRef = useRef<HTMLDivElement>(null);
  const t = useTranslations("protected.common");
  const now = useNow({ updateInterval: 1000 * 30 });
  const format = useFormatter();
  const user = useUser();
  const isMobile = useMatches({
    base: true,
    sm: false,
  });

  const { data, isLoading } = useQuery({
    queryKey: ["recordings", follower.username, follower.type, page],
    queryFn: () => getRecordings(follower.username, follower.type, page),
    enabled: isOpen,
    staleTime: 1000 * 60 * 5,
  });

  const recordings = data?.data ?? [];
  const totalPages = data?.meta?.pagination?.pageCount ?? 1;

  const handlePageChange = (newPage: number) => {
    setPage(newPage);
    // Scroll to top of accordion item when pagination changes
    accordionRef.current?.scrollIntoView({
      behavior: "smooth",
      block: "start",
    });
  };

  return (
    <Accordion.Item
      ref={accordionRef}
      key={follower.documentId}
      value={follower.username}
      style={
        follower.isFavorite ?? false
          ? {
              borderColor: "rgba(251, 191, 36, 0.4)",
              background: "rgba(251, 191, 36, 0.03)",
            }
          : undefined
      }
    >
      <AccordionControl follower={follower}>
        <Group gap="xs">
          <Box pos="relative">
            <Avatar
              size="lg"
              style={
                follower?.owner?.id === user?.id
                  ? {
                      border: "4px solid transparent",
                      background:
                        "linear-gradient(var(--mantine-color-body), var(--mantine-color-body)) padding-box, linear-gradient(135deg, #f97316, #ec4899, #8b5cf6, #3b82f6, #10b981) border-box",
                    }
                  : undefined
              }
            >
              <Image
                src={
                  follower.avatar?.url
                    ? generateAvatarUrl(follower.avatar.url)
                    : "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
                }
                alt="Avatar"
                width={60}
                height={60}
              />
            </Avatar>
            {follower.type && (
              <FollowerTypeIcon
                pos="absolute"
                color="transparent"
                type={follower.type}
                top="50%"
                left="50%"
                size="100%"
                opacity={0.1}
                style={{ transform: "translate(-50%, -50%)" }}
              />
            )}
          </Box>

          <Stack gap={2}>
            <Group gap="xs">
              <Anchor component={Link} href={getProfileUrl(follower)} size="md">
                <Text size="lg" truncate maw={isMobile ? 100 : 200} fw="bold">
                  {decodeURIComponent(follower.username)}
                </Text>
              </Anchor>
              {follower.countryCode ? (
                <CountryFlag countryCode={follower?.countryCode} />
              ) : null}
            </Group>

            <Stack gap="0">
              <Text size="xs" c="dimmed" suppressHydrationWarning>
                {t("followers.addedAgo", {
                  time: safeRelativeTime(format, follower.createdAt, {
                    now,
                  }),
                })}
              </Text>
              <Text size="xs" c="dimmed" suppressHydrationWarning>
                {t("recordings.videoCount", {
                  count: follower.totalRecordings!,
                })}
              </Text>
            </Stack>
          </Stack>
        </Group>
      </AccordionControl>
      <Accordion.Panel>
        {isLoading ? (
          <Stack align="center" py="xl">
            <Loader size="sm" />
          </Stack>
        ) : recordings.length > 0 ? (
          <Stack mt="lg" gap="lg">
            <SimpleGrid cols={{ sm: 2, md: 3, xl: 4 }} spacing="lg">
              {recordings.map((rec) => {
                const isRecording = rec.sources?.some(
                  (s) =>
                    s.state === SourceStateEnum.Recording ||
                    s.state === SourceStateEnum.Uploading,
                );

                return (
                  <Stack key={rec.documentId} gap="4">
                    <Box
                      pos="relative"
                      style={{ opacity: rec.hidden ? 0.5 : 1 }}
                    >
                      <ImageSpritePreview
                        recording={rec}
                        username={follower.username}
                        type={follower.type}
                      />
                      {rec.hidden && (
                        <Box
                          pos="absolute"
                          top={8}
                          left={8}
                          bg="dark"
                          p={4}
                          style={{ borderRadius: "var(--mantine-radius-sm)" }}
                        >
                          <IconEyeOff size={16} />
                        </Box>
                      )}
                    </Box>

                    <Group justify="space-between" align="center">
                      <Text size="sm" suppressHydrationWarning>
                        {isRecording
                          ? t("recordings.liveAgo", {
                              time: safeRelativeTime(format, rec.createdAt, {
                                style: "narrow",
                                now,
                              }),
                            })
                          : format.dateTime(new Date(rec.createdAt || ""), {
                              dateStyle: "medium",
                              timeStyle: "short",
                            })}
                      </Text>

                      <RecordingMenu
                        recording={rec}
                        username={follower.username}
                        type={follower.type}
                      />
                    </Group>
                  </Stack>
                );
              })}
            </SimpleGrid>

            {totalPages > 1 && (
              <Pagination
                value={page}
                onChange={handlePageChange}
                total={totalPages}
                siblings={1}
                style={{ alignSelf: "center" }}
              />
            )}
          </Stack>
        ) : (
          <Box
            mt="lg"
            pos="relative"
            w={160}
            h={284}
            style={{
              overflow: "hidden",
              borderRadius: "var(--mantine-radius-md)",
            }}
          >
            <Image
              alt="no videos"
              src="/assets/placeholder/180x280/1a1b1e/909296?text=No videos yet"
              unoptimized
              width={160}
              height={284}
              loading="lazy"
              style={{ objectFit: "cover", opacity: 0.8 }}
            />
          </Box>
        )}
      </Accordion.Panel>
    </Accordion.Item>
  );
}

function AccordionControl({
  follower,
  ...props
}: AccordionControlProps & { follower: FollowerWithMeta }) {
  return (
    <Center>
      <Accordion.Control {...props} disabled={follower.totalRecordings === 0} />
      <Flex gap="xs" align="center" mx="md">
        {follower.isFollowing && (
          <FavoriteButton
            documentId={follower.documentId!}
            isFavorite={follower.isFavorite ?? false}
          />
        )}
        {follower.isFollowing ? (
          <UnfollowButton username={follower.username} type={follower.type} />
        ) : (
          <FollowButton username={follower.username} type={follower.type} />
        )}
      </Flex>
    </Center>
  );
}
