// components/infinite-followers.tsx
"use client";

import {
  FollowerWithMeta,
  SourceStateEnum,
} from "@/lib/types/strapi-autogenerated";
import {
  Anchor,
  Avatar,
  Box,
  Card,
  Flex,
  Grid,
  Group,
  SimpleGrid,
  Stack,
  Text,
  useMatches,
} from "@mantine/core";
import Link from "next/link";

import { ImageSpritePreview } from "@/app/[locale]/(protected)/components/image-sprite-preview";
import { RecordingMenu } from "@/app/[locale]/(protected)/components/recording-menu";
import { getProfileUrl } from "@/app/components/open-social";
import { generateAvatarUrl } from "@/app/lib/avatar-url";
import { safeRelativeTime } from "@/app/lib/safe-relative-time";
import { useFormatter, useNow, useTranslations } from "next-intl";
import Image from "next/image";
import { CountryFlag } from "../../components/country-flag";
import FollowButton from "../../components/follow-button";
import UnfollowButton from "../../components/unfollow-button";

interface Props {
  follower: FollowerWithMeta;
}

export default function FollowerItem({ follower }: Props) {
  const t = useTranslations("protected.common");
  const now = useNow({ updateInterval: 1000 * 30 });
  const format = useFormatter();

  const mawTruncate = useMatches({
    base: 100,
    sm: 200,
  });

  return (
    <Grid.Col key={follower.documentId} span={12}>
      <Card shadow="sm" padding="sm" radius="md" h="100%" withBorder>
        <Flex justify="space-between">
          <Group gap="xs">
            <Anchor component={Link} href={getProfileUrl(follower)}>
              <Avatar size="lg">
                {follower.avatar?.url && (
                  <Image
                    src={generateAvatarUrl(follower.avatar?.url)}
                    alt={"Avatar"}
                    width={60}
                    height={60}
                  />
                )}
              </Avatar>
            </Anchor>

            <Stack gap={2}>
              <Group gap="xs">
                <Anchor component={Link} href={getProfileUrl(follower)}>
                  <Text size="lg" truncate maw={mawTruncate} fw="bold">
                    {decodeURIComponent(follower.username)}
                  </Text>
                </Anchor>
                {follower.countryCode ? (
                  <CountryFlag countryCode={follower?.countryCode} />
                ) : null}
              </Group>

              <Stack gap="0">
                <Text size="xs" c="dimmed" suppressHydrationWarning>
                  {t("followers.addedAgo", {
                    time: safeRelativeTime(format, follower.createdAt, {
                      now,
                    }),
                  })}
                </Text>
                <Text size="xs" c="dimmed" suppressHydrationWarning>
                  {t("recordings.videoCount", {
                    count: follower.totalRecordings!,
                  })}
                </Text>
              </Stack>
            </Stack>
          </Group>

          <Flex gap="xs" justify="right" align="center">
            {follower.isFollowing ? (
              <>
                <UnfollowButton
                  username={follower.username}
                  type={follower.type}
                  //onSuccess={() => handleFollowed(follower.id!)}
                />
              </>
            ) : (
              <FollowButton
                username={follower.username}
                type={follower.type}
                //onSuccess={() => handleFollowed(follower.id!)}
              />
            )}
          </Flex>
        </Flex>
        {follower.recordings && follower.recordings?.length > 0 ? (
          <Box mt="xs">
            <SimpleGrid cols={{ base: 1, sm: 2, md: 3, xl: 4 }} spacing="lg">
              {follower.recordings?.map((rec, index) => {
                const isRecording = rec.sources?.some(
                  (s) =>
                    s.state === SourceStateEnum.Recording ||
                    s.state === SourceStateEnum.Uploading,
                );

                return (
                  <Stack
                    key={rec.documentId}
                    gap="4"
                    visibleFrom={getVisibleFrom(index)}
                  >
                    <ImageSpritePreview
                      recording={rec}
                      username={follower.username}
                      type={follower.type}
                    />

                    <Group justify="space-between">
                      <Text size="sm" suppressHydrationWarning>
                        {isRecording
                          ? t("recordings.liveAgo", {
                              time: safeRelativeTime(format, rec.createdAt, {
                                style: "narrow",
                                now,
                              }),
                            })
                          : format.dateTime(new Date(rec.createdAt || ""), {
                              dateStyle: "medium",
                              timeStyle: "short",
                            })}
                      </Text>
                      <RecordingMenu
                        recording={rec}
                        username={follower.username}
                        type={follower.type}
                      />
                    </Group>
                  </Stack>
                );
              })}
            </SimpleGrid>
          </Box>
        ) : (
          <Box
            mt="lg"
            pos="relative"
            w={160}
            h={284}
            style={{
              overflow: "hidden",
              borderRadius: "var(--mantine-radius-md)",
            }}
          >
            <Image
              alt=""
              src="/assets/placeholder/180x280/1a1b1e/909296?text=No videos yet"
              unoptimized
              width={160}
              height={284}
              loading="lazy"
              style={{ objectFit: "cover", opacity: 0.8 }}
            />
          </Box>
        )}
      </Card>
    </Grid.Col>
  );
}

const getVisibleFrom = (index: number): "sm" | "md" | "xl" | undefined => {
  if (index === 0) return undefined; // Always visible
  if (index === 1) return "sm"; // 2+ columns
  if (index === 2) return "md"; // 3+ columns
  return "xl"; // 4+ columns
};
