"use client";

import { followUser } from "@/app/actions/followers";
import { FollowRequestBody } from "@/lib/types/strapi-autogenerated";
import { ActionIcon, Tooltip } from "@mantine/core";
import { useDisclosure } from "@mantine/hooks";
import { notifications } from "@mantine/notifications";
import { IconCheck, IconUsersPlus } from "@tabler/icons-react";
import { useTranslations } from "next-intl";
import { useTransition } from "react";
import { CreatorUpgradeModal } from "./creator-upgrade-modal";

export default function FollowButton({
  username,
  type,
  onSuccess,
}: FollowRequestBody & { onSuccess?: () => void }) {
  const [isPending, startTransition] = useTransition();
  const t = useTranslations("protected.common");
  const [upgradeOpened, { open: openUpgrade, close: closeUpgrade }] = useDisclosure(false);

  const handleClick = () => {
    startTransition(async () => {
      const result = await followUser({ username, type });

      if (result.success) {
        notifications.show({
          title: t("follow.successTitle"),
          message: t("follow.successMessage", { username }),
          color: "green",
          icon: <IconCheck size={16} />,
        });
        onSuccess?.();
      }

      if (result.error) {
        if (result.error === "MAX_3_FOLLOWERS") {
          openUpgrade();
        } else if (result.error === "MAX_50_FOLLOWERS") {
          notifications.show({
            title: t("follow.errorTitle"),
            message: t("followers.max50Message"),
            color: "red",
          });
        } else if (result.error === "MAX_100_FOLLOWERS") {
          notifications.show({
            title: t("follow.errorTitle"),
            message: t("followers.max100Message"),
            color: "red",
          });
        } else {
          notifications.show({
            title: t("follow.errorTitle"),
            message: result.error,
            color: "red",
          });
        }
      }
    });
  };

  return (
    <>
      <CreatorUpgradeModal opened={upgradeOpened} onClose={closeUpgrade} />

      <Tooltip label={t("follow.tooltip")}>
        <ActionIcon
          size="lg"
          color="red"
          onClick={handleClick}
          loading={isPending}
        >
          <IconUsersPlus />
        </ActionIcon>
      </Tooltip>
    </>
  );
}
