"use client";

import { downloadRecording } from "@/app/actions/download-recording";
import { deleteRecording, toggleHidden } from "@/app/actions/recording";
import { useWatchLater } from "@/app/hooks/use-watch-later";
import { useUser } from "@/app/providers/user-provider";
import { Recording } from "@/lib/types/strapi-autogenerated";
import { ActionIcon, Menu, Text } from "@mantine/core";
import { modals } from "@mantine/modals";
import { notifications } from "@mantine/notifications";
import {
  IconBookmark,
  IconBookmarkFilled,
  IconDots,
  IconDownload,
  IconEye,
  IconEyeOff,
  IconScissors,
  IconSparkles,
  IconTrash,
} from "@tabler/icons-react";
import { useQueryClient } from "@tanstack/react-query";
import { useLocale, useTranslations } from "next-intl";
import Link from "next/link";
import { useState } from "react";
import { DownloadUpgradeModal } from "./download-upgrade-modal";
import { VideoEditorModal } from "./video-editor-modal";

interface RecordingMenuProps {
  recording: Recording;
  username?: string;
  type?: string;
}

export function RecordingMenu({
  recording,
  username,
  type,
}: RecordingMenuProps) {
  const user = useUser();
  const t = useTranslations("protected.common.recordings");
  const queryClient = useQueryClient();
  const { isInWatchLater, toggleWatchLater } = useWatchLater();
  const locale = useLocale();
  const [downloadUpgradeOpened, setDownloadUpgradeOpened] = useState(false);
  const [editorOpened, setEditorOpened] = useState(false);

  const isOwner = user?.id && recording.follower?.owner?.id === user.id;
  const isFollowing = user?.followers?.some(
    (f) => f.documentId === recording.follower?.documentId,
  );
  const isPremium =
    user?.role?.type === "admin" ||
    user?.role?.type === "champion" ||
    user?.subscriptionStatus === "active";

  const inWatchLater = recording.documentId
    ? isInWatchLater(recording.documentId)
    : false;


  const handleDelete = () => {
    if (!recording.documentId) return;
    modals.openConfirmModal({
      title: t("deleteConfirm.title"),
      children: <Text size="sm">{t("deleteConfirm.message")}</Text>,
      labels: {
        confirm: t("deleteConfirm.confirm"),
        cancel: t("deleteConfirm.cancel"),
      },
      confirmProps: { color: "red" },
      onConfirm: async () => {
        const result = await deleteRecording(recording.documentId!);
        if (result.success && username && type) {
          queryClient.invalidateQueries({
            queryKey: ["recordings", username, type],
          });
        }
      },
    });
  };

  const handleToggleHidden = async () => {
    if (!recording.documentId) return;
    const result = await toggleHidden(recording.documentId, !!recording.hidden);
    if (result.success && username && type) {
      queryClient.invalidateQueries({
        queryKey: ["recordings", username, type],
      });
    }
  };

  const handleToggleWatchLater = () => {
    if (!recording.documentId) return;
    const wasInWatchLater = inWatchLater;
    toggleWatchLater(recording.documentId);
    notifications.show({
      title: wasInWatchLater
        ? t("removedFromWatchLater")
        : t("addedToWatchLater"),
      message: null,
      color: wasInWatchLater ? "gray" : "green",
    });
  };

  const handleDownload = async () => {
    if (!recording.documentId || !user?.id) return;
    if (!isPremium) {
      setDownloadUpgradeOpened(true);
      return;
    }
    await downloadRecording(recording.documentId, user.id, locale);
    notifications.show({
      title: t("downloadEmailSent"),
      message: null,
      color: "green",
    });
  };

  return (
    <>
      <Menu shadow="md">
        <Menu.Target>
          <ActionIcon
            variant="filled"
            color="dark"
            size="md"
            onClick={(e) => e.preventDefault()}
          >
            <IconDots />
          </ActionIcon>
        </Menu.Target>
        <Menu.Dropdown>
          <Menu.Item
            leftSection={
              inWatchLater ? <IconBookmarkFilled /> : <IconBookmark />
            }
            onClick={handleToggleWatchLater}
          >
            {inWatchLater ? t("removeFromWatchLater") : t("addToWatchLater")}
          </Menu.Item>
          {isFollowing && (
            <Menu.Item
              component={Link}
              href={`/ai-studio/create/${recording.documentId}`}
              leftSection={<IconSparkles />}
            >
              {t("createWithAI")}
            </Menu.Item>
          )}
          <Menu.Divider />
          <Menu.Item
            leftSection={<IconScissors />}
            onClick={() => setEditorOpened(true)}
          >
            Edit clip
          </Menu.Item>
          <Menu.Item leftSection={<IconDownload />} onClick={handleDownload}>
            {t("download")}
          </Menu.Item>
          {isOwner && (
            <>
              <Menu.Item
                leftSection={recording.hidden ? <IconEye /> : <IconEyeOff />}
                onClick={handleToggleHidden}
              >
                {recording.hidden ? t("show") : t("hide")}
              </Menu.Item>
              <Menu.Item
                color="red"
                leftSection={<IconTrash />}
                onClick={handleDelete}
              >
                {t("delete")}
              </Menu.Item>
            </>
          )}
        </Menu.Dropdown>
      </Menu>
      <DownloadUpgradeModal
        opened={downloadUpgradeOpened}
        onClose={() => setDownloadUpgradeOpened(false)}
      />
      <VideoEditorModal
        recording={recording}
        opened={editorOpened}
        onClose={() => setEditorOpened(false)}
      />
    </>
  );
}
