"use client";

import { deleteRecording, toggleHidden } from "@/app/actions/recording";
import { useWatchLater } from "@/app/hooks/use-watch-later";
import { useUser } from "@/app/providers/user-provider";
import { Recording } from "@/lib/types/strapi-autogenerated";
import { ActionIcon, Menu, Text } from "@mantine/core";
import { modals } from "@mantine/modals";
import {
  IconBookmark,
  IconBookmarkFilled,
  IconDots,
  IconEye,
  IconEyeOff,
  IconSparkles,
  IconTrash,
} from "@tabler/icons-react";
import { useQueryClient } from "@tanstack/react-query";
import { useTranslations } from "next-intl";
import Link from "next/link";

interface RecordingMenuProps {
  recording: Recording;
  username?: string;
  type?: string;
}

export function RecordingMenu({
  recording,
  username,
  type,
}: RecordingMenuProps) {
  const user = useUser();
  const t = useTranslations("protected.common.recordings");
  const queryClient = useQueryClient();
  const { isInWatchLater, toggleWatchLater } = useWatchLater();

  const isOwner = user?.id && recording.follower?.owner?.id === user.id;
  const isFollowing = user?.followers?.some(
    (f) => f.documentId === recording.follower?.documentId,
  );

  console.log(recording.follower, user?.followers);
  const inWatchLater = recording.documentId
    ? isInWatchLater(recording.documentId)
    : false;

  const handleDelete = () => {
    if (!recording.documentId) return;
    modals.openConfirmModal({
      title: t("deleteConfirm.title"),
      children: <Text size="sm">{t("deleteConfirm.message")}</Text>,
      labels: {
        confirm: t("deleteConfirm.confirm"),
        cancel: t("deleteConfirm.cancel"),
      },
      confirmProps: { color: "red" },
      onConfirm: async () => {
        const result = await deleteRecording(recording.documentId!);
        if (result.success && username && type) {
          queryClient.invalidateQueries({
            queryKey: ["recordings", username, type],
          });
        }
      },
    });
  };

  const handleToggleHidden = async () => {
    if (!recording.documentId) return;
    const result = await toggleHidden(recording.documentId, !!recording.hidden);
    if (result.success && username && type) {
      queryClient.invalidateQueries({
        queryKey: ["recordings", username, type],
      });
    }
  };

  const handleToggleWatchLater = () => {
    if (!recording.documentId) return;
    toggleWatchLater(recording.documentId);
  };

  return (
    <Menu shadow="md">
      <Menu.Target>
        <ActionIcon
          variant="filled"
          color="dark"
          size="md"
          onClick={(e) => e.preventDefault()}
        >
          <IconDots />
        </ActionIcon>
      </Menu.Target>
      <Menu.Dropdown>
        <Menu.Item
          leftSection={
            inWatchLater ? (
              <IconBookmarkFilled size={14} />
            ) : (
              <IconBookmark size={14} />
            )
          }
          onClick={handleToggleWatchLater}
        >
          {inWatchLater ? t("removeFromWatchLater") : t("addToWatchLater")}
        </Menu.Item>
        {isFollowing && (
          <Menu.Item
            component={Link}
            href={`/ai-studio/create/${recording.documentId}`}
            leftSection={<IconSparkles size={14} />}
          >
            {t("createWithAI")}
          </Menu.Item>
        )}
        {isOwner && (
          <>
            <Menu.Divider />
            <Menu.Item
              leftSection={
                recording.hidden ? (
                  <IconEye size={14} />
                ) : (
                  <IconEyeOff size={14} />
                )
              }
              onClick={handleToggleHidden}
            >
              {recording.hidden ? t("show") : t("hide")}
            </Menu.Item>
            <Menu.Item
              color="red"
              leftSection={<IconTrash size={14} />}
              onClick={handleDelete}
            >
              {t("delete")}
            </Menu.Item>
          </>
        )}
      </Menu.Dropdown>
    </Menu>
  );
}
