"use client";

import { Recording } from "@/lib/types/strapi-autogenerated";
import { Modal, Stack, Text, Title } from "@mantine/core";
import { useMediaQuery } from "@mantine/hooks";
import { useFormatter, useTranslations } from "next-intl";
import VideoEditor from "../protected/[type]/[username]/video/[id]/edit/video-editor";

interface VideoEditorModalProps {
  recording: Recording;
  opened: boolean;
  onClose: () => void;
}

export function VideoEditorModal({
  recording,
  opened,
  onClose,
}: VideoEditorModalProps) {
  const format = useFormatter();
  const isMobile = useMediaQuery("(max-width: 768px)");
  const t = useTranslations("protected.videoEditor");

  return (
    <Modal
      opened={opened}
      onClose={onClose}
      fullScreen={isMobile}
      size="90%"
      radius="md"
      styles={{
        content: {
          border: "1px solid var(--mantine-color-default-border)",
        },
      }}
      title={
        <Stack gap={2}>
          <Title order={4}>
            {t("modal.title")}{" "}
            {format.dateTime(new Date(recording.createdAt || ""), {
              dateStyle: "medium",
              timeStyle: "short",
            })}
          </Title>
          <Text size="sm" c="dimmed">
            {t("modal.description", {
              username: decodeURIComponent(recording.follower?.username || ""),
            })}
          </Text>
        </Stack>
      }
    >
      <VideoEditor recording={recording} />
    </Modal>
  );
}
