import dayjs from "@/app/lib/dayjs";
import {
  ActionIcon,
  Anchor,
  Button,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import { IconClock, IconVideo, IconWorldSearch } from "@tabler/icons-react";
import {
  dehydrate,
  HydrationBoundary,
  InfiniteData,
  QueryClient,
} from "@tanstack/react-query";
import { getTranslations } from "next-intl/server";
import { redirect } from "next/navigation";

import { Follower } from "@/lib/types/strapi-autogenerated";

import { fetchProfileRecordings, getFollower } from "./actions/actions";
import { ProfileHeader } from "./components/profile-header";
import ProfileRecordings from "./components/profile-recordings";
import { ProfileFilters, profileParamsCache } from "./lib/search-params";

interface PageProps {
  params: Promise<{
    username: string;
    type: string;
  }>;
  searchParams: Promise<ProfileFilters>;
}

export default async function Page({ params, searchParams }: PageProps) {
  const { type, username } = await params;
  const filters = await profileParamsCache.parse(searchParams);

  const follower = await getFollower({ username, type });

  if (!follower) {
    redirect(`/search?username=${username}&type=${type}`);
  }

  const queryClient = new QueryClient();

  // Query key uses type/username - matches what modal will use
  await queryClient.prefetchInfiniteQuery({
    queryKey: ["profile-recordings", type, username, filters],
    queryFn: ({ pageParam }) =>
      fetchProfileRecordings(type, username, filters, pageParam),
    initialPageParam: 1,
  });

  const initialData = queryClient.getQueryData<
    InfiniteData<Awaited<ReturnType<typeof fetchProfileRecordings>>>
  >(["profile-recordings", type, username, filters]);

  const recordings = initialData?.pages?.[0]?.data ?? [];
  const isRecording = recordings.some((r) =>
    r.sources?.some((s) => s.state === "recording"),
  );
  const hasRecordings = recordings.length > 0;

  return (
    <section>
      <ProfileHeader follower={follower} isRecording={isRecording} />

      {!hasRecordings ? (
        <EmptyState follower={follower} />
      ) : (
        <HydrationBoundary state={dehydrate(queryClient)}>
          <ProfileRecordings />
        </HydrationBoundary>
      )}
    </section>
  );
}

async function EmptyState({ follower }: { follower: Follower }) {
  const t = await getTranslations("protected.profile");
  const isNewlyAdded = dayjs().diff(dayjs(follower.createdAt), "minute") < 5;

  if (isNewlyAdded) {
    return (
      <Stack align="center" justify="center" py={80} gap="lg">
        <ActionIcon variant="transparent" size={120} radius="xl" color="blue">
          <IconClock size={90} stroke={2} />
        </ActionIcon>
        <Stack align="center" gap={12}>
          <Title order={2} fw={600}>
            {t("emptyNewlyAdded.title", { username: follower.username })}
          </Title>
          <Text size="xl" c="dimmed" maw={450} ta="center">
            {t("emptyNewlyAdded.description")}
          </Text>
        </Stack>
      </Stack>
    );
  }

  return (
    <Stack align="center" justify="center" py={80} gap="lg">
      <ActionIcon variant="transparent" size={120} radius="xl" color="white">
        <IconVideo size={90} stroke={2} />
      </ActionIcon>
      <Stack align="center" gap={12}>
        <Title order={2} fw={600}>
          {t("emptyDefault.title")}
        </Title>
        <Text size="xl" c="dimmed" maw={450} ta="center">
          {t("emptyDefault.description", { username: follower.username })}
        </Text>
      </Stack>
      <Anchor href="/discover" underline="never">
        <Button
          size="lg"
          radius="md"
          leftSection={<IconWorldSearch size={20} />}
        >
          {t("discoverStreamers")}
        </Button>
      </Anchor>
    </Stack>
  );
}
