import { countryCodeToSlug, getCountryName } from "@/app/lib/country-utils";
import { getFollowerFilters } from "../../cache";
import { streamingPlatforms } from "@/app/lib/streaming-platforms";
import { FollowerTypeEnum } from "@/lib/types/strapi-autogenerated";
import {
  Button,
  Container,
  Group,
  Image as MantineImage,
  Paper,
  SimpleGrid,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import { getLocale, getTranslations } from "next-intl/server";
import Image from "next/image";
import Link from "@/app/components/link";
import ReactMarkdown from "react-markdown";
import { FAQSection } from "../../../components/faq-section";
import { PlatformBadges } from "../../../components/platform-badge";

interface PageProps {
  params: Promise<{
    type: string;
  }>;
  children: React.ReactNode;
}

export default async function Layout({ params, children }: PageProps) {
  const { type } = await params;
  const locale = await getLocale();
  const t = await getTranslations("creators");

  const platform = streamingPlatforms.find(
    (p) => p.name.toLowerCase() === type,
  ) || {
    color: "#ff0050",
    name: "",
    file: "creators.png",
  };

  const platformKey = platform.name ? type : "all";

  // Only fetch countries when a specific platform is selected
  const { countryCodes } = platform.name
    ? await getFollowerFilters(platform.name.toLowerCase() as FollowerTypeEnum)
    : { countryCodes: [] };

  // Sort countries by name
  const sortedCountries = countryCodes
    .map(({ value: code }) => ({
      code,
      name: getCountryName(code, locale),
      slug: countryCodeToSlug(code, "en"), // Always use English for URL slugs
    }))
    .sort((a, b) => a.name.localeCompare(b.name, locale));

  return (
    <Container size="xl">
      <div
        style={{
          position: "absolute",
          top: 0,
          left: 0,
          width: "100%",
          height: 700,
          zIndex: 0,
          pointerEvents: "none",
        }}
      >
        <Image
          src="/creators.svg"
          alt="background"
          fill
          priority
          style={{ objectFit: "cover" }}
        />
      </div>
      <Stack align="center" gap={24} mb={60}>
        <Title
          order={1}
          ta="center"
          style={{
            fontSize: "clamp(2.5rem, 6vw, 4rem)",
            fontWeight: 800,
            lineHeight: 1.2,
            letterSpacing: "-0.03em",
            background:
              "linear-gradient(135deg, #ffffff 0%, #e2e8f0 50%, #94a3b8 100%)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
            paddingBottom: "0.1em",
          }}
        >
          {t(`hero.title.${platformKey}`)}
        </Title>

        <Text
          size="xl"
          ta="center"
          maw={600}
          style={{ color: "#94a3b8", lineHeight: 1.7 }}
        >
          {t(`hero.subtitle.${platformKey}`)}
        </Text>
      </Stack>

      <PlatformBadges href={`/creators/`} activePlatform={type} />

      {children}

      {/* CTA Section */}
      <div style={{ marginTop: 100 }}>
        <Paper
          p={60}
          style={{
            background:
              "linear-gradient(135deg, rgba(99, 102, 241, 0.15) 0%, rgba(168, 85, 247, 0.1) 100%)",
            border: "1px solid rgba(99, 102, 241, 0.2)",
            borderRadius: "32px",
            textAlign: "center",
            position: "relative",
            overflow: "hidden",
          }}
        >
          <div
            style={{
              position: "absolute",
              top: "-50%",
              left: "50%",
              transform: "translateX(-50%)",
              width: "100%",
              height: "200%",
              background:
                "radial-gradient(ellipse at center, rgba(99, 102, 241, 0.1) 0%, transparent 50%)",
              pointerEvents: "none",
            }}
          />
          <Stack
            align="center"
            gap={24}
            style={{ position: "relative", zIndex: 1 }}
          >
            <Title
              order={2}
              style={{
                fontSize: "clamp(1.75rem, 4vw, 2.5rem)",
                fontWeight: 700,
                color: "#f1f5f9",
              }}
            >
              {t(`cta.title.${platformKey}`)}
            </Title>
            <Text size="lg" style={{ color: "#94a3b8", lineHeight: 1.7 }}>
              {t(`cta.subtitle.${platformKey}`)}
            </Text>

            <Button
              component="a"
              href="/register"
              size="responsive"
              radius="lg"
              variant="gradient"
              gradient={{ from: "#6366f1", to: "#a855f7", deg: 135 }}
              style={{ fontWeight: 600 }}
            >
              {t("cta.button")}
            </Button>
          </Stack>
        </Paper>
      </div>

      {/* Browse by Country Section */}
      {sortedCountries.length > 0 && (
        <div style={{ marginTop: 100 }}>
          <Title order={2} ta="center" mb="xl" style={{ color: "#f1f5f9" }}>
            {t("country.browseByCountry", {
              platform: t(`hero.title.${platformKey}`),
            })}
          </Title>
          <SimpleGrid cols={{ base: 1, xs: 2, sm: 3, md: 4 }} spacing="md">
            {sortedCountries.map(({ code, name, slug }) => (
              <Link
                key={code}
                href={`/creators/${type}/${slug}`}
                style={{ textDecoration: "none" }}
              >
                <Group gap="xs" wrap="nowrap">
                  <MantineImage
                    src={`https://flagcdn.com/w40/${code.toLowerCase()}.png`}
                    alt={name}
                    w={24}
                    h={18}
                    radius={2}
                    fit="cover"
                  />
                  <Text truncate="end" size="sm" c="dimmed">
                    {t("country.browseLink", {
                      platform: t(`hero.title.${platformKey}`),
                      country: name,
                    })}
                  </Text>
                </Group>
              </Link>
            ))}
          </SimpleGrid>
        </div>
      )}

      {t.has(`meta.${type}.faqs`) &&
        (() => {
          const faqs = t.raw(`meta.${type}.faqs`) as {
            question: string;
            answer: string;
          }[];
          return faqs.length > 0 ? (
            <div style={{ marginTop: 100 }}>
              <FAQSection faqs={faqs} title={t("faq")} />
            </div>
          ) : null;
        })()}

      <div style={{ marginTop: 100 }}>
        <ReactMarkdown
          components={{
            h2: ({ children }) => (
              <Title order={2} mb="sm" style={{ color: "#f1f5f9" }}>
                {children}
              </Title>
            ),
            h3: ({ children }) => (
              <Title order={4} mt="xl" style={{ color: "#f1f5f9" }}>
                {children}
              </Title>
            ),
            p: ({ children }) => (
              <Text mt="xs" style={{ color: "#94a3b8" }}>
                {children}
              </Text>
            ),
          }}
        >
          {t(`about.${platformKey}`)}
        </ReactMarkdown>
      </div>
    </Container>
  );
}
