import { FollowerTypeText } from "@/app/[locale]/(protected)/components/follower-type-text";
import { formatDuration } from "@/app/[locale]/(protected)/components/video/player-utils";
import { getImageUrl } from "@/app/lib/media-url";
import { getProfileUrl } from "@/app/components/open-social";
import { Recording } from "@/lib/types/strapi-autogenerated";
import {
  ActionIcon,
  Anchor,
  Card,
  Flex,
  SimpleGrid,
  Stack,
  Text,
} from "@mantine/core";
import { IconPlayerPlay } from "@tabler/icons-react";
import { getFormatter, getTranslations } from "next-intl/server";
import Image from "next/image";

export async function RecordingsSimpleGrid({
  recordings,
}: {
  recordings: Recording[] | undefined;
}) {
  const t = await getTranslations("recordings");
  const format = await getFormatter();

  return (
    <SimpleGrid cols={{ base: 1, sm: 4 }}>
      {recordings?.map((recording) => {
        const totalDuration =
          recording.sources?.reduce((sum, s) => sum + (s.duration || 0), 0) ||
          0;

        const firstDoneSource = recording.sources?.find((s) => s.state === "done");
        const previewUrl = getImageUrl(recording.documentId!, "preview.jpg", firstDoneSource);

        return (
          <div key={recording.id}>
            <Anchor
              href={`${getProfileUrl(recording.follower)}/video/${
                recording.documentId
              }`}
              underline="never"
            >
              <Card
                padding={0}
                style={{
                  background: "rgba(255, 255, 255, 0.02)",
                  border: "1px solid rgba(255, 255, 255, 0.06)",
                  borderRadius: "16px",
                  overflow: "hidden",
                  cursor: "pointer",
                }}
              >
                <div
                  style={{ position: "relative", width: "100%", height: 160 }}
                >
                  <Image
                    src={previewUrl}
                    alt={`${recording.follower?.username} ${t("recordedOn", {
                      date: format.dateTime(
                        new Date(recording.createdAt || ""),
                        {
                          year: "numeric",
                          month: "short",
                          day: "numeric",
                          hour: "numeric",
                          minute: "2-digit",
                        },
                      ),
                    })}`}
                    fill
                    unoptimized
                    loading="lazy"
                    sizes="(max-width: 640px) 100vw, 25vw"
                    style={{ objectFit: "cover" }}
                  />

                  <Flex
                    style={{
                      position: "absolute",
                      bottom: 4,
                      right: 4,
                      background: "rgba(0, 0, 0, 0.7)",
                      padding: "2px 4px",
                      borderRadius: "2px",
                    }}
                  >
                    <Text size="xs" c="white">
                      {formatDuration(totalDuration)}
                    </Text>
                  </Flex>
                  <ActionIcon
                    variant="filled"
                    size="xl"
                    radius="xl"
                    aria-label="Play video"
                    style={{
                      position: "absolute",
                      top: "50%",
                      left: "50%",
                      transform: "translate(-50%, -50%)",
                      background: "rgba(99, 102, 241, 0.9)",
                      opacity: 0.9,
                    }}
                  >
                    <IconPlayerPlay size={20} />
                  </ActionIcon>

                  <Flex
                    style={{
                      position: "absolute",
                      top: 4,
                      right: 4,
                      padding: "2px 4px",
                      borderRadius: "2px",
                    }}
                  >
                    <FollowerTypeText type={recording.follower?.type} />
                  </Flex>
                </div>
                <Flex p="xs" align="center" justify="space-between">
                  <Stack gap={2}>
                    <Text
                      fw={600}
                      size="sm"
                      lineClamp={2}
                      style={{ color: "#f1f5f9", lineHeight: 1.4 }}
                    >
                      {recording.follower?.nickname || "-"}
                    </Text>

                    <Text size="xs" c="dimmed">
                      {t("recordedOn", {
                        date: format.dateTime(
                          new Date(recording.createdAt || ""),
                          {
                            year: "numeric",
                            month: "short",
                            day: "numeric",
                            hour: "numeric",
                            minute: "2-digit",
                          },
                        ),
                      })}
                    </Text>
                  </Stack>
                </Flex>
              </Card>
            </Anchor>
          </div>
        );
      })}
    </SimpleGrid>
  );
}
